[package]
name = "filesystem"
version = "0.1.0"
edition = "2021"

[features]
diff = []
local = ["dep:async-std", "dep:ignore", "dep:futures", "dep:sha256"]
test_utils = ["local", "dep:tempfile"]

[dependencies]
anyhow = { version = "1.0" }
async-trait = "0.1"
camino = "1.1"
flume = "0.10.14"
tokio = { version = "1.26", features = ["full"] }
tracing = { version = "0.1" }

# Optional dependencies
async-std = { version = "1.12", optional = true }
futures = { version = "0.3", optional = true }
ignore = { version = "0.4", optional = true }
sha256 = { version = "1.1", optional = true }
tempfile = { version = "3", optional = true }

[dev-dependencies]
filesystem = { path = ".", features = ["test_utils", "diff"] }