# Generated by Django 5.1.2 on 2024-10-22 09:00

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        help_text="Official account identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ccy",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "Euro"), ("USD", "US Dollar")], default=None, max_length=3
                    ),
                ),
                ("open", models.DateField()),
                ("close", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AccountHolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "is_company",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the holder is a company or a physical person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Custodian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("country", django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Fx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "foreign",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "Euro"), ("USD", "US Dollar")],
                        default=None,
                        help_text="Foreign (quoted) currency",
                        max_length=3,
                    ),
                ),
                (
                    "local",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "Euro"), ("USD", "US Dollar")],
                        default="EUR",
                        help_text="Local/foreign currency",
                        max_length=3,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="How many 'foreign' you need to take a 'local'",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("date_value", models.DateField()),
            ],
            options={
                "ordering": ["-date_value"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("once", "Once in a lifetime"),
                            ("year", "Every year"),
                            ("month", "Every month"),
                            ("quarter", "Every quarter"),
                        ],
                        default="once",
                        help_text="How often this same group is rescheduled",
                        max_length=10,
                    ),
                ),
                (
                    "start",
                    models.DateField(
                        help_text="For recurring groups, this will be the base date to compute the cadence. For non recurring events, this is just the date of the single occurrence"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountHolderRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "owns_money",
                    models.BooleanField(
                        default=True,
                        help_text="This person will also be the owner of the money it contains. Furthermore, if there are any debt due to having taken out a loan, this person will be liable for the tax obligations",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finances_data.account"
                    ),
                ),
                (
                    "holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances_data.accountholder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="holders",
            field=models.ManyToManyField(
                through="finances_data.AccountHolderRole", to="finances_data.accountholder"
            ),
        ),
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tn_ancestors_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Ancestors pks"
                    ),
                ),
                (
                    "tn_ancestors_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Ancestors count"
                    ),
                ),
                (
                    "tn_children_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Children pks"
                    ),
                ),
                (
                    "tn_children_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Children count"
                    ),
                ),
                (
                    "tn_depth",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Depth",
                    ),
                ),
                (
                    "tn_descendants_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Descendants pks"
                    ),
                ),
                (
                    "tn_descendants_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Descendants count"
                    ),
                ),
                (
                    "tn_index",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Index"),
                ),
                (
                    "tn_level",
                    models.PositiveIntegerField(
                        default=1,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Level",
                    ),
                ),
                (
                    "tn_priority",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999999999),
                        ],
                        verbose_name="Priority",
                    ),
                ),
                (
                    "tn_order",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Order"),
                ),
                (
                    "tn_siblings_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Siblings pks"
                    ),
                ),
                (
                    "tn_siblings_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Siblings count"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_abstract",
                    models.BooleanField(
                        default=False, help_text="If the category can be instantiated or not"
                    ),
                ),
                (
                    "is_numerable",
                    models.BooleanField(
                        default=False,
                        help_text="Account with stocks are numerable (units), a bank account or a mortage is not",
                    ),
                ),
                (
                    "tn_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tn_children",
                        to="finances_data.accounttype",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "ordering": ["tn_order"],
                "abstract": False,
                "unique_together": {("tn_parent", "name")},
            },
        ),
        migrations.AddField(
            model_name="account",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="finances_data.accounttype"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="custodian",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="finances_data.custodian"
            ),
        ),
        migrations.CreateModel(
            name="MovementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tn_ancestors_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Ancestors pks"
                    ),
                ),
                (
                    "tn_ancestors_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Ancestors count"
                    ),
                ),
                (
                    "tn_children_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Children pks"
                    ),
                ),
                (
                    "tn_children_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Children count"
                    ),
                ),
                (
                    "tn_depth",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Depth",
                    ),
                ),
                (
                    "tn_descendants_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Descendants pks"
                    ),
                ),
                (
                    "tn_descendants_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Descendants count"
                    ),
                ),
                (
                    "tn_index",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Index"),
                ),
                (
                    "tn_level",
                    models.PositiveIntegerField(
                        default=1,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Level",
                    ),
                ),
                (
                    "tn_priority",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999999999),
                        ],
                        verbose_name="Priority",
                    ),
                ),
                (
                    "tn_order",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Order"),
                ),
                (
                    "tn_siblings_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Siblings pks"
                    ),
                ),
                (
                    "tn_siblings_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Siblings count"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_abstract",
                    models.BooleanField(
                        default=False, help_text="If the category can be instantiated or not"
                    ),
                ),
                (
                    "tn_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tn_children",
                        to="finances_data.movementtype",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "ordering": ["tn_order"],
                "abstract": False,
                "unique_together": {("tn_parent", "name")},
            },
        ),
        migrations.CreateModel(
            name="MovementNumerable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("direction", models.IntegerField(choices=[(0, "IN"), (1, "OUT")])),
                ("date_value", models.DateField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Number of units. Typically this will be an integer, but some accounts allow fractional units",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Value per unit",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finances_data.account"
                    ),
                ),
                (
                    "fx",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is the FX used for this movement (it doesn't need to be exactly the same as the official one for this 'date_value', as FX varies along the day)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finances_data.fx",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finances_data.movementtype"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finances_data.transaction"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_value"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MovementNonNumerable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("direction", models.IntegerField(choices=[(0, "IN"), (1, "OUT")])),
                ("date_value", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finances_data.account"
                    ),
                ),
                (
                    "fx",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is the FX used for this movement (it doesn't need to be exactly the same as the official one for this 'date_value', as FX varies along the day)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finances_data.fx",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finances_data.movementtype"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finances_data.transaction"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_value"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MovementDividend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("direction", models.IntegerField(choices=[(0, "IN"), (1, "OUT")])),
                ("date_value", models.DateField()),
                (
                    "ex_dividend_date",
                    models.DateField(help_text="Date when the dividend is assigned"),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Dividen per stock",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finances_data.account"
                    ),
                ),
                (
                    "fx",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is the FX used for this movement (it doesn't need to be exactly the same as the official one for this 'date_value', as FX varies along the day)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finances_data.fx",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finances_data.movementtype"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finances_data.transaction"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_value"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Which group (if any) this transaction belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finances_data.transactiongroup",
            ),
        ),
        migrations.CreateModel(
            name="SnapshotNonNumerable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_value", models.DateField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finances_data.account"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_value"],
                "abstract": False,
                "unique_together": {("account", "date_value")},
            },
        ),
        migrations.CreateModel(
            name="SnapshotNumerable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date_value", models.DateField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Number of units own. Typically this will be an integer, but some accounts allow fractional units",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Value of each of the units (use the currency of the account)",
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finances_data.account"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_value"],
                "abstract": False,
                "unique_together": {("account", "date_value")},
            },
        ),
    ]
