# Generated by Django 5.1.2 on 2024-10-15 16:39

import datetime
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances_data', '0002_accountholder_custodian_account_accountholders_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountHolders',
            new_name='AccountHolderRole',
        ),
        migrations.AddField(
            model_name='account',
            name='ccy',
            field=djmoney.models.fields.CurrencyField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='account',
            name='close',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='open',
            field=models.DateField(default=datetime.date(2024, 10, 15)),
            preserve_default=False,
        ),
    ]
