# Generated by Django 5.1.2 on 2024-10-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances_data', '0006_custodian_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transfer',
            new_name='Transaction',
        ),
        migrations.RenameModel(
            old_name='TransferType',
            new_name='TransactionType',
        ),
    ]
