# Generated by Django 5.1.2 on 2024-10-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances_data", "0007_rename_transfer_transaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountholder",
            name="is_company",
            field=models.BooleanField(
                default=True, help_text="Whether the holder is a company or a physical person"
            ),
        ),
    ]
