# Generated by Django 5.1.2 on 2024-10-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances_data", "0008_accountholder_is_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_numerable",
        ),
        migrations.AddField(
            model_name="accounttype",
            name="is_numerable",
            field=models.BooleanField(
                default=False,
                help_text="Account with stocks are numerable (units), a bank account or a mortage is not",
            ),
        ),
    ]
