# Generated by Django 5.1.2 on 2024-10-17 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances_data", "0009_remove_account_is_numerable_accounttype_is_numerable"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("once", "Once in a lifetime"),
                            ("year", "Every year"),
                            ("month", "Every month"),
                            ("quarter", "Every quarter"),
                        ],
                        default="once",
                        help_text="How often this same group is rescheduled",
                        max_length=10,
                    ),
                ),
                (
                    "start",
                    models.DateField(
                        help_text="For recurring groups, this will be the base date to compute the cadence. For non recurring events, this is just the date of the single occurrence"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="type",
        ),
        migrations.AddField(
            model_name="transaction",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Which group (if any) this transaction belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finances_data.transactiongroup",
            ),
        ),
        migrations.DeleteModel(
            name="TransactionType",
        ),
    ]
