# Generated by Django 5.1.2 on 2024-10-21 09:26

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances_data', '0010_transactiongroup_remove_transaction_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default=None, help_text='Foreign (quoted) currency', max_length=3)),
                ('local', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', help_text='Local/foreign currency', max_length=3)),
                ('rate', models.DecimalField(decimal_places=4, help_text="How many 'foreign' you need to take a 'local'", max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_value', models.DateField()),
            ],
            options={
                'ordering': ['-date_value'],
            },
        ),
        migrations.AlterField(
            model_name='snapshotnumerable',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Number of units own. Typically this will be an integer, but some accounts allow fractional units', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='snapshotnumerable',
            name='unit_value',
            field=models.DecimalField(decimal_places=4, help_text='Value of each of the units (use the currency of the account)', max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='MovementDividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField(choices=[(0, 'IN'), (1, 'OUT')])),
                ('date_value', models.DateField()),
                ('ex_dividend_date', models.DateField(help_text='Date when the dividend is assigned')),
                ('unit_value', models.DecimalField(decimal_places=4, help_text='Dividen per stock', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_data.account')),
                ('fx', models.ForeignKey(blank=True, help_text="This is the FX used for this movement (it doesn't need to be exactly the same as the official one for this 'date_value', as FX varies along the day)", null=True, on_delete=django.db.models.deletion.PROTECT, to='finances_data.fx')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances_data.transaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_data.movementtype')),
            ],
            options={
                'ordering': ['-date_value'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovementNonNumerable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField(choices=[(0, 'IN'), (1, 'OUT')])),
                ('date_value', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_data.account')),
                ('fx', models.ForeignKey(blank=True, help_text="This is the FX used for this movement (it doesn't need to be exactly the same as the official one for this 'date_value', as FX varies along the day)", null=True, on_delete=django.db.models.deletion.PROTECT, to='finances_data.fx')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances_data.transaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_data.movementtype')),
            ],
            options={
                'ordering': ['-date_value'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovementNumerable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.IntegerField(choices=[(0, 'IN'), (1, 'OUT')])),
                ('date_value', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Number of units. Typically this will be an integer, but some accounts allow fractional units', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_value', models.DecimalField(decimal_places=4, help_text='Value per unit', max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_data.account')),
                ('fx', models.ForeignKey(blank=True, help_text="This is the FX used for this movement (it doesn't need to be exactly the same as the official one for this 'date_value', as FX varies along the day)", null=True, on_delete=django.db.models.deletion.PROTECT, to='finances_data.fx')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances_data.transaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances_data.movementtype')),
            ],
            options={
                'ordering': ['-date_value'],
                'abstract': False,
            },
        ),
    ]
