# Generated by Django 5.1.2 on 2024-10-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances_data', '0011_fx_alter_snapshotnumerable_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movementdividend',
            old_name='transfer',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='movementnonnumerable',
            old_name='transfer',
            new_name='transaction',
        ),
        migrations.RenameField(
            model_name='movementnumerable',
            old_name='transfer',
            new_name='transaction',
        ),
    ]
