load("@aspect_rules_py//py:defs.bzl", "py_pytest_main", "py_test")
load("@py_deps//:requirements.bzl", "requirement")

py_pytest_main(
    name = "__test__",
)

py_test(
    name = "tests",
    srcs = [
        "__test__.py",
    ] + glob(["**/*.py"]),
    main = ":__test__.py",
    deps = [
        "//bazel/tools/semver",
        requirement("pytest"),
    ],
)
