// @generated by protoc-gen-connect-es v1.6.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file apps/finances/tauri/models/protos/account.proto (package finances_app_models, syntax proto3)
/* eslint-disable */
// @ts-nocheck

