// @generated by protoc-gen-es v2.8.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/account_context.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Account } from "./account_pb.js";
import type { Movement } from "./movement_pb.js";
import type { Snapshot } from "./snapshot_pb.js";

/**
 * Describes the file apps/finances/tauri/models/protos/account_context.proto.
 */
export declare const file_apps_finances_tauri_models_protos_account_context: GenFile;

/**
 * Data available for the selected account
 *
 * @generated from message finances_app_models.AccountContext
 */
export declare type AccountContext = Message<"finances_app_models.AccountContext"> & {
  /**
   * @generated from field: finances_app_models.Account account = 1;
   */
  account?: Account;

  /**
   * @generated from field: repeated finances_app_models.Movement movements = 2;
   */
  movements: Movement[];

  /**
   * @generated from field: repeated finances_app_models.Snapshot snapshots = 3;
   */
  snapshots: Snapshot[];
};

/**
 * Describes the message finances_app_models.AccountContext.
 * Use `create(AccountContextSchema)` to create a new message.
 */
export declare const AccountContextSchema: GenMessage<AccountContext>;

