syntax = "proto3";
package finances_app_models;

import "google/protobuf/timestamp.proto";
import "apps/finances/tauri/models/protos/custodian.proto";
import "apps/finances/tauri/models/protos/ccy.proto";

// Main account categories
enum AccountCategory {
  Other = 0;
  Savings = 1;
  Investment = 2;
  Retirement = 3;
}

// Fine-grained account type
message AccountType {
  int64 pk = 1;
  string name = 2;
  // Last element in the breadcrumb is the account-type itself. This way, if the breadcrumb is empty, it has not been populated.
  repeated string breadcrumb = 3;
  AccountCategory category = 4;
}


message Account {
  int64 pk = 1;
  string name = 2;
  Custodian custodian = 3;

  int64 account_type_pk = 4;
  Ccy ccy = 5;

  optional string identifier = 6;
  optional string description = 7;

  optional google.protobuf.Timestamp open = 8;

  bool holder_owns_money = 9;
  bool is_numerable = 10;
}
