syntax = "proto3";
package finances_app_models;

import "apps/finances/tauri/models/protos/custodian.proto";
import "libraries/googleapis/protos/google/type/date.proto";
import "apps/finances/tauri/models/protos/snapshot.proto";

// Main account categories
enum AccountCategory {
  Other = 0;
  Savings = 1;
  Investment = 2;
  Retirement = 3;
}

// Fine-grained account type
message AccountType {
  int64 pk = 1;
  string name = 2;
  // Last element in the breadcrumb is the account-type itself. This way, if the breadcrumb is empty, it has not been populated.
  repeated string breadcrumb = 3;
  AccountCategory category = 4;
}


message Account {
  int64 pk = 1;
  string name = 2;
  Custodian custodian = 3;

  AccountType type = 4;
  // The three-letter currency code defined in ISO 4217.
  string currency_code = 5;

  optional string identifier = 6;
  optional string description = 7;

  google.type.Date open = 8;

  bool holder_owns_money = 9;
  bool is_numerable = 10;

  optional Snapshot last_snapshot = 11;
}
