syntax = "proto3";
package finances_app_models;

import "apps/finances/tauri/models/protos/holder.proto";

message DatabaseConnection {
    string user = 1;
    string password = 2;
    string host = 3;
    // Expecting u16
    uint32 port = 4;
    string dbname = 5;
}

message AppState {
    // The three-letter currency code defined in ISO 4217.
    string base_ccy = 1;

    // Base URL to all media resources
    string base_media_url = 2;

    // Base URL to static content
    string base_static_url = 3;

    // Base URL to the site root
    string base_url = 4;

    // Current DB connection
    DatabaseConnection db = 5;

    // Backup directory
    string backup_folder = 6;

    // Active account holder. Used as filter if applicable
    optional Holder holder = 7;
}
