// @generated by protoc-gen-es v2.3.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/app_state.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apps/finances/tauri/models/protos/app_state.proto.
 */
export declare const file_apps_finances_tauri_models_protos_app_state: GenFile;

/**
 * @generated from message finances_app_models.DatabaseConnection
 */
export declare type DatabaseConnection = Message<"finances_app_models.DatabaseConnection"> & {
  /**
   * @generated from field: string user = 1;
   */
  user: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;

  /**
   * @generated from field: string host = 3;
   */
  host: string;

  /**
   * @generated from field: uint32 port = 4;
   */
  port: number;

  /**
   * @generated from field: string dbname = 5;
   */
  dbname: string;
};

/**
 * Describes the message finances_app_models.DatabaseConnection.
 * Use `create(DatabaseConnectionSchema)` to create a new message.
 */
export declare const DatabaseConnectionSchema: GenMessage<DatabaseConnection>;

/**
 * @generated from message finances_app_models.AppState
 */
export declare type AppState = Message<"finances_app_models.AppState"> & {
  /**
   * @generated from field: string base_ccy = 1;
   */
  baseCcy: string;

  /**
   * @generated from field: string base_media_url = 2;
   */
  baseMediaUrl: string;

  /**
   * @generated from field: string base_static_url = 3;
   */
  baseStaticUrl: string;

  /**
   * @generated from field: string base_url = 4;
   */
  baseUrl: string;

  /**
   * @generated from field: finances_app_models.DatabaseConnection db = 5;
   */
  db?: DatabaseConnection;

  /**
   * @generated from field: string backup_folder = 6;
   */
  backupFolder: string;
};

/**
 * Describes the message finances_app_models.AppState.
 * Use `create(AppStateSchema)` to create a new message.
 */
export declare const AppStateSchema: GenMessage<AppState>;

