load("@aspect_rules_ts//ts:proto.bzl", "ts_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_rust_prost//:defs.bzl", "rust_prost_library")

protos = [
    "account.proto",
    "app_state.proto",
    "ccy.proto",
    "custodian.proto",
    "holder_context.proto",
    "holder.proto",
    "main_context.proto",
]

proto_library(
    name = "protos",
    srcs = protos,
    deps = ["@protobuf//:timestamp_proto"],
)

# This rule generates (and copies to the workspace) the proto files for Typescript
ts_proto_library(
    name = "protos_ts",
    node_modules = "//apps/finances/tauri/models:node_modules",
    proto = ":protos",
    proto_srcs = protos,
    protoc_gen_options = {
        "import_extension": "js",
    },
    visibility = ["//visibility:public"],
)

# Generate Rust bindings from the generated proto files
rust_prost_library(
    name = "protos_rs",
    proto = ":protos",
    # TODO: Wait for https://github.com/bazelbuild/rules_rust/issues/2831, so we can add type_attributes, if not we can go the build.rs way
    visibility = ["//apps/finances/tauri/models:__subpackages__"],
)
