// @generated by protoc-gen-es v2.2.3 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/ccy.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file apps/finances/tauri/models/protos/ccy.proto.
 */
export declare const file_apps_finances_tauri_models_protos_ccy: GenFile;

/**
 * @generated from enum finances_app_models.Ccy
 */
export enum Ccy {
  /**
   * @generated from enum value: USD = 0;
   */
  USD = 0,

  /**
   * @generated from enum value: EUR = 1;
   */
  EUR = 1,
}

/**
 * Describes the enum finances_app_models.Ccy.
 */
export declare const CcySchema: GenEnum<Ccy>;

