// @generated by protoc-gen-es v2.2.4 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/custodian.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apps/finances/tauri/models/protos/custodian.proto.
 */
export declare const file_apps_finances_tauri_models_protos_custodian: GenFile;

/**
 * @generated from message finances_app_models.Custodian
 */
export declare type Custodian = Message<"finances_app_models.Custodian"> & {
  /**
   * @generated from field: int64 pk = 1;
   */
  pk: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional string photo = 3;
   */
  photo?: string;
};

/**
 * Describes the message finances_app_models.Custodian.
 * Use `create(CustodianSchema)` to create a new message.
 */
export declare const CustodianSchema: GenMessage<Custodian>;

