// @generated by protoc-gen-es v2.2.3 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/fx.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Decimal } from "../../../../../libraries/googleapis/protos/google/type/decimal_pb.js";
import type { Date } from "../../../../../libraries/googleapis/protos/google/type/date_pb.js";

/**
 * Describes the file apps/finances/tauri/models/protos/fx.proto.
 */
export declare const file_apps_finances_tauri_models_protos_fx: GenFile;

/**
 * @generated from message finances_app_models.Fx
 */
export declare type Fx = Message<"finances_app_models.Fx"> & {
  /**
   * @generated from field: string foreign_code = 1;
   */
  foreignCode: string;

  /**
   * @generated from field: string local_code = 2;
   */
  localCode: string;

  /**
   * @generated from field: google.type.Decimal fx = 3;
   */
  fx?: Decimal;

  /**
   * @generated from field: google.type.Date date_value = 4;
   */
  dateValue?: Date;
};

/**
 * Describes the message finances_app_models.Fx.
 * Use `create(FxSchema)` to create a new message.
 */
export declare const FxSchema: GenMessage<Fx>;

