// @generated by protoc-gen-es v2.7.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/fx_quote.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Decimal } from "../../../../../libraries/googleapis/protos/google/type/decimal_pb.js";
import type { Date } from "../../../../../libraries/googleapis/protos/google/type/date_pb.js";

/**
 * Describes the file apps/finances/tauri/models/protos/fx_quote.proto.
 */
export declare const file_apps_finances_tauri_models_protos_fx_quote: GenFile;

/**
 * @generated from message finances_app_models.FxQuote
 */
export declare type FxQuote = Message<"finances_app_models.FxQuote"> & {
  /**
   * The three-letter currency code defined in ISO 4217.
   *
   * @generated from field: string base_ccy_code = 1;
   */
  baseCcyCode: string;

  /**
   * The three-letter currency code defined in ISO 4217.
   *
   * @generated from field: string quote_ccy_code = 2;
   */
  quoteCcyCode: string;

  /**
   * @generated from field: google.type.Decimal quote = 3;
   */
  quote?: Decimal;

  /**
   * @generated from field: google.type.Date date_value = 4;
   */
  dateValue?: Date;
};

/**
 * Describes the message finances_app_models.FxQuote.
 * Use `create(FxQuoteSchema)` to create a new message.
 */
export declare const FxQuoteSchema: GenMessage<FxQuote>;

