// @generated by protoc-gen-es v2.2.3 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/holder.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apps/finances/tauri/models/protos/holder.proto.
 */
export declare const file_apps_finances_tauri_models_protos_holder: GenFile;

/**
 * @generated from message finances_app_models.Holder
 */
export declare type Holder = Message<"finances_app_models.Holder"> & {
  /**
   * @generated from field: int64 pk = 1;
   */
  pk: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: bool is_company = 3;
   */
  isCompany: boolean;

  /**
   * @generated from field: optional string photo = 4;
   */
  photo?: string;
};

/**
 * Describes the message finances_app_models.Holder.
 * Use `create(HolderSchema)` to create a new message.
 */
export declare const HolderSchema: GenMessage<Holder>;

/**
 * @generated from message finances_app_models.HolderList
 */
export declare type HolderList = Message<"finances_app_models.HolderList"> & {
  /**
   * @generated from field: repeated finances_app_models.Holder holders = 1;
   */
  holders: Holder[];
};

/**
 * Describes the message finances_app_models.HolderList.
 * Use `create(HolderListSchema)` to create a new message.
 */
export declare const HolderListSchema: GenMessage<HolderList>;

