// @generated by protoc-gen-es v2.6.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/holder_context.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Holder } from "./holder_pb.js";
import type { Account } from "./account_pb.js";

/**
 * Describes the file apps/finances/tauri/models/protos/holder_context.proto.
 */
export declare const file_apps_finances_tauri_models_protos_holder_context: GenFile;

/**
 * @generated from message finances_app_models.HolderContext
 */
export declare type HolderContext = Message<"finances_app_models.HolderContext"> & {
  /**
   * @generated from field: finances_app_models.Holder holder = 1;
   */
  holder?: Holder;

  /**
   * @generated from field: repeated finances_app_models.Account accounts = 2;
   */
  accounts: Account[];
};

/**
 * Describes the message finances_app_models.HolderContext.
 * Use `create(HolderContextSchema)` to create a new message.
 */
export declare const HolderContextSchema: GenMessage<HolderContext>;

