// @generated by protoc-gen-es v2.2.3 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/main_context.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Holder } from "./holder_pb.js";
import type { AccountType } from "./account_pb.js";

/**
 * Describes the file apps/finances/tauri/models/protos/main_context.proto.
 */
export declare const file_apps_finances_tauri_models_protos_main_context: GenFile;

/**
 * @generated from message finances_app_models.MainContext
 */
export declare type MainContext = Message<"finances_app_models.MainContext"> & {
  /**
   * @generated from field: repeated finances_app_models.Holder holders = 1;
   */
  holders: Holder[];

  /**
   * @generated from field: repeated finances_app_models.AccountType account_types = 2;
   */
  accountTypes: AccountType[];
};

/**
 * Describes the message finances_app_models.MainContext.
 * Use `create(MainContextSchema)` to create a new message.
 */
export declare const MainContextSchema: GenMessage<MainContext>;

