// @generated by protoc-gen-es v2.2.5 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/money_amount.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Money } from "../../../../../libraries/googleapis/protos/google/type/money_pb.js";
import type { Decimal } from "../../../../../libraries/googleapis/protos/google/type/decimal_pb.js";

/**
 * Describes the file apps/finances/tauri/models/protos/money_amount.proto.
 */
export declare const file_apps_finances_tauri_models_protos_money_amount: GenFile;

/**
 * @generated from message finances_app_models.MoneyAmount
 */
export declare type MoneyAmount = Message<"finances_app_models.MoneyAmount"> & {
  /**
   * @generated from oneof finances_app_models.MoneyAmount.amount
   */
  amount: {
    /**
     * @generated from field: finances_app_models.MoneyAmount.NonNumerable non_numerable = 1;
     */
    value: MoneyAmount_NonNumerable;
    case: "nonNumerable";
  } | {
    /**
     * @generated from field: finances_app_models.MoneyAmount.Numerable numerable = 2;
     */
    value: MoneyAmount_Numerable;
    case: "numerable";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message finances_app_models.MoneyAmount.
 * Use `create(MoneyAmountSchema)` to create a new message.
 */
export declare const MoneyAmountSchema: GenMessage<MoneyAmount>;

/**
 * @generated from message finances_app_models.MoneyAmount.NonNumerable
 */
export declare type MoneyAmount_NonNumerable = Message<"finances_app_models.MoneyAmount.NonNumerable"> & {
  /**
   * @generated from field: google.type.Money amount = 1;
   */
  amount?: Money;
};

/**
 * Describes the message finances_app_models.MoneyAmount.NonNumerable.
 * Use `create(MoneyAmount_NonNumerableSchema)` to create a new message.
 */
export declare const MoneyAmount_NonNumerableSchema: GenMessage<MoneyAmount_NonNumerable>;

/**
 * @generated from message finances_app_models.MoneyAmount.Numerable
 */
export declare type MoneyAmount_Numerable = Message<"finances_app_models.MoneyAmount.Numerable"> & {
  /**
   * @generated from field: google.type.Money unit_value = 1;
   */
  unitValue?: Money;

  /**
   * @generated from field: google.type.Decimal quantity = 2;
   */
  quantity?: Decimal;
};

/**
 * Describes the message finances_app_models.MoneyAmount.Numerable.
 * Use `create(MoneyAmount_NumerableSchema)` to create a new message.
 */
export declare const MoneyAmount_NumerableSchema: GenMessage<MoneyAmount_Numerable>;

