syntax = "proto3";
package finances_app_models;

import "libraries/googleapis/protos/google/type/date.proto";
import "apps/finances/tauri/models/protos/money_amount.proto";
import "apps/finances/tauri/models/protos/fx_quote.proto";
import "libraries/googleapis/protos/google/type/money.proto";

message MovementType {
    int64 pk = 1;
    string name = 2;
    // Last element in the breadcrumb is the movement-type itself. This way, if the breadcrumb is empty, it has not been populated.
    repeated string breadcrumb = 3;
}

enum MovementDirection {
    In = 0;
    Out = 1;
}

message MovementAmount {
    message Dividend {
        google.type.Date ex_dividend_date = 1;
        // Payout per share (and quantity from the snapshot)
        MoneyAmount.Numerable payout = 3;
    }

    // This is also used to classify the Movement into Numerable/NonNumerable/Dividend
    oneof amount {
        MoneyAmount.NonNumerable non_numerable = 5;
        MoneyAmount.Numerable numerable = 6;
        Dividend dividend =7;
    }
}

message Movement {
    optional int64 pk = 1;
    google.type.Date date_value = 2;

    // optional - New movements doesn't belong to a transaction yet
    optional int64 transaction_pk = 3;
    MovementType type = 4;
    MovementDirection direction = 5;

    MovementAmount amount = 6;
    FxQuote fx = 7;

    int64 account_pk = 8;
}
