// @generated by protoc-gen-es v2.2.3 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/movement.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { MoneyAmount_NonNumerable, MoneyAmount_Numerable } from "./money_amount_pb.js";
import type { Date } from "../../../../../libraries/googleapis/protos/google/type/date_pb.js";
import type { FxQuote } from "./fx_quote_pb.js";

/**
 * Describes the file apps/finances/tauri/models/protos/movement.proto.
 */
export declare const file_apps_finances_tauri_models_protos_movement: GenFile;

/**
 * @generated from message finances_app_models.MovementType
 */
export declare type MovementType = Message<"finances_app_models.MovementType"> & {
  /**
   * @generated from field: int64 pk = 1;
   */
  pk: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated string breadcrumb = 3;
   */
  breadcrumb: string[];
};

/**
 * Describes the message finances_app_models.MovementType.
 * Use `create(MovementTypeSchema)` to create a new message.
 */
export declare const MovementTypeSchema: GenMessage<MovementType>;

/**
 * @generated from message finances_app_models.MovementAmount
 */
export declare type MovementAmount = Message<"finances_app_models.MovementAmount"> & {
  /**
   * @generated from oneof finances_app_models.MovementAmount.amount
   */
  amount: {
    /**
     * @generated from field: finances_app_models.MoneyAmount.NonNumerable non_numerable = 5;
     */
    value: MoneyAmount_NonNumerable;
    case: "nonNumerable";
  } | {
    /**
     * @generated from field: finances_app_models.MoneyAmount.Numerable numerable = 6;
     */
    value: MoneyAmount_Numerable;
    case: "numerable";
  } | {
    /**
     * @generated from field: finances_app_models.MovementAmount.Dividend dividend = 7;
     */
    value: MovementAmount_Dividend;
    case: "dividend";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message finances_app_models.MovementAmount.
 * Use `create(MovementAmountSchema)` to create a new message.
 */
export declare const MovementAmountSchema: GenMessage<MovementAmount>;

/**
 * @generated from message finances_app_models.MovementAmount.Dividend
 */
export declare type MovementAmount_Dividend = Message<"finances_app_models.MovementAmount.Dividend"> & {
  /**
   * @generated from field: google.type.Date ex_dividend_date = 1;
   */
  exDividendDate?: Date;

  /**
   * @generated from field: finances_app_models.MoneyAmount.Numerable payout = 3;
   */
  payout?: MoneyAmount_Numerable;
};

/**
 * Describes the message finances_app_models.MovementAmount.Dividend.
 * Use `create(MovementAmount_DividendSchema)` to create a new message.
 */
export declare const MovementAmount_DividendSchema: GenMessage<MovementAmount_Dividend>;

/**
 * @generated from message finances_app_models.Movement
 */
export declare type Movement = Message<"finances_app_models.Movement"> & {
  /**
   * @generated from field: optional int64 pk = 1;
   */
  pk?: bigint;

  /**
   * @generated from field: google.type.Date date_value = 2;
   */
  dateValue?: Date;

  /**
   * @generated from field: optional int64 transaction_pk = 3;
   */
  transactionPk?: bigint;

  /**
   * @generated from field: optional string transaction_name = 9;
   */
  transactionName?: string;

  /**
   * @generated from field: finances_app_models.MovementType type = 4;
   */
  type?: MovementType;

  /**
   * @generated from field: finances_app_models.MovementDirection direction = 5;
   */
  direction: MovementDirection;

  /**
   * @generated from field: finances_app_models.MovementAmount amount = 6;
   */
  amount?: MovementAmount;

  /**
   * @generated from field: finances_app_models.FxQuote fx = 7;
   */
  fx?: FxQuote;

  /**
   * @generated from field: int64 account_pk = 8;
   */
  accountPk: bigint;
};

/**
 * Describes the message finances_app_models.Movement.
 * Use `create(MovementSchema)` to create a new message.
 */
export declare const MovementSchema: GenMessage<Movement>;

/**
 * @generated from enum finances_app_models.MovementDirection
 */
export enum MovementDirection {
  /**
   * @generated from enum value: In = 0;
   */
  In = 0,

  /**
   * @generated from enum value: Out = 1;
   */
  Out = 1,
}

/**
 * Describes the enum finances_app_models.MovementDirection.
 */
export declare const MovementDirectionSchema: GenEnum<MovementDirection>;

