// @generated by protoc-gen-es v2.6.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/snapshot.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Date } from "../../../../../libraries/googleapis/protos/google/type/date_pb.js";
import type { MoneyAmount } from "./money_amount_pb.js";

/**
 * Describes the file apps/finances/tauri/models/protos/snapshot.proto.
 */
export declare const file_apps_finances_tauri_models_protos_snapshot: GenFile;

/**
 * @generated from message finances_app_models.Snapshot
 */
export declare type Snapshot = Message<"finances_app_models.Snapshot"> & {
  /**
   * @generated from field: optional int64 pk = 1;
   */
  pk?: bigint;

  /**
   * @generated from field: google.type.Date date_value = 2;
   */
  dateValue?: Date;

  /**
   * @generated from field: finances_app_models.MoneyAmount amount = 3;
   */
  amount?: MoneyAmount;

  /**
   * @generated from field: int64 account_pk = 4;
   */
  accountPk: bigint;
};

/**
 * Describes the message finances_app_models.Snapshot.
 * Use `create(SnapshotSchema)` to create a new message.
 */
export declare const SnapshotSchema: GenMessage<Snapshot>;

/**
 * @generated from message finances_app_models.SnapshotsRequest
 */
export declare type SnapshotsRequest = Message<"finances_app_models.SnapshotsRequest"> & {
  /**
   * @generated from field: int64 account_pk = 1;
   */
  accountPk: bigint;

  /**
   * @generated from field: optional google.type.Date start_date = 2;
   */
  startDate?: Date;

  /**
   * @generated from field: optional google.type.Date end_date = 3;
   */
  endDate?: Date;
};

/**
 * Describes the message finances_app_models.SnapshotsRequest.
 * Use `create(SnapshotsRequestSchema)` to create a new message.
 */
export declare const SnapshotsRequestSchema: GenMessage<SnapshotsRequest>;

/**
 * @generated from message finances_app_models.SnapshotsResponse
 */
export declare type SnapshotsResponse = Message<"finances_app_models.SnapshotsResponse"> & {
  /**
   * @generated from field: int64 account_pk = 1;
   */
  accountPk: bigint;

  /**
   * @generated from field: repeated finances_app_models.Snapshot snapshots = 2;
   */
  snapshots: Snapshot[];

  /**
   * @generated from field: optional google.type.Date start_date = 3;
   */
  startDate?: Date;

  /**
   * @generated from field: optional google.type.Date end_date = 4;
   */
  endDate?: Date;
};

/**
 * Describes the message finances_app_models.SnapshotsResponse.
 * Use `create(SnapshotsResponseSchema)` to create a new message.
 */
export declare const SnapshotsResponseSchema: GenMessage<SnapshotsResponse>;

