// @generated by protoc-gen-es v2.2.4 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/snapshot.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Date } from "../../../../../libraries/googleapis/protos/google/type/date_pb.js";
import type { MoneyAmount } from "./money_amount_pb.js";

/**
 * Describes the file apps/finances/tauri/models/protos/snapshot.proto.
 */
export declare const file_apps_finances_tauri_models_protos_snapshot: GenFile;

/**
 * @generated from message finances_app_models.Snapshot
 */
export declare type Snapshot = Message<"finances_app_models.Snapshot"> & {
  /**
   * @generated from field: optional int64 pk = 1;
   */
  pk?: bigint;

  /**
   * @generated from field: google.type.Date date_value = 2;
   */
  dateValue?: Date;

  /**
   * @generated from field: finances_app_models.MoneyAmount amount = 3;
   */
  amount?: MoneyAmount;

  /**
   * @generated from field: int64 account_pk = 4;
   */
  accountPk: bigint;
};

/**
 * Describes the message finances_app_models.Snapshot.
 * Use `create(SnapshotSchema)` to create a new message.
 */
export declare const SnapshotSchema: GenMessage<Snapshot>;

