// @generated by protoc-gen-es v2.2.3 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/transaction.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apps/finances/tauri/models/protos/transaction.proto.
 */
export declare const file_apps_finances_tauri_models_protos_transaction: GenFile;

/**
 * @generated from message finances_app_models.TransactionGroup
 */
export declare type TransactionGroup = Message<"finances_app_models.TransactionGroup"> & {
  /**
   * @generated from field: int64 pk = 1;
   */
  pk: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;
};

/**
 * Describes the message finances_app_models.TransactionGroup.
 * Use `create(TransactionGroupSchema)` to create a new message.
 */
export declare const TransactionGroupSchema: GenMessage<TransactionGroup>;

