syntax = "proto3";
package finances_app_models;

import "apps/finances/tauri/models/protos/movement.proto";

message TransactionGroup {
    int64 pk = 1;
    string name = 2;
    optional string description = 3;
}

// Details for a given transaction
message Transaction {
    int64 pk = 1;
    string name = 2;
    optional string description = 3;

    TransactionGroup group = 4;

    repeated Movement movements_from = 5;
    repeated Movement movements_to = 6;
}


// FIXME: Are we using this one?
message NewTransaction {
    string name = 1;
    optional string description = 2;
    optional int64 transaction_group_pk = 3;

    repeated NewMovement movements_from = 4;
    repeated NewMovement movements_to = 5;

}


message LastTransactionsRequest {
    int64 account_pk = 1;
    MovementDirection account_movement_direction = 2;
    optional int32 n_transactions = 3;
}

message LastTransactionsResponse {
    repeated Transaction transactions = 1;
}
