// @generated by protoc-gen-es v2.2.3 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/finances/tauri/models/protos/transaction.proto (package finances_app_models, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { NewMovement } from "./movement_pb.js";

/**
 * Describes the file apps/finances/tauri/models/protos/transaction.proto.
 */
export declare const file_apps_finances_tauri_models_protos_transaction: GenFile;

/**
 * @generated from message finances_app_models.TransactionGroup
 */
export declare type TransactionGroup = Message<"finances_app_models.TransactionGroup"> & {
  /**
   * @generated from field: int64 pk = 1;
   */
  pk: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;
};

/**
 * Describes the message finances_app_models.TransactionGroup.
 * Use `create(TransactionGroupSchema)` to create a new message.
 */
export declare const TransactionGroupSchema: GenMessage<TransactionGroup>;

/**
 * @generated from message finances_app_models.NewTransaction
 */
export declare type NewTransaction = Message<"finances_app_models.NewTransaction"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: optional string description = 2;
   */
  description?: string;

  /**
   * @generated from field: optional int64 transaction_group_pk = 3;
   */
  transactionGroupPk?: bigint;

  /**
   * @generated from field: repeated finances_app_models.NewMovement movements_from = 4;
   */
  movementsFrom: NewMovement[];

  /**
   * @generated from field: repeated finances_app_models.NewMovement movements_to = 5;
   */
  movementsTo: NewMovement[];
};

/**
 * Describes the message finances_app_models.NewTransaction.
 * Use `create(NewTransactionSchema)` to create a new message.
 */
export declare const NewTransactionSchema: GenMessage<NewTransaction>;

