load("@aspect_bazel_lib//lib:transitions.bzl", "platform_transition_filegroup")
load("@aspect_rules_py//py:defs.bzl", "py_binary")
load("@py_deps//:requirements.bzl", "requirement")
load("@rules_oci//oci:defs.bzl", "oci_load")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")
load("//bazel/containers:py_layer.bzl", "py_oci_image")

APPS = [
    "//libraries/finances/accounts/django_finances_accounts:finances_accounts",
    "//libraries/finances/investments/django_finances_investments:finances_investments",
]

# Use this target to execute commands on this project:
#
# ```
# bazel run //apps/finances/django:admin -- --help
# ```
py_binary(
    name = "admin",
    srcs = glob(["**/*.py"]),
    env = {
        "DATABASE_SQLITE3": "/Users/jgsogo/personal/totum-revolutum/finances.sqlite3",
    },
    imports = ["."],
    main = "manage.py",
    deps = APPS + [
        requirement("django"),
        requirement("PyYAML"),
        requirement("psycopg"),
    ],
)

filegroup(
    name = "docker-compose-yaml",
    srcs = [":docker-compose.yaml"],
    visibility = [":__subpackages__"],
)

filegroup(
    name = "env-dev",
    srcs = [":.env.dev"],
    visibility = [":__subpackages__"],
)

filegroup(
    name = "_entrypoint",
    srcs = [":entrypoint.sh"],
    visibility = [":__subpackages__"],
)

pkg_tar(
    name = "entrypoint",
    srcs = ["entrypoint.sh"],
)

py_oci_image(
    name = "_container",
    base = "//containers/django-app",
    binary = ":admin",
    entrypoint = ["/entrypoint.sh"],
    exposed_ports = ["8080"],
    tags = [
        "manual",
    ],
    tars = [
        ":entrypoint",
    ],
)

platform_transition_filegroup(
    name = "container",
    srcs = [":_container"],
    tags = [
        "manual",
    ],
    target_platform = select({
        "@platforms//cpu:arm64": "//bazel/platforms:linux_x86_64",
        "@platforms//cpu:x86_64": "//bazel/platforms:linux_x86_64",
    }),
    # visibility = ["//visibility:public"],
    # visibility = [":__subpackages__"],
)

# TODO: Some around this rule to test the container
# container_structure_test(
#     name = "structure_test",
#     configs = ["test.yaml"],
#     image = ":container",
#     tags = [
#         "ci",
#         "manual",
#     ],
# )

oci_load(
    name = "load",
    image = ":container",
    repo_tags = ["django_finances:latest"],
    tags = [
        "manual",
    ],
)

# We need this rule so 'oci_load' actually creates the tarball,
# see https://github.com/bazel-contrib/rules_oci/blob/main/docs/load.md#build-outputs
# for more info
filegroup(
    name = "tarball",
    srcs = [":load"],
    output_group = "tarball",
    visibility = [":__subpackages__"],
)
