load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_library")
load("@py_deps//:requirements.bzl", "requirement")
load("//bazel/python/gunicorn:defs.bzl", "gunicorn_binary")

APPS = [
    "//libraries/finances/accounts/django_finances_accounts:finances_accounts",
    "//libraries/finances/investments/django_finances_investments:finances_investments",
]

# The library, with all the application files
py_library(
    name = "applib",
    srcs = glob(["finances/**/*.py"]),
    imports = ["."],
    deps = APPS + [
        requirement("django"),
        requirement("PyYAML"),
        requirement("psycopg"),  # FIXME: This is required because some of the deployments are using Postgres
    ],
)

# The application django-admin
py_binary(
    name = "admin",
    srcs = ["manage.py"],
    env = {
        "SQL_DATABASE": "/Users/jgsogo/personal/totum-revolutum/finances.sqlite3",
        "DJANGO_ALLOWED_HOSTS": "localhost 127.0.0.1 0.0.0.0 [::1]",
        "DEBUG": "1",
        "SECRET_KEY": "buu",
    },
    main = "manage.py",
    deps = [
        ":applib",
        # requirement("gunicorn"),  # FIXME: Required for the deployments
    ],
)

gunicorn_binary(
    name = "gunicorn",
    args = [
        "finances.wsgi:application",
        "--bind 0.0.0.0:8000",
        "--access-logfile '-'",
    ],
    env = {
        "SQL_DATABASE": "/Users/jgsogo/personal/totum-revolutum/finances.sqlite3",
        "DJANGO_ALLOWED_HOSTS": "localhost 127.0.0.1 0.0.0.0 [::1]",
        "DEBUG": "1",
        "SECRET_KEY": "buu",
    },
    deps = [
        ":applib",
    ],
)

# py_oci_image(
#     name = "container",
#     base = "//containers/django/app",
#     binaries = [
#         ":gunicorn",
#         ":admin",
#     ],
#     entrypoint = ["/entrypoint.sh"],
#     exposed_ports = ["8080"],
#     tags = [
#         "manual",
#     ],
#     tars = [
#         ":entrypoint",
#     ],
#     user = "app:app",
# )
