load("@crates_libraries//:defs.bzl", "aliases", "all_crate_deps")
load("@totum_revolutum//bazel/rust:defs.bzl", "rust_library_tests_and_docs")

rust_library_tests_and_docs(
    name = "filesystem_pcloud",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    deps = all_crate_deps(
        normal = True,
    ) + [
        "@totum_revolutum//libraries/filesystem",
        "@totum_revolutum//libraries/pcloud_sdk",
    ],
)

# rust_binary(
#     name = "cli",
#     srcs = glob(["src/cli/**/*.rs"]),
#     crate_features = [
#         "cli",
#         "indicatif",
#     ],
#     proc_macro_deps = all_crate_deps(
#         proc_macro = True,
#     ),
#     deps = all_crate_deps(
#         normal = True,
#     ) + [
#         ":pcloud_sdk/cli",
#         "@crates_libraries//:indicatif",
#     ],
# )
