[package]
name = "filesystem_pcloud"
version = "0.1.0"
edition = "2021"

[features]


[dependencies]
filesystem = { path = "../filesystem" }
pcloud_sdk = { path = "../pcloud_sdk" }

anyhow = { workspace = true }
async-trait = { workspace = true }
camino = { workspace = true }
flume = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

[dev-dependencies]
#filesystem = { path = ".", features = ["test_utils"] }
pcloud_sdk = { path = "../pcloud_sdk", features = ["test_utils"] }


[[example]]
name = "copy_file"
