[package]
name = "filesystem_pcloud"
version = "0.1.0"
edition = "2021"

[features]


[dependencies]
filesystem = { path = "../filesystem" }
http_utils = { path = "../http_utils" }
pcloud_sdk = { path = "../pcloud_sdk" }

async-trait = { workspace = true }
camino = { workspace = true }
flume = { workspace = true }
headers = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

[dev-dependencies]
pcloud_sdk = { path = "../pcloud_sdk", features = ["test_utils"] }
anyhow = { workspace = true }


[[example]]
name = "copy_file"
