// @generated by protoc-gen-es v2.11.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/tic_tac_toe/models/actions.proto (package board_games.tic_tac_toe, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Player } from "./board_pb.js";

/**
 * Describes the file apps/board_games/games/tic_tac_toe/models/actions.proto.
 */
export declare const file_apps_board_games_games_tic_tac_toe_models_actions: GenFile;

/**
 * @generated from message board_games.tic_tac_toe.ActionPlaceMark
 */
export declare type ActionPlaceMark = Message<"board_games.tic_tac_toe.ActionPlaceMark"> & {
  /**
   * Position 0–8, mapped left-to-right, top-to-bottom.
   *
   * @generated from field: uint32 position = 1;
   */
  position: number;
};

/**
 * Describes the message board_games.tic_tac_toe.ActionPlaceMark.
 * Use `create(ActionPlaceMarkSchema)` to create a new message.
 */
export declare const ActionPlaceMarkSchema: GenMessage<ActionPlaceMark>;

/**
 * @generated from message board_games.tic_tac_toe.ActionJoinGame
 */
export declare type ActionJoinGame = Message<"board_games.tic_tac_toe.ActionJoinGame"> & {
  /**
   * @generated from field: board_games.tic_tac_toe.Player player = 1;
   */
  player: Player;
};

/**
 * Describes the message board_games.tic_tac_toe.ActionJoinGame.
 * Use `create(ActionJoinGameSchema)` to create a new message.
 */
export declare const ActionJoinGameSchema: GenMessage<ActionJoinGame>;

/**
 * @generated from message board_games.tic_tac_toe.Action
 */
export declare type Action = Message<"board_games.tic_tac_toe.Action"> & {
  /**
   * @generated from oneof board_games.tic_tac_toe.Action.action
   */
  action: {
    /**
     * @generated from field: board_games.tic_tac_toe.ActionPlaceMark place_mark = 1;
     */
    value: ActionPlaceMark;
    case: "placeMark";
  } | {
    /**
     * @generated from field: board_games.tic_tac_toe.ActionJoinGame join_game = 2;
     */
    value: ActionJoinGame;
    case: "joinGame";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message board_games.tic_tac_toe.Action.
 * Use `create(ActionSchema)` to create a new message.
 */
export declare const ActionSchema: GenMessage<Action>;

