// @generated by protoc-gen-es v2.10.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/tic_tac_toe/models/board.proto (package board_games.tic_tac_toe, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apps/board_games/games/tic_tac_toe/models/board.proto.
 */
export declare const file_apps_board_games_games_tic_tac_toe_models_board: GenFile;

/**
 * @generated from message board_games.tic_tac_toe.Board
 */
export declare type Board = Message<"board_games.tic_tac_toe.Board"> & {
  /**
   * Linearized 3x3 board. Values: 'X', 'O', or ' ' (empty).
   *
   * @generated from field: repeated board_games.tic_tac_toe.Player board_status = 1;
   */
  boardStatus: Player[];

  /**
   * FIXME: Every game will have this?
   *
   * @generated from oneof board_games.tic_tac_toe.Board.turn_state
   */
  turnState: {
    /**
     * @generated from field: board_games.tic_tac_toe.Player current_turn = 2;
     */
    value: Player;
    case: "currentTurn";
  } | {
    /**
     * If there is a winner, the game has finished
     *
     * @generated from field: board_games.tic_tac_toe.Winner winner = 3;
     */
    value: Winner;
    case: "winner";
  } | {
    /**
     * @generated from field: bool draw = 4;
     */
    value: boolean;
    case: "draw";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message board_games.tic_tac_toe.Board.
 * Use `create(BoardSchema)` to create a new message.
 */
export declare const BoardSchema: GenMessage<Board>;

/**
 * @generated from message board_games.tic_tac_toe.Winner
 */
export declare type Winner = Message<"board_games.tic_tac_toe.Winner"> & {
  /**
   * @generated from field: board_games.tic_tac_toe.Player player = 1;
   */
  player: Player;

  /**
   * @generated from field: repeated uint32 line = 2;
   */
  line: number[];
};

/**
 * Describes the message board_games.tic_tac_toe.Winner.
 * Use `create(WinnerSchema)` to create a new message.
 */
export declare const WinnerSchema: GenMessage<Winner>;

/**
 * @generated from enum board_games.tic_tac_toe.Player
 */
export enum Player {
  /**
   * @generated from enum value: PLAYER_X = 0;
   */
  PLAYER_X = 0,

  /**
   * @generated from enum value: PLAYER_O = 1;
   */
  PLAYER_O = 1,

  /**
   * @generated from enum value: NONE = 2;
   */
  NONE = 2,
}

/**
 * Describes the enum board_games.tic_tac_toe.Player.
 */
export declare const PlayerSchema: GenEnum<Player>;

