syntax = "proto3";
package board_games.tic_tac_toe;

enum Player {
  PLAYER_X = 0;
  PLAYER_O = 1;
  NONE = 2;
}

message Board {
    // Linearized 3x3 board. Values: 'X', 'O', or ' ' (empty).
    repeated Player board_status = 1;

    map<uint32, Player> players = 2;

    oneof turn_state { // FIXME: Every game will have this?
        Player current_turn = 3;

        // If there is a winner, the game has finished
        Winner winner = 4;

        bool draw = 5;
    }
}

message Winner {
    Player player = 1;
    repeated uint32 line = 2;
}
