// @generated by protoc-gen-es v2.6.3 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/tic_tac_toe/models/board.proto (package board_game.tic_tac_toe, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apps/board_games/games/tic_tac_toe/models/board.proto.
 */
export declare const file_apps_board_games_games_tic_tac_toe_models_board: GenFile;

/**
 * @generated from message board_game.tic_tac_toe.Board
 */
export declare type Board = Message<"board_game.tic_tac_toe.Board"> & {
  /**
   * Linearized 3x3 board. Values: 'X', 'O', or ' ' (empty).
   *
   * @generated from field: string board_status = 1;
   */
  boardStatus: string;

  /**
   * FIXME: Every game will have this?
   *
   * @generated from oneof board_game.tic_tac_toe.Board.test_oneof
   */
  testOneof: {
    /**
     * @generated from field: uint32 current_turn = 2;
     */
    value: number;
    case: "currentTurn";
  } | {
    /**
     * If there is a winner, the game has finished
     *
     * @generated from field: uint32 winner = 3;
     */
    value: number;
    case: "winner";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message board_game.tic_tac_toe.Board.
 * Use `create(BoardSchema)` to create a new message.
 */
export declare const BoardSchema: GenMessage<Board>;

