// @generated by protoc-gen-es v2.10.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/tic_tac_toe/models/events.proto (package board_games.tic_tac_toe, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Player } from "./board_pb.js";

/**
 * Describes the file apps/board_games/games/tic_tac_toe/models/events.proto.
 */
export declare const file_apps_board_games_games_tic_tac_toe_models_events: GenFile;

/**
 * @generated from message board_games.tic_tac_toe.EventMarkPlaced
 */
export declare type EventMarkPlaced = Message<"board_games.tic_tac_toe.EventMarkPlaced"> & {
  /**
   * @generated from field: uint32 position = 1;
   */
  position: number;

  /**
   * @generated from field: board_games.tic_tac_toe.Player mark = 2;
   */
  mark: Player;
};

/**
 * Describes the message board_games.tic_tac_toe.EventMarkPlaced.
 * Use `create(EventMarkPlacedSchema)` to create a new message.
 */
export declare const EventMarkPlacedSchema: GenMessage<EventMarkPlaced>;

/**
 * @generated from message board_games.tic_tac_toe.EventGameFinishedWinner
 */
export declare type EventGameFinishedWinner = Message<"board_games.tic_tac_toe.EventGameFinishedWinner"> & {
  /**
   * @generated from field: board_games.tic_tac_toe.Player player = 1;
   */
  player: Player;

  /**
   * @generated from field: repeated uint32 line = 2;
   */
  line: number[];
};

/**
 * Describes the message board_games.tic_tac_toe.EventGameFinishedWinner.
 * Use `create(EventGameFinishedWinnerSchema)` to create a new message.
 */
export declare const EventGameFinishedWinnerSchema: GenMessage<EventGameFinishedWinner>;

/**
 * @generated from message board_games.tic_tac_toe.EventGameFinishedDraw
 */
export declare type EventGameFinishedDraw = Message<"board_games.tic_tac_toe.EventGameFinishedDraw"> & {
};

/**
 * Describes the message board_games.tic_tac_toe.EventGameFinishedDraw.
 * Use `create(EventGameFinishedDrawSchema)` to create a new message.
 */
export declare const EventGameFinishedDrawSchema: GenMessage<EventGameFinishedDraw>;

/**
 * @generated from message board_games.tic_tac_toe.EventNextTurn
 */
export declare type EventNextTurn = Message<"board_games.tic_tac_toe.EventNextTurn"> & {
  /**
   * @generated from field: board_games.tic_tac_toe.Player next_player = 1;
   */
  nextPlayer: Player;
};

/**
 * Describes the message board_games.tic_tac_toe.EventNextTurn.
 * Use `create(EventNextTurnSchema)` to create a new message.
 */
export declare const EventNextTurnSchema: GenMessage<EventNextTurn>;

/**
 * @generated from message board_games.tic_tac_toe.EventNewPlayer
 */
export declare type EventNewPlayer = Message<"board_games.tic_tac_toe.EventNewPlayer"> & {
  /**
   * @generated from field: uint32 player_number = 1;
   */
  playerNumber: number;

  /**
   * @generated from field: board_games.tic_tac_toe.Player player = 2;
   */
  player: Player;
};

/**
 * Describes the message board_games.tic_tac_toe.EventNewPlayer.
 * Use `create(EventNewPlayerSchema)` to create a new message.
 */
export declare const EventNewPlayerSchema: GenMessage<EventNewPlayer>;

/**
 * @generated from message board_games.tic_tac_toe.Event
 */
export declare type Event = Message<"board_games.tic_tac_toe.Event"> & {
  /**
   * @generated from oneof board_games.tic_tac_toe.Event.event
   */
  event: {
    /**
     * @generated from field: board_games.tic_tac_toe.EventMarkPlaced mark_placed = 1;
     */
    value: EventMarkPlaced;
    case: "markPlaced";
  } | {
    /**
     * @generated from field: board_games.tic_tac_toe.EventGameFinishedWinner game_finished_winner = 2;
     */
    value: EventGameFinishedWinner;
    case: "gameFinishedWinner";
  } | {
    /**
     * @generated from field: board_games.tic_tac_toe.EventGameFinishedDraw game_finished_draw = 3;
     */
    value: EventGameFinishedDraw;
    case: "gameFinishedDraw";
  } | {
    /**
     * @generated from field: board_games.tic_tac_toe.EventNextTurn next_turn = 4;
     */
    value: EventNextTurn;
    case: "nextTurn";
  } | {
    /**
     * @generated from field: board_games.tic_tac_toe.EventNewPlayer new_player = 5;
     */
    value: EventNewPlayer;
    case: "newPlayer";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message board_games.tic_tac_toe.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export declare const EventSchema: GenMessage<Event>;

