syntax = "proto3";
package board_games.tic_tac_toe;

import "apps/board_games/games/tic_tac_toe/models/board.proto";

message EventMarkPlaced {
    uint32 position = 1;
    Player mark = 2;
}

message EventGameFinishedWinner {
    Player player = 1;
    repeated uint32 line = 2;
}

message EventGameFinishedDraw {
}

message EventNextTurn {
    Player next_player = 1;
}

message EventNewPlayer {
    uint32 player_number = 1;
    Player player = 2;
}

message Event {
    oneof event {
        EventMarkPlaced mark_placed = 1;
        EventGameFinishedWinner game_finished_winner = 2;
        EventGameFinishedDraw game_finished_draw = 3;
        EventNextTurn next_turn = 4;
        EventNewPlayer new_player = 5;
    }
}
