// @generated by protoc-gen-es v2.10.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/tic_tac_toe/models/events.proto (package board_games.tic_tac_toe, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apps/board_games/games/tic_tac_toe/models/events.proto.
 */
export declare const file_apps_board_games_games_tic_tac_toe_models_events: GenFile;

/**
 * @generated from message board_games.tic_tac_toe.EventMarkPlaced
 */
export declare type EventMarkPlaced = Message<"board_games.tic_tac_toe.EventMarkPlaced"> & {
  /**
   * @generated from field: uint32 mark_placed_at_position = 1;
   */
  markPlacedAtPosition: number;
};

/**
 * Describes the message board_games.tic_tac_toe.EventMarkPlaced.
 * Use `create(EventMarkPlacedSchema)` to create a new message.
 */
export declare const EventMarkPlacedSchema: GenMessage<EventMarkPlaced>;

/**
 * @generated from message board_games.tic_tac_toe.EventGameFinishedWinner
 */
export declare type EventGameFinishedWinner = Message<"board_games.tic_tac_toe.EventGameFinishedWinner"> & {
  /**
   * @generated from field: uint32 player = 1;
   */
  player: number;

  /**
   * @generated from field: repeated uint32 line = 2;
   */
  line: number[];
};

/**
 * Describes the message board_games.tic_tac_toe.EventGameFinishedWinner.
 * Use `create(EventGameFinishedWinnerSchema)` to create a new message.
 */
export declare const EventGameFinishedWinnerSchema: GenMessage<EventGameFinishedWinner>;

/**
 * @generated from message board_games.tic_tac_toe.EventGameFinishedDraw
 */
export declare type EventGameFinishedDraw = Message<"board_games.tic_tac_toe.EventGameFinishedDraw"> & {
};

/**
 * Describes the message board_games.tic_tac_toe.EventGameFinishedDraw.
 * Use `create(EventGameFinishedDrawSchema)` to create a new message.
 */
export declare const EventGameFinishedDrawSchema: GenMessage<EventGameFinishedDraw>;

/**
 * @generated from message board_games.tic_tac_toe.Event
 */
export declare type Event = Message<"board_games.tic_tac_toe.Event"> & {
  /**
   * @generated from oneof board_games.tic_tac_toe.Event.event
   */
  event: {
    /**
     * @generated from field: board_games.tic_tac_toe.EventMarkPlaced mark_placed = 1;
     */
    value: EventMarkPlaced;
    case: "markPlaced";
  } | {
    /**
     * @generated from field: board_games.tic_tac_toe.EventGameFinishedWinner winner = 2;
     */
    value: EventGameFinishedWinner;
    case: "winner";
  } | {
    /**
     * @generated from field: board_games.tic_tac_toe.EventGameFinishedDraw draw = 3;
     */
    value: EventGameFinishedDraw;
    case: "draw";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message board_games.tic_tac_toe.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export declare const EventSchema: GenMessage<Event>;

