[package]
name = "tauri-hello-world"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tauri_hello_world_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
# tauri-build = { workspace = true, features = [] }
tauri-build = { version = "2.0.0-rc", features = [] }

[dependencies]
# tauri-build = { workspace = true }
# tauri = { workspace = true }
# tauri-plugin-shell = { workspace = true }
# serde = {  workspace = true, features = ["derive"] }
# serde_json = { workspace = true }
tauri-build = { version = "2.0.0-rc", features = [] }
tauri = { version = "2.0.0-rc", features = [] }
tauri-plugin-shell = "2.0.0-rc"
serde = { version = "1.0.200" }
serde_json = "1.0.121"
