load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
load("//bazel:sh_with_runfiles_binary.bzl", "sh_with_runfiles_binary")
load("//bazel/containers/postgres:with_postgres_run.bzl", "with_postgres_run", "with_postgres_test")

exports_files(["Cargo.toml"])

rust_library(
    name = "finances_investments",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["postgres"],
    visibility = [
        "//apps/finances:__subpackages__",
        "//libraries:__pkg__",
    ],
    deps = [
        "//bazel/third_party/crates:chrono",
        "//bazel/third_party/crates:diesel",
        "//libraries/finances/accounts/rust:finances_accounts",
    ],
)

rust_library(
    name = "finances_investments/test_utils",
    srcs = glob(["src/**/*.rs"]),
    crate_features = [
        "postgres",
        "test_utils",
    ],
    crate_name = "finances_investments",
    visibility = [
        "//apps/finances:__subpackages__",
        "//libraries:__pkg__",
    ],
    deps = [
        "//bazel/third_party/crates:chrono",
        "//bazel/third_party/crates:diesel",
        "//libraries/finances/accounts/rust:finances_accounts/test_utils",
    ],
)

# Unittests... marked as 'manual' because they require Postgres
rust_test(
    name = "_tests",
    crate = ":finances_investments/test_utils",
    crate_features = [
        "postgres",
        "test_utils",
    ],
    tags = ["manual"],
    deps = [
        "//bazel/third_party/crates:bigdecimal",
        "//bazel/third_party/crates:lazy_static",
        "@libpqxx//:libpq",
    ],
)

with_postgres_test(
    name = "tests-postgres",
    # First migrate,then run the tests
    binaries = [
        "//libraries/finances/investments/django_finances_investments:migrate",
        "//libraries/finances/accounts/django_finances_accounts:populate_test_database",
        "//libraries/finances/investments/django_finances_investments:populate_test_database",
        ":_tests",
    ],
    env = {
        "DJANGO_SQL_ENGINE": "django.db.backends.postgresql",
    },
    env_transpose = {
        "DJANGO_SQL_DATABASE": "POSTGRES_DB",
        "DJANGO_SQL_USER": "POSTGRES_USER",
        "DJANGO_SQL_PASSWORD": "POSTGRES_PASSWORD",
        "DJANGO_SQL_HOST": "POSTGRES_HOST",
        "DJANGO_SQL_PORT": "POSTGRES_PORT",
    },
)

###
# Scripts executed at build time. These generate source files
###

# Generate schema files
sh_with_runfiles_binary(
    name = "diesel_print_schema",
    args = [
        "print-schema",
        "--only-tables",
        "finances_investments",
        "--database-url",
        "$$POSTGRES_URL",
        "> $$BUILD_WORKSPACE_DIRECTORY/" + package_name() + "/src/schema/schema_postgres.rs",
    ],
    tool = "@diesel_cli",
)

# Generate constants.rs file
sh_with_runfiles_binary(
    name = "gen_constants_bin",
    args = [
        "--output-file",
        "$$BUILD_WORKSPACE_DIRECTORY/" + package_name() + "/src/constants.rs",
        "--database-url",
        "$$POSTGRES_URL",
    ],
    tool = "//libraries/finances/accounts/rust:gen_constants",
)

with_postgres_run(
    name = "codegen",
    # First migrate,then print the schema
    binaries = [
        "//libraries/finances/investments/django_finances_investments:migrate",
        ":diesel_print_schema",
        ":gen_constants_bin",
    ],
    env = {
        "DJANGO_SQL_ENGINE": "django.db.backends.postgresql",
    },
    env_transpose = {
        "DJANGO_SQL_DATABASE": "POSTGRES_DB",
        "DJANGO_SQL_USER": "POSTGRES_USER",
        "DJANGO_SQL_PASSWORD": "POSTGRES_PASSWORD",
        "DJANGO_SQL_HOST": "POSTGRES_HOST",
        "DJANGO_SQL_PORT": "POSTGRES_PORT",
    },
    tags = [
        "manual",
        "update",
    ],
)
