# Generated by Django 5.2 on 2025-07-21 12:29

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the game instance.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the game instance was created."
                    ),
                ),
                (
                    "current_state",
                    models.BinaryField(
                        blank=True,
                        help_text="Optional serialized game state (protobuf, binary).",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the game type (e.g., checkers, chess).",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the game (e.g., Checkers).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the game rules or objectives.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the room.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Public name of the room, visible to users.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the room was created."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        help_text="Auto-incrementing ID for ordering events.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the event occurred (according to engine or server).",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type or name of the event (e.g., 'move_made', 'game_over').",
                        max_length=64,
                    ),
                ),
                (
                    "payload",
                    models.BinaryField(
                        help_text="Serialized payload of the event (e.g., protobuf)."
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game in which this event occurred.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_logs",
                        to="board_games_core.game",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="game_type",
            field=models.ForeignKey(
                help_text="Type of game being played in this session.",
                on_delete=django.db.models.deletion.PROTECT,
                to="board_games_core.gametype",
            ),
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the participant.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Role of the participant (e.g., 'player', 'spectator', 'referee').",
                        max_length=32,
                    ),
                ),
                (
                    "join_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the participant joined the game.",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game this participant is involved in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="board_games_core.game",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="room",
            field=models.OneToOneField(
                help_text="Room where this game is being played.",
                on_delete=django.db.models.deletion.CASCADE,
                to="board_games_core.room",
            ),
        ),
    ]
