# Generated by Django 5.2 on 2025-12-12 14:44

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When the action was taken."
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        help_text="Type or name of the action (e.g., 'movement').", max_length=64
                    ),
                ),
                (
                    "payload",
                    models.BinaryField(
                        help_text="Raw binary data of the action, typically a serialized protobuf."
                    ),
                ),
                ("rejected", models.BooleanField(help_text="If the action was rejected or not")),
            ],
            options={
                "ordering": ["game", "timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the game was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the game was last updated (e.g. a move was made).",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("playing", "Playing"),
                            ("finished", "Finished"),
                        ],
                        default="waiting",
                        help_text="State of the game: waiting, playing, or finished.",
                        max_length=10,
                    ),
                ),
                (
                    "payload",
                    models.BinaryField(
                        help_text="Raw binary data of the game state, typically a serialized protobuf."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameType",
            fields=[
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for the game type, used in URLs and references. Examples: 'checkers', 'chess', 'tic_tac_toe'.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name of the game type. Example: 'Checkers'.",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the game type and its rules or characteristics.",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="If the game_type is enabled or not. It won't be possible to play disabled games",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the room.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Public name of the room, visible to users.", max_length=100
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Timestamp when the room was created."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update to the room (e.g., new participant).",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="If true, the room is visible to everyone; otherwise, it's private.",
                    ),
                ),
                (
                    "is_open",
                    models.BooleanField(
                        default=True, help_text="If false, new participants cannot join this room."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the event occurred (according to engine or server).",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Type or name of the event (e.g., 'move_made', 'game_over').",
                        max_length=64,
                    ),
                ),
                (
                    "payload",
                    models.BinaryField(
                        help_text="Serialized payload of the event (e.g., protobuf)."
                    ),
                ),
                ("applied", models.BooleanField(help_text="If the event has been applied or not")),
                (
                    "action",
                    models.ForeignKey(
                        help_text="Associated action that generated this event",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="board_games_core.action",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game in which this event occurred.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_logs",
                        to="board_games_core.game",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="action",
            name="game",
            field=models.ForeignKey(
                help_text="The game in which this action was performed.",
                on_delete=django.db.models.deletion.CASCADE,
                to="board_games_core.game",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="game_type",
            field=models.ForeignKey(
                help_text="The type of game being played (e.g., Checkers, Chess).",
                on_delete=django.db.models.deletion.PROTECT,
                to="board_games_core.gametype",
            ),
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the participant.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("player", "Player"), ("spectator", "Spectator")],
                        default="spectator",
                        help_text="Role of the participant (e.g., 'player', 'spectator', 'referee').",
                        max_length=20,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Timestamp when the participant joined the game.",
                    ),
                ),
                (
                    "player_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="The player's number/seat in the game (e.g., 1 or 2). Null for spectators.",
                        null=True,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        help_text="Game this participant played in (if applicable).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="board_games_core.game",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="Room this participant is currently in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="board_games_core.room",
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "player_number")},
            },
        ),
        migrations.AddField(
            model_name="action",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                help_text="The participant who performed this action. Can be null for system actions.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="board_games_core.participant",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="room",
            field=models.OneToOneField(
                help_text="The room where this game is taking place.",
                on_delete=django.db.models.deletion.CASCADE,
                to="board_games_core.room",
            ),
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When the snapshot was taken."
                    ),
                ),
                (
                    "payload",
                    models.BinaryField(
                        help_text="Raw binary data of the game state, typically a serialized protobuf."
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        help_text="Associated event that generated this Snapshot",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="board_games_core.event",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="Game for this snapshot.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="board_games_core.game",
                    ),
                ),
            ],
        ),
    ]
