# Generated by Django 5.2 on 2025-07-21 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_games_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameAction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action_index",
                    models.PositiveIntegerField(
                        help_text="Sequential index of the action in the game timeline, starting from 0."
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When the action was taken."
                    ),
                ),
                (
                    "payload",
                    models.BinaryField(
                        help_text="Raw binary data of the action, typically a serialized protobuf."
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        help_text="The game in which this action was performed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="board_games_core.game",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        help_text="The participant who performed this action. Can be null for system actions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to="board_games_core.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["game", "action_index"],
                "unique_together": {("game", "action_index")},
            },
        ),
    ]
