# Generated by Django 5.2 on 2025-08-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_games_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(
                help_text="Public name of the room, visible to users.", max_length=100
            ),
        ),
    ]
