# Generated by Django 5.2 on 2025-12-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_games_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="game",
            field=models.ForeignKey(
                help_text="Game in which this event occurred.",
                on_delete=django.db.models.deletion.CASCADE,
                to="board_games_core.game",
            ),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="game",
            field=models.ForeignKey(
                help_text="Game for this snapshot.",
                on_delete=django.db.models.deletion.CASCADE,
                to="board_games_core.game",
            ),
        ),
    ]
