# Generated by Django 5.2 on 2025-08-22 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_games_core", "0002_alter_room_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="action",
            field=models.OneToOneField(
                default=0,
                help_text="Associated action that generated this EventLog.",
                on_delete=django.db.models.deletion.CASCADE,
                to="board_games_core.gameaction",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gameaction",
            name="action_type",
            field=models.CharField(
                default="no-action",
                help_text="Type or name of the action (e.g., 'movement').",
                max_length=64,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gameaction",
            name="applied",
            field=models.BooleanField(
                default=False, help_text="If the action was successfully applied or not"
            ),
            preserve_default=False,
        ),
    ]
