# Generated by Django 5.2 on 2025-08-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board_games_core", "0003_eventlog_action_gameaction_action_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gameaction",
            options={"ordering": ["game", "timestamp"]},
        ),
        migrations.AlterUniqueTogether(
            name="gameaction",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="gameaction",
            name="action_index",
        ),
    ]
