# Generated by Django 5.2 on 2025-08-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board_games_core", "0004_alter_gameaction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gametype",
            name="enabled",
            field=models.BooleanField(
                default=False,
                help_text="If the game_type is enabled or not. It won't be possible to play disabled games",
            ),
        ),
    ]
