load("@bazel_skylib//rules:common_settings.bzl", "string_flag")

exports_files(["sh_with_runfiles_binary.tpl.sh"])

string_flag(
    name = "machine",
    build_setting_default = "user",
    values = [
        "user",
        "ci",
    ],
    visibility = ["//visibility:public"],
)

config_setting(
    name = "machine_user",
    flag_values = {
        ":machine": "user",
    },
)
