load("@aspect_bazel_lib//lib:expand_template.bzl", "expand_template")
load("@rules_oci//oci:defs.bzl", "oci_push")
load("//bazel/containers/buildx:image_from_dockerfile.bzl", "image_from_dockerfile")
load("//bazel/python/django/containers:defs.bzl", "DJANGO_PORT", "USER")

image_name = "nginx_django"

repository = "ghcr.io/jgsogo/{}".format(image_name)  # FIXME: Make it global for all the repo

expand_template(
    name = "nginx_conf",
    out = "nginx.conf",
    substitutions = {
        "%USER%": USER,
        "%DJANGO_PORT%": DJANGO_PORT,
    },
    template = ":nginx.conf.tpl",
)

image_from_dockerfile(
    name = "nginx",
    srcs = [
        "Dockerfile",
        ":nginx_conf",
    ],
    repository = repository,
    tags = [
        "manual",
    ],
    visibility = [
        "//visibility:public",
    ],
)

oci_push(
    name = "release",
    image = ":nginx",
    remote_tags = "//:stable_build_scm_revision",
    repository = repository,
    tags = [
        "manual",
        "no-remote-cache",
        "release",
    ],
    visibility = [
        "//apps:__subpackages__",
    ],
)
