
# Django
DEBUG=False
SECRET_KEY=
DJANGO_ALLOWED_HOSTS="localhost 127.0.0.1 0.0.0.0 [::1]"

# Database"
DJANGO_SQL_ENGINE=
DJANGO_SQL_DATABASE=
DJANGO_SQL_USER=
DJANGO_SQL_PASSWORD=
DJANGO_SQL_HOST=
DJANGO_SQL_PORT=

# Django static and media files
STATIC_ROOT=${WWW_DATA_FOLDER}/static/
MEDIA_ROOT=${WWW_DATA_FOLDER}/media/

# gunicorn
GUNICORN_APP_NAME=%NAME%
GUNICORN_LOGS_FOLDER=${LOGS_FOLDER}
GUNICORN_RUN_FOLDER=${RUN_FOLDER}
GUNICORN_USER=$(whoami)
GUNICORN_GROUP=$(id -gn jgsogo)
