
# Django
DEBUG=False
SECRET_KEY=
DJANGO_ALLOWED_HOSTS="localhost 127.0.0.1 0.0.0.0 [::1]"

# Database"
DJANGO_SQL_ENGINE=
DJANGO_SQL_DATABASE=
DJANGO_SQL_USER=
DJANGO_SQL_PASSWORD=
DJANGO_SQL_HOST=
DJANGO_SQL_PORT=

# Django static and media files
STATIC_ROOT=$OUTPUT_DIRECTORY/static/
MEDIA_ROOT=$OUTPUT_DIRECTORY/media/

# gunicorn
GUNICORN_APP_NAME=%NAME%
GUNICORN_WORKING_DIR=$OUTPUT_DIRECTORY
GUNICORN_USER=$(whoami)
GUNICORN_GROUP=$(id -gn jgsogo)
GUNICORN_BIND="unix:$OUTPUT_DIRECTORY/run/gunicorn.sock"
