load("@aspect_rules_js//js:defs.bzl", "js_run_devserver")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("//bazel:sh_with_runfiles_binary.bzl", "sh_with_runfiles_binary")
load("//bazel/tauri:defs.bzl", "tauri_run")

npm_link_all_packages(name = "node_modules")

filegroup(
    name = "src",
    srcs = glob(["src/**/*.*"]),
)

filegroup(
    name = "static",
    srcs = glob(["static/**/*.*"]),
)

js_run_devserver(
    name = "devserver",
    args = ["dev --config vite.config.js"],
    chdir = package_name(),
    command = "./node_modules/.bin/vite",
    data = [
        # Configs
        "vite.config.js",
        "package.json",
        "tsconfig.json",
        "svelte.config.js",

        # Build deps
        ":node_modules",  # TODO: Use //:node_modules instead

        # Sources
        ":src",
        ":static",
    ],
    grant_sandbox_write_permissions = True,
)

tauri_run(
    name = "dev",
    backend = "//apps/finances/tauri/src-tauri:app",
    frontend = ":devserver",
)

# FIXME: This is mostly a workaround because the ":dev" target is not working (see ../README.md),
# it executes "tauri dev" outside Bazel using the files in the workspace
sh_with_runfiles_binary(
    name = "dev_sh",
    args = [
        "--dir /Users/jgsogo/personal/totum-revolutum/apps/finances/tauri",
        "tauri",
        "dev",
    ],
    tags = [
        "manual",
        "workaround",
    ],
    tool = "@pnpm",
    visibility = ["//visibility:public"],
)
