load("@aspect_rules_js//js:defs.bzl", "js_run_devserver")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("//bazel/tauri:defs.bzl", "tauri_run")

npm_link_all_packages(name = "node_modules")

filegroup(
    name = "src",
    srcs = glob(["src/**/*.*"]),
)

filegroup(
    name = "static",
    srcs = glob(["static/**/*.*"]),
)

js_run_devserver(
    name = "devserver",
    args = ["dev --config vite.config.js"],
    chdir = package_name(),
    command = "./node_modules/.bin/vite",
    data = [
        # Configs
        "package.json",
        "postcss.config.cjs",
        "svelte.config.js",
        "tailwind.config.js",
        "tsconfig.json",
        "vite.config.js",

        # Build deps
        ":node_modules",  # TODO: Use //:node_modules instead
        # ":node_modules/tailwindcss",
        # ":node_modules/flowbite",
        "//apps/finances/tauri/models:src_ts",
        "//apps/finances/tauri/models/protos:protos_ts",

        # "//apps/finances/tauri/src-tauri:tauri_conf_json",

        # Sources
        ":src",
        ":static",
    ],
    grant_sandbox_write_permissions = True,
)

tauri_run(
    name = "dev",
    backend = "//apps/finances/tauri/src-tauri:app",
    frontend = ":devserver",
    visibility = ["//visibility:public"],
)

# # FIXME: This is mostly a workaround because the ":dev" target is not working (see ../README.md),
# # it executes "tauri dev" outside Bazel using the files in the workspace
# sh_with_runfiles_binary(
#     name = "dev_sh",
#     data = [
#         # Configs
#         "vite.config.js",
#         "package.json",
#         "tsconfig.json",
#         "svelte.config.js",

#         # Build deps
#         ":node_modules",  # TODO: Use //:node_modules instead
#         "//apps/finances/tauri/models:src_ts",
#         "//apps/finances/tauri/models/protos:protos_ts",

#         # "//apps/finances/tauri/src-tauri:tauri_conf_json",
#         # "//apps/finances/tauri/src-tauri:app",
#         "//apps/finances/tauri/src-tauri:all",

#         # Sources
#         ":src",
#         ":static",
#     ],
#     args = [
#         "--dir apps/finances/tauri",
#         # "--dir /Users/jgsogo/personal/totum-revolutum/apps/finances/tauri",
#         "tauri",
#         "dev",
#         # "--config=apps/finances/tauri/src-tauri/tauri.conf.json",
#         "--no-watch",
#         "--runner=andwhat", # This is the app to use to run the binary (cargo)
#         # "--help",
#     ],
#     tags = [
#         "manual",
#         "workaround",
#     ],
#     tool = "@pnpm",
#     visibility = ["//visibility:public"],
# )
