load("@aspect_rules_js//js:defs.bzl", "js_run_binary", "js_run_devserver")

filegroup(
    name = "src",
    srcs = glob(["src/**/*.*"]),
)

filegroup(
    name = "static",
    srcs = glob(["static/**/*.*"]),
)

filegroup(
    name = "configs",
    srcs = [
        "postcss.config.cjs",
        "svelte.config.js",
        "tsconfig.json",
        "vite.config.js",
    ],
)

js_run_binary(
    name = "frontend",
    srcs = [
        # Build deps
        "package.json",
        "//:node_modules",  # TODO: Consume only the required deps
        "//apps/finances/tauri/models:models/ts",

        # Sources
        ":configs",
        ":src",
        ":static",
    ],
    args = ["build --sourcemap --config vite.config.js"],  # TODO: Source map allow us to go from the error to the source code. Use it in debug builds!
    # args = ["build --config vite.config.js"],
    chdir = package_name(),
    out_dirs = ["build"],
    tool = "//bazel/tools/npm:vite_binary",
    visibility = ["//apps/finances/tauri/src-tauri:__pkg__"],
)

js_run_devserver(
    name = "devserver",
    args = ["dev --config vite.config.js"],
    chdir = package_name(),
    command = "./node_modules/.bin/vite",
    data = [
        # Build deps
        "package.json",
        "//:node_modules",  # TODO: Consume only the required deps
        "//apps/finances/tauri/models:models/ts",

        # Sources
        ":configs",
        ":src",
        ":static",
    ],
    grant_sandbox_write_permissions = True,
    visibility = ["//apps/finances:__pkg__"],
)
