load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "data",
    srcs = [
        "constants.hpp",
        "game.cpp",
        "room.cpp",
    ],
    hdrs = [
        "game.h",
        "room.h",
    ],
    visibility = [
        "//apps/board_games/engine:__subpackages__",
        "//apps/board_games/games:__subpackages__",
    ],
    deps = [
        "//apps/board_games/engine/data/models",
        "//apps/board_games/engine/errors",
        "//bazel/logging:spdlog",
        "//libraries/utils/cpp/libpqxx:connection_pool",
        "//libraries/utils/cpp/libpqxx:notify",
    ],
)
