# Use 'pre-commit autoupdate' in the CLI to update these repositories

# Use a slightly older version of node by default
# as the default uses a very new version of GLIBC
default_language_version:
  node: 16.18.0

fail_fast: true

repos:
  # Some common pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      # - id: check-illegal-windows-names # Introduced in next version
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: pretty-format-json
        args: [ --autofix ]
      - id: no-commit-to-branch
      - id: file-contents-sorter
        files: (\.gitignore|\.bazelignore)
        args: [ --unique ]

  # Check formatting and lint for starlark code
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 7.3.1.1
    hooks:
      - id: buildifier
      - id: buildifier-lint

  # Enforce that commit messages allow for later changelog generation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      # Requires that commitizen is already installed
      - id: commitizen
        stages: [ commit-msg ]

  # Run Rust pre-commit hooks
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy

  # Lint and format SQL files
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.0
    hooks:
      - id: sqlfluff-lint
      - id: sqlfluff-fix

  # Python
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args:
          - "-l 100"

  - repo: https://github.com/PyCQA/flake8.git
    rev: 7.1.1
    hooks:
      - id: flake8
        exclude: "migrations/"  # Python regex
        args:
          - "--max-line-length=100"

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Some local scripts
  - repo: local
    hooks:
      # - id: cargo-check
      #   name: cargo +nightly check
      #   entry: cargo +nightly check
      #   language: system
      #   always_run: true
      #   pass_filenames: false

      #      - id: branch-updated
      #        name: Branch up-to-date with master
      #        entry: scripts/branch_updated.sh
      #        language: script
      #        always_run: true

      # - id: cargo-check
      #   name: Run cargo check (using the rules_rust managed version)
      #   entry: bazel run @rules_rust//tools/upstream_wrapper:cargo -- check
      #   language: script
      #   always_run: true
      #   require_serial: true

      - id: rustfmt
        name: Run rustfmt (rules_rust managed version)
        entry: bazel/tools/rustfmt.sh
        language: script
        files: \.rs$
        # exclude: ^(qcm/.*/build\.rs)
        # require_serial: true

      - id: bazel-check
        name: Run all Bazel targets with 'check' tag
        entry: scripts/bazel_run_targets.sh check
        language: script
        always_run: true
        require_serial: true

      - id: bazel-update
        name: Run all Bazel targets with 'update' tag (update workspace files)
        entry: scripts/bazel_run_targets.sh update
        language: script
        always_run: true
        require_serial: true
