# Use 'pre-commit autoupdate' in the CLI to update this repositories

# Use a slightly older version of node by default
# as the default uses a very new version of GLIBC
default_language_version:
  node: 16.18.0

repos:
  # Some common pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      # - id: check-illegal-windows-names # Introduced in next version
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: pretty-format-json
      - id: no-commit-to-branch

  # Check formatting and lint for starlark code
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 6.4.0
    hooks:
      - id: buildifier
      - id: buildifier-lint

  # Enforce that commit messages allow for later changelog generation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.22.0
    hooks:
      # Requires that commitizen is already installed
      - id: commitizen
        stages: [commit-msg]

  # Prettify some source code files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier

  # Run Rust pre-commit hooks
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy

  # Some local scripts
  - repo: local
    hooks:
      - id: branch-updated
        name: Branch up-to-date with master
        entry: scripts/branch_updated.sh
        language: script
