# https://rust-lang.github.io/rustfmt/?version=v1.5.1

edition = "2021"
# use_field_init_shorthand = true
# reorder_imports = true
max_width = 120

# TODO: Only supported in nightly. Meanwhile, we are patching the generated schema.rs files to skip rustfmt
#ignore = [
#    "apps/photodb/src/schema.rs",
#    "libraries/diesel_utils/tests/common/schema.rs",
#]
