[workspace]
resolver = "2"
members = [
    "apps/photodb",
    "apps/syncronia",
    "libraries/cron",
    "libraries/conductus",
    "libraries/constants",
    "libraries/diesel_utils",
    "libraries/filesystem",
    "libraries/pcloud_sdk",
    "libraries/rebrickable",
    "libraries/utils",
    # A placeholder to depend on _external_ crates (see [this note](./notes/2024-05-04-1923.md))
    "bazel/external",
]


# List all the dependencies. In the Bazel world we need all the dependencies here
# so they are available in the crate_universe.
[workspace.dependencies]
anyhow = "1.0.82"
async-std = { version = "1.12" }
async-trait = "0.1.80"
bitflags = "2.5"
bytes = "1.6.0"
camino = "1.1.6"
camino-tempfile = "1.1.1"
chrono = { version = "0.4.38" }
chrono-tz = { version = "0.9.0" }
clap = { version = "4.5.4", features = ["cargo", "string"] }
clap_complete = "4.5.2"
clap-verbosity-flag = { version = "2.2" }
confy = { version = "0.6.1", default-features = false, features = ["yaml_conf"] }
cron-parser = "0.9.0"
data-encoding = "2.6.0"
diesel = { version = "2.2.0", default-features = false, features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "2.2.0", default-features = false, features = ["sqlite"] }
diesel_table_macro_syntax = "0.2.0"
diffy = "0.4.0"
dirs = { version = "5.0.1" }
dotenvy = "0.15.7"
dyn-clone = "1.0.17"
env_logger = "0.11.3"
kamadak-exif = "0.5.5"
flume = "0.11.0"
fs4 = { version = "0.9.1" }
futures = { version = "0.3.30" }
futures-util = { version = "0.3.30", default-features = false }
headers = { version = "0.4.0" }
home = { version = "0.5.9" }
http = "1.1.0"
http-body = "1.0.0"
http-body-util = "0.1.1"
httpmock = { version = "0.7" }
hyper = { version = "1.4.0" }
hyper-util = { version = "0.1.6" }
ignore = { version = "0.4.22" }
ignore-files = "3.0.1"
image = { version = "0.25.1" }
indicatif = { version = "0.17.8" }
itertools = "0.13.0"
lazy_static = "1.4.0"
log = "0.4.21"
main_error = "0.1.2"
mime = "0.3.17"
mockall = { version = "0.13.0" }
num-traits = "0.2.19"
oxipng = { version = "9.0", features = ["parallel", "zopfli", "filetime"], default-features = false }
regex = "1.10.5"
reqwest = { version = "0.12.4" }
ring = "0.17.8"
serde = { version = "1.0.200" }
serde_json = "1.0.121"
serde_regex = "1.1.0"
serde_repr = "0.1.19"
serde_yaml = "0.9.34"
sha256 = { version = "1.5" }
strum = "0.26.3"
strum_macros = "0.26.2"
syn = { version = "2.0.74", features = ["visit"] }
tempfile = { version = "3.10.1" }
testing_logger = "0.1.1"
thiserror = "1.0.59"
time = { version = "0.3.36" }
tokio = { version = "1.39" }
tokio-stream = "0.1.15"
toml = "0.8.12"
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }
tryhard = { version = "0.5.1" }
url = "2.5"
uuid = "1.3.2"
