[workspace]
resolver = "2"
members = [
    "apps/syncronia",
    "libraries/constants",
    "libraries/filesystem",
    "libraries/filesystem_pcloud",
    "libraries/pcloud_sdk",
    ]


# List all the dependencies that are "common" to all crates. If using them, we
# probably want to use the same version for all of them.
[workspace.dependencies]
anyhow = "1.0.82"
async-std = { version = "1.12" }
async-trait = "0.1"
camino = "1.1"
clap = { version = "4.1" }
clap-verbosity-flag = { version = "2.0.0" }
dyn-clone = "1.0.17"
flume = "0.11.0"
futures = { version = "0.3" }
httpmock = { version = "0.6" }
ignore = { version = "0.4" }
indicatif = { version = "0.17" }
lazy_static = "1.4.0"
log = "0.4.21"
main_error = "0.1.2"
mockall = { version = "0.11" }
num-traits = "0.2.18"
sha256 = { version = "1.5" }
strum = "0.26.2"
strum_macros = "0.26.2"
tempfile = { version = "3" }
tokio = { version = "1.26" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
