set dotenv-load := true

mod apps
mod utils 'justfiles/utils.just'

_default: _just-check
    @{{ just_executable() }} --choose  # Requires 'fzf' (https://formulae.brew.sh/formula/fzf)

_just-check:
    {{ just_executable() }} --unstable --fmt --check

# Updates all the dependencies (MODULE.bazel and 3rd parties not included)
[group('update')]
update: update-deps update-precommit

[group('update')]
update-precommit:
    max=10; until pre-commit autoupdate || [[ "$max" -le 0 ]]; do sleep 1; ((--max)); done # Run 10 times (it frequently fails with SSL errors)

# Updates only the dependencies
[group('update')]
update-deps: update-bazel update-rust update-npm update-python

[group('update')]
update-rust:
    cargo update
    rm -fr bazel/third_party/crates # Remove everything in the 3rd party directory
    bazel run @@//bazel/third_party:crates_vendor
    bazel mod tidy
    @echo "🤖🦾 Rust - Fix some autogenerated files"
    bazel run //bazel/third_party:patch_crates_vendor -- $(bazel info workspace)/bazel/third_party/crates
    @echo "🤖🦾 Run buildifier"
    pre-commit run buildifier

[group('update')]
update-npm:
    bazel run -- @pnpm --dir $(pwd) update --recursive --workspace
    @echo "🤖🦾 NPM - Update some auto generated files"
    bazel run @@//libraries/googleapis/protos/google/type:protos_ts.copy
    bazel run @@//apps/finances/tauri/models/protos:protos_ts.copy
    bazel run //apps/board_games/engine/protocol:engine_ts_proto.copy
    bazel run //apps/board_games/games/tic_tac_toe/models:models_ts_proto.copy

[group('update')]
update-python:
    bazel run @@//bazel/third_party:python_requirements

[group('update')]
update-bazel:
    scripts/update_bazel_version.sh
    scripts/update_bazel_modules.sh MODULE.bazel protobuf.MODULE.bazel llvm.MODULE.bazel
    bazel mod tidy

# Run all testing
[group('dev')]
test: build bazel-check rules_qt-test
    # cargo check
    # cargo clippy
    bazel run //bazel/tools/format
    bazel test --test_keep_going //...

# Build everything
[group('dev')]
build: bazel-update npm-install
    # cargo build
    bazel build --keep_going //...

[group('dev')]
npm-install:
    # FIXME: Remove. These 'install' rules are just creating the node_modules in the workspace, but Bazel uses the ones in the build directory (created by the 'npm_link_all_packages' rule)
    #        I wonder, however, if this can be useful to vscode for linting in the IDE
    bazel run -- @pnpm//:pnpm --dir $(pwd) install --lockfile-only # Only this one is needed to update pnpm-lock.yaml
    bazel run -- @pnpm --dir $(pwd) install --recursive

# Run all the Bazel targets labelled with 'update' tag
[group('bazel')]
bazel-update: rules_qt-bazel-update (utils::_bazel_run_targets 'update')

# Run all the Bazel targets labelled with 'check' tag
[group('bazel')]
bazel-check: (utils::_bazel_run_targets 'check')

# Run all the `oci_load` rules: These rules will generate OCI containers and load them into the local registry
[group('bazel')]
bazel-load-oci: utils::_bazel_run_oci_load

# Execute tokei: prints statistics about the repository
[group('repo')]
tokei:
    tokei --sort lines --compact

# Shows the documentation
[group('dev')]
doc:
    cargo doc --open --document-private-items --all-features --workspace

# Removes temporary files (free disk space)
[group('dev')]
clean:
    cargo clean
    bazel clean
    docker system prune --volumes --force

# Reset: removes all temporary files and recreates the workspace (Cargo and Bazel). This can take a while
[group('dev')]
reset: clean build test

# Starts a bazel remote cache service
[group('dev')]
bazel-remote:
    docker-compose --env-file .env -f ./tools/github/self-hosted-runner/docker-compose-bazel.yml up --build -d bazel-remote

# Run bazel-remote (cache) and github runner
[group('github')]
gh-runner-linux:
    docker-compose --env-file .env -f ./tools/github/self-hosted-runner/docker-compose-bazel.yml up --build -d

[group('github')]
gh-runner-linux-logs:
    docker-compose -f ./tools/github/self-hosted-runner/docker-compose-bazel.yml logs -f

# Stops bazel-remote (cache) and github runner
[group('github')]
gh-runner-linux-stop:
    docker-compose -f ./tools/github/self-hosted-runner/docker-compose-bazel.yml down

# Run gh self-hosted runner for Macos
[group('github')]
[working-directory('actions-runner')]
gh-runner-macos:
    curl -o actions-runner-osx-x64-2.322.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.322.0/actions-runner-osx-x64-2.322.0.tar.gz
    echo "aa0fc262363912167dcdbc746ffcdf7b8996bc587f51cf1bab38ad86cf70b6ea  actions-runner-osx-x64-2.322.0.tar.gz" | shasum -a 256 -c
    tar xzf ./actions-runner-osx-x64-2.322.0.tar.gz
    rm actions-runner-osx-x64-2.322.0.tar.gz
    ./../tools/github/self-hosted-runner/runner.sh # Do not detach

# Run self-hosted runners for Linux and Macos
[group('github')]
gh-runner: gh-runner-linux gh-runner-macos

# Stop self-hosted runners for Linux
[group('github')]
gh-runner-stop: gh-runner-linux-stop

# Run all testing
[group('@rules_qt')]
[working-directory('third_party/@rules_qt')]
rules_qt-test:
    bazel test --test_keep_going //...

# Run all the Bazel targets labelled with 'update' tag
[group('@rules_qt')]
[working-directory('third_party/@rules_qt')]
rules_qt-bazel-update:
    just utils::_bazel_run_targets 'update' $(pwd)
