"""
Configure LLVM toolchains
"""

bazel_dep(name = "toolchains_llvm", version = "1.5.0")
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")
bazel_dep(name = "spdlog", version = "1.16.0")
bazel_dep(name = "catch2", version = "3.11.0")
bazel_dep(name = "magic_enum", version = "0.9.7")
bazel_dep(name = "rules_qt")
local_path_override(
    module_name = "rules_qt",
    path = "third_party/@rules_qt",
)

# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    commit = "abb61a688167623088f8768cc9264798df6a9d10",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    # Replace the commit hash (above) with the latest (https://github.com/hedronvision/bazel-compile-commands-extractor/commits/main).
    # Even better, set up Renovate and let it do the work for you (see "Suggestion: Updates" in the README).
)

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

STDUUID_VERSION = "1.2.3"

http_archive(
    name = "stduuid",
    build_file = "//bazel/external:BUILD.stduuid.bazel",
    sha256 = "b1176597e789531c38481acbbed2a6894ad419aab0979c10410d59eb0ebf40d3",
    strip_prefix = "stduuid-{}".format(STDUUID_VERSION),
    type = "tar.gz",
    urls = ["https://github.com/mariusbancila/stduuid/archive/refs/tags/v{}.tar.gz".format(STDUUID_VERSION)],
)

# LLVM Versions and platforms
# https://github.com/bazel-contrib/toolchains_llvm/blob/master/toolchain/internal/llvm_distributions.bzl
LLVM_VERSION = "20.1.7"

###############################################################################
# L L V M
#
# https://github.com/bazel-contrib/toolchains_llvm/blob/master/tests/MODULE.bazel
###############################################################################
llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")

# LLVM toolchain.
llvm.toolchain(
    llvm_version = LLVM_VERSION,
)
use_repo(llvm, "llvm_toolchain")
use_repo(llvm, "llvm_toolchain_llvm")  # if you depend on specific tools in scripts

register_toolchains("@llvm_toolchain//:all")

#####
# Qt
#####
qt = use_extension("@rules_qt//:extensions.bzl", "qt")
qt.configure(qt_version = "6.9.2")
use_repo(qt, "qt_mac_clang_64")

#####
# Other extensions
#####

libpqxx_non_module_dependencies = use_extension("//third_party/libpqxx:extensions.bzl", "non_module_dependencies")
use_repo(libpqxx_non_module_dependencies, "libpqxx")

tl_expected_non_module_dependencies = use_extension("//third_party/tl-expected:extensions.bzl", "non_module_dependencies")
use_repo(tl_expected_non_module_dependencies, "tl-expected")

date_non_module_dependencies = use_extension("//third_party/date:extensions.bzl", "non_module_dependencies")
use_repo(date_non_module_dependencies, "date")

decimal_for_cpp_non_module_dependencies = use_extension("//third_party/decimal_for_cpp:extensions.bzl", "non_module_dependencies")
use_repo(decimal_for_cpp_non_module_dependencies, "decimal_for_cpp")
