"""
Configure LLVM toolchains
"""

bazel_dep(name = "toolchains_llvm", version = "1.4.0")

# LLVM Versions and platforms
# https://github.com/bazel-contrib/toolchains_llvm/blob/master/toolchain/internal/llvm_distributions.bzl
LLVM_VERSION = "19.1.7"

###############################################################################
# L L V M
#
# https://github.com/bazel-contrib/toolchains_llvm/blob/master/tests/MODULE.bazel
###############################################################################
llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")

# LLVM toolchain.
llvm.toolchain(
    llvm_version = LLVM_VERSION,
)
use_repo(llvm, "llvm_toolchain")
use_repo(llvm, "llvm_toolchain_llvm")  # if you depend on specific tools in scripts

register_toolchains("@llvm_toolchain//:all")
