"""
Configure LLVM toolchains
"""

bazel_dep(name = "toolchains_llvm", version = "1.4.0")
bazel_dep(name = "rules_foreign_cc", version = "0.15.0")
bazel_dep(name = "spdlog", version = "1.15.3")
bazel_dep(name = "catch2", version = "3.8.1")

# LLVM Versions and platforms
# https://github.com/bazel-contrib/toolchains_llvm/blob/master/toolchain/internal/llvm_distributions.bzl
LLVM_VERSION = "19.1.7"

###############################################################################
# L L V M
#
# https://github.com/bazel-contrib/toolchains_llvm/blob/master/tests/MODULE.bazel
###############################################################################
llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")

# LLVM toolchain.
llvm.toolchain(
    llvm_version = LLVM_VERSION,
)
use_repo(llvm, "llvm_toolchain")
use_repo(llvm, "llvm_toolchain_llvm")  # if you depend on specific tools in scripts

register_toolchains("@llvm_toolchain//:all")

libpqxx_non_module_dependencies = use_extension("//third_party/libpqxx:extensions.bzl", "non_module_dependencies")
use_repo(libpqxx_non_module_dependencies, "libpqxx")

tl_expected_non_module_dependencies = use_extension("//third_party/tl-expected:extensions.bzl", "non_module_dependencies")
use_repo(tl_expected_non_module_dependencies, "tl-expected")
