module(
    name = "totum-revolutum",
    version = "0.0.0",
    compatibility_level = 1,
)

bazel_dep(name = "bazel_skylib", version = "1.7.1")
bazel_dep(name = "platforms", version = "0.0.10")

bazel_dep(name = "rules_python", version = "1.0.0", dev_dependency = True)
bazel_dep(name = "rules_rust", version = "0.56.0", dev_dependency = True)

bazel_dep(name = "rules_nodejs", version = "6.3.2")
bazel_dep(name = "aspect_rules_py", version = "1.0.0")
bazel_dep(name = "rules_oci", version = "2.2.0")
bazel_dep(name = "rules_pkg", version = "1.0.1")

bazel_dep(name = "rules_java", version = "8.6.3", dev_dependency = True)
bazel_dep(name = "aspect_bazel_lib", version = "2.10.0", dev_dependency = True)

bazel_dep(name = "aspect_rules_js", version = "2.1.2")
bazel_dep(name = "aspect_rules_ts", version = "3.3.2")
bazel_dep(name = "aspect_rules_jest", version = "0.22.0")

bazel_dep(name = "rules_uv", version = "0.46.0", dev_dependency = True)

# FIXME: Override rules_rust to add this patch: https://github.com/bazelbuild/rules_rust/pull/3102, required for the protobuf-stuff
archive_override(
    module_name = "rules_rust",
    integrity = "sha256-GtOMBT3FH1/Wmdfsp/mi5gYltPeulIwTxHDnSU04fu4=",
    patch_strip = 1,
    patches = [
        "@//bazel/external:rules_rust_0001-Workspace_members.patch",
    ],
    strip_prefix = "rules_rust-89aec557796a3a404f3458b8643a85d49a789b83",
    urls = ["https://github.com/bazelbuild/rules_rust/archive/89aec557796a3a404f3458b8643a85d49a789b83.tar.gz"],
)

http_jar = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")

# Bazel-diff: https://github.com/Tinder/bazel-diff
# TODO: Is this superseded: https://github.com/bazel-contrib/target-determinator? It uses
# TODO: bazel-differ (https://github.com/ewhauser/bazel-differ) under the hood, which is
# TODO: _"mostly a pure Go port of the excellent Tinder/bazel-diff"_
http_jar(
    name = "bazel_diff",
    sha256 = "ed5410288bd7ec5b49b556103f561fb15e4c82f13f12cb41be128d447ecc2d46",
    urls = [
        "https://github.com/Tinder/bazel-diff/releases/download/7.1.1/bazel-diff_deploy.jar",
    ],
)

########
# Python
# ======
#
# Here we configure a toolchain for Python. We will use [`aspect_rules_py`](https://github.com/aspect-build/rules_py)
# for our libraries and binaries
########
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    configure_coverage_tool = True,
    python_version = "3.12",
)
# use_repo(python, python_3 = "python_3_12") # Adds target @python_3//:python3, which is the Python interpreter

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "py_deps",
    python_version = "3.12",
    requirements_lock = "//bazel/third_party:requirements.lock",
)
use_repo(pip, "py_deps")

######
# Rust
# ====
#
# Rust setup is mostly taken from rust = use_extension("//rust:extensions.bzl", "rust")
######
rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.83.0"],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

#####
# Crates repositories
#####
crate = use_extension("@rules_rust//crate_universe:extension.bzl", "crate")

# Diesel CLI is a binary only package. We need to build it "manually" (see [this note](./notes/2024-05-04-1923.md))
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "diesel_cli",
    build_file = "//bazel/external:BUILD.diesel_cli.bazel",
    sha256 = "4a5a3f3bf0906ab9d40b6df4dfcafb4c20ab15ad96ad0e3ae919268151a50dd6",
    strip_prefix = "diesel_cli-2.2.6",
    type = "tar.gz",
    urls = ["https://crates.io/api/v1/crates/diesel_cli/2.2.6/download"],
)

crate.from_cargo(
    name = "crates_libraries",
    cargo_lockfile = "//:Cargo.lock",
    manifests = [
        "//:Cargo.toml",
        "//apps/finances/tauri/src-tauri:Cargo.toml",
        "//apps/finances/tauri/models:Cargo.toml",
        "//apps/photodb:Cargo.toml",
        "//apps/syncronia:Cargo.toml",
        "//libraries/conductus:Cargo.toml",
        "//libraries/constants:Cargo.toml",
        "//libraries/cron:Cargo.toml",
        "//libraries/diesel_utils:Cargo.toml",
        "//libraries/filesystem:Cargo.toml",
        "//libraries/finances/accounts/rust:Cargo.toml",
        "//libraries/finances/investments/rust:Cargo.toml",
        "//libraries/openexchangerates:Cargo.toml",
        "//libraries/pcloud_sdk:Cargo.toml",
        "//libraries/rebrickable:Cargo.toml",
        "//libraries/utils:Cargo.toml",
        # This is added to the workspace as a workaround for binary packages (see [this note](./notes/2024-05-04-1923.md))
        "//bazel/external:Cargo.toml",
        # Sandbox apps
    ],
    # Limiting the number of supported platforms can help with performance: https://github.com/bazelbuild/rules_rust/discussions/2259
    supported_platform_triples = [
        "aarch64-apple-darwin",  # FIXME: https://github.com/bazelbuild/rules_rust/issues/3011#issuecomment-2488307333
        # "aarch64-unknown-linux-gnu",
        "x86_64-apple-darwin",
        "x86_64-unknown-linux-gnu",
    ],
)
use_repo(crate, "crates_libraries")

#####
# Node
# ====
#
# rules_nodejs devs recommend using aspect_rules_js for npm install (see https://github.com/bazelbuild/rules_nodejs/issues/3138),
# so here I'm just following their examples: https://github.com/aspect-build/rules_js/blob/main/MODULE.bazel
####
# node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node", dev_dependency = True)
# node.toolchain()  # Uses default version from https://github.com/bazelbuild/rules_nodejs/blob/main/nodejs/repositories.bzl#L19

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm", dev_dependency = True)
npm.npm_translate_lock(
    name = "npm",
    bins = {
        # This is basically the "bin" entry from `node_modules/<package>/package.json`
        "vite": [
            "vite=./bin/vite",
        ],
    },
    data = [
        "//apps/finances/tauri:package.json",
        "//apps/finances/tauri/models:package.json",
        "//sandbox/svelte-hello-world:package.json",
        "//sandbox/ts-library-with-tests:package.json",
    ],
    # generate_bzl_library_targets = True,
    npmrc = "//:.npmrc",
    pnpm_lock = "//:pnpm-lock.yaml",
    # update_pnpm_lock = True,
    verify_node_modules_ignored = "//:.bazelignore",
)
use_repo(npm, "npm")

pnpm = use_extension("@aspect_rules_js//npm:extensions.bzl", "pnpm")

# Allows developers to use the matching pnpm version, for example:
# bazel run -- @pnpm --dir $(pwd)/sandbox/svelte-hello-world install
use_repo(pnpm, "pnpm")

################################################################################
# rules_ts
################################################################################

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext", dev_dependency = True)
rules_ts_ext.deps()
use_repo(rules_ts_ext, "npm_typescript")

#####
# Extensions
# ====
#
fetch_buildx = use_extension("//bazel/containers/buildx:extensions.bzl", "fetch_buildx")
use_repo(fetch_buildx, "buildx_darwin_amd64", "buildx_darwin_arm64", "buildx_linux_amd64", "configure_buildx")

fetch_gh = use_extension("//bazel/tools/gh:extensions.bzl", "fetch_gh")
use_repo(fetch_gh, "gh_darwin_amd64", "gh_darwin_arm64", "gh_linux_amd64")

include("//:protobuf.MODULE.bazel")
