module(
    name = "totum_revolutum",
    version = "0.0.0",
    compatibility_level = 1,
)

bazel_dep(name = "bazel_skylib", version = "1.5.0")
bazel_dep(name = "platforms", version = "0.0.8")

bazel_dep(name = "rules_python", version = "0.31.0", dev_dependency = True)
bazel_dep(name = "rules_rust", version = "0.41.1", dev_dependency = True)

bazel_dep(name = "aspect_rules_py", version = "0.5.0")

bazel_dep(name = "aspect_bazel_lib", version = "2.5.1", dev_dependency = True)

http_jar = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_jar")

# Bazel-diff: https://github.com/Tinder/bazel-diff
http_jar(
    name = "bazel_diff",
    sha256 = "0b9e32f9c20e570846b083743fe967ae54d13e2a1f7364983e0a7792979442be",
    urls = [
        "https://github.com/Tinder/bazel-diff/releases/download/7.0.0/bazel-diff_deploy.jar",
    ],
)

########
# Python
# ======
#
# Here we configure a toolchain for Python. We will use [`aspect_rules_py`](https://github.com/aspect-build/rules_py)
# for our libraries and binaries
########
python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    configure_coverage_tool = True,
    python_version = "3.12",
)

######
# Rust
# ====
#
# Rust setup is mostly taken from rust = use_extension("//rust:extensions.bzl", "rust")
######
rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.75.0"],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

#####
# Crates repositories
#####
crate = use_extension("@rules_rust//crate_universe:extension.bzl", "crate")
crate.from_cargo(
    name = "crates_libraries",
    cargo_lockfile = "//libraries:Cargo.lock",
    manifests = [
        "//libraries:Cargo.toml",
        "//libraries/filesystem:Cargo.toml",
        "//libraries/constants:Cargo.toml",
        "//libraries/pcloud_sdk:Cargo.toml",
    ],
)
use_repo(crate, "crates_libraries")
