# All the Bazel stuff required to have protobuf available
#
# Copied from: https://github.com/bazelbuild/rules_rust/blob/main/examples/bzlmod/proto/MODULE.bazel

bazel_dep(name = "rules_proto", version = "7.1.0")
bazel_dep(name = "toolchains_protoc", version = "0.4.1")
bazel_dep(name = "protobuf", version = "30.2")
bazel_dep(name = "rules_rust_prost", version = "0.61.0")

# 2 Register Proto toolchain
###############################################################################
# Proto toolchain
# register_toolchains("@rules_rust_prost//:default_prost_toolchain")

# Custom Prost toolchain
register_toolchains("@//bazel/rust/prost:prost_toolchain")

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.spec(
    package = "protoc-gen-prost",
    version = "0.4.0",
)
crate.annotation(
    crate = "protoc-gen-prost",
    gen_binaries = ["protoc-gen-prost"],
)
crate.spec(
    package = "protoc-gen-tonic",
    version = "0.4.1",
)
crate.annotation(
    crate = "protoc-gen-tonic",
    gen_binaries = ["protoc-gen-tonic"],
)
crate.from_specs(
    name = "crates_protoc",
    supported_platform_triples = [
        # "aarch64-apple-darwin",
        # "aarch64-unknown-linux-gnu",
        "x86_64-apple-darwin",
        "x86_64-unknown-linux-gnu",
    ],
)
use_repo(crate, "crates_protoc")
