[package]
name = "http_utils"
version = "0.1.0"
edition = "2021"

[features]


[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
headers = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
