load("@crates_libraries//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test", "rust_test_suite")
load("@totum//bazel:defs.bzl", "run_copy_to_workspace")
load("@totum//bazel/rust/diesel:defs.bzl", "diesel_print_schema", "diesel_setup")

filegroup(
    name = "diesel_config",
    srcs = ["diesel.toml"],
)

filegroup(
    name = "migrations",
    srcs = glob(["migrations/**/*.sql"]),
)

diesel_setup(
    name = "setup",
    config_file = ":diesel_config",
    database_url = "db.sqlite3",
    migrations = [
        ":migrations",
    ],
)

diesel_print_schema(
    name = "schema",
    config_file = ":diesel_config",
    database_url = ":setup",
    schema = "src/schema.rs",
)

# We need to run this rule so we can build using Cargo
run_copy_to_workspace(
    name = "schema.update",
    origin = ":schema",
    tags = ["update"],
    target = "src/schema.rs",
)

rust_library(
    name = "finances_db",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["postgres"],
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    visibility = ["//visibility:public"],
    deps = all_crate_deps(
        normal = True,
    ),
)

rust_library(
    name = "finances_db/sqlite",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["sqlite"],
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    deps = all_crate_deps(
        normal = True,
    ),
)

# Unittests
rust_test(
    name = "tests",
    compile_data = [":migrations"],
    crate = ":finances_db/sqlite",
    crate_features = [
        "sqlite",
        "test_utils",
    ],
    deps = [
        "@crates_libraries//:anyhow",
        "@crates_libraries//:diesel_migrations",
        "@crates_libraries//:tempfile",
    ],
)

# Integration tests
rust_test_suite(
    name = "integration_tests",
    srcs = glob(["tests/**/test_*.rs"]),
    compile_data = [":migrations"],
    crate_features = ["sqlite"],
    deps = [":finances_db/sqlite"],
)

# Documentation
# FIXME: For everything related to docs, there is no way to activate a feature here
# rust_doc(
#     name = "doc",
#     crate = ":finances_db/sqlite",
#     # crate_features = ["postgres"],
#     visibility = ["//visibility:public"],
# )
#
# # Documentation - tests
# rust_doc_test(
#     name = "doc/tests-sqlite",
#     crate = ":finances_db/sqlite",
#     # crate_features = ["sqlite"],
#     # deps = deps + test_docs_deps,
# )

# rust_doc_test(
#     name = "doc/tests-postgres",
#     crate = ":finances_db/postgres",
#     # crate_features = ["postgres"],
#     # deps = deps + test_docs_deps,
# )
