[package]
name = "finances_db"
version = "0.0.1"
edition = "2021"

[lib]
name = "finances_db"
path = "src/lib.rs"

[features]
default = ["postgres"]
sqlite = ["diesel/returning_clauses_for_sqlite_3_35",]
postgres = ["dep:bigdecimal", "diesel/numeric", "diesel/postgres"]

[dependencies]
# diesel_utils = { path = "../../../libraries/diesel_utils" }
# utils = { path = "../../../libraries/utils", features = ["dates"] }

# anyhow = { workspace = true }
# async-trait = { workspace = true }
# camino = { workspace = true }
# camino-tempfile = { workspace = true }
# chrono = { workspace = true }
bigdecimal = {workspace = true, optional = true}
chrono = { workspace = true }
# clap = { workspace = true, features = ["derive", "env"] }
# clap-verbosity-flag = { workspace = true }
# data-encoding = { workspace = true }
diesel = { workspace = true, features = ["r2d2", "chrono"] }
# diesel_migrations = { workspace = true, features = ["sqlite"] }
dirs = { workspace = true }
# dotenvy = { workspace = true }
# flume = { workspace = true }
home = { workspace = true }
# ignore-files = { workspace = true }
# image = { workspace = true }
# kamadak-exif = { workspace = true }
# lazy_static = { workspace = true }
log = { workspace = true }
# oxipng = { workspace = true }
# ring = { workspace = true }
# serde = { workspace = true, features = ["derive"] }
# serde_json = { workspace = true }
# strum = { workspace = true, features = ["derive"] }
# strum_macros = { workspace = true }
# tempfile = { workspace = true }
# tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
# uuid = { version = "1.9.1", features = ["v4"] }

[dev-dependencies]
anyhow = { workspace = true }
diesel_migrations = { workspace = true }
tempfile = { workspace = true }
finances_db = { path = ".", default-features = false, features = ["sqlite"] }
