# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

# FIXME: Not sure if, for this project, I need this file. Why? Because I'm writing the `schema.rs` file myself manually, I'm
#        never executing the diesel-cli tool.

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]
