load("@aspect_rules_ts//ts:defs.bzl", "ts_config", "ts_project")
load("@npm//:vitest/package_json.bzl", vitest_bin = "bin")
load("@rules_rust//rust:defs.bzl", "rust_library")

exports_files(["Cargo.toml"])

###########
# Rust library
###########

rust_library(
    name = "googleapis/rust",
    srcs = glob(
        ["src-rust/**/*.rs"],
    ),
    crate_features = ["bazel"],
    crate_name = "googleapis",
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/googleapis/protos/google/type:protos_rs",
    ],
)

###########
# Javascript library
###########

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
)

ts_project(
    name = "googleapis/ts",
    srcs = glob(
        ["src-js/**/*.ts"],
        exclude = [
            "**/*.spec.ts",
            "**/*.test.ts",
        ],
    ) + ["package.json"],
    declaration = True,
    source_map = True,
    tsconfig = ":tsconfig",
    visibility = ["//visibility:public"],
    deps = [
        "//:node_modules/@types/node",
        "//:node_modules/decimal.js",
        "//libraries/googleapis/protos/google/type:protos_ts",
    ],
)

ts_project(
    name = "src_test_ts",
    srcs = glob([
        "src-js/**/*.spec.ts",
        # "src-js/**/*.test.ts",
    ]) + ["package.json"],
    declaration = True,
    source_map = True,
    tsconfig = ":tsconfig",
    deps = [
        ":googleapis/ts",
        "//:node_modules/vitest",
    ],
)

vitest_bin.vitest_test(
    name = "test.vitest",
    args = ["run"],
    chdir = package_name(),
    data = [
        "package.json",
        ":src_test_ts",
        "//:node_modules",  # TODO: Consume only the required deps
    ],
)
