load("@crates_libraries//:defs.bzl", "aliases", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary")
load("@totum//bazel/rust:defs.bzl", "rust_library_tests_and_docs")

rust_library_tests_and_docs(
    name = "syncronia_lib",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    all_features = {
        "cli": ["cli"],
        "test_utils": ["test_utils"],
    },
    crate_name = "syncronia",
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    deps = all_crate_deps(
        normal = True,
    ) + [
        "@totum//libraries/filesystem",
        "@totum//libraries/filesystem_pcloud",
        "@totum//libraries/pcloud_sdk",
    ],
)

rust_binary(
    name = "syncronia",
    srcs = glob(["src/cli/**/*.rs"]),
    crate_features = [
        "cli",
    ],
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    deps = all_crate_deps(
        normal = True,
    ) + [
        ":syncronia_lib",
        "@totum//libraries/filesystem",
        "@totum//libraries/filesystem_pcloud",
        "@totum//libraries/pcloud_sdk",
    ],
)
