load("@rules_rust//rust:defs.bzl", "rust_binary")
load("//bazel:value_from_stable_status.bzl", "value_from_stable_status")
load("//bazel/rust:defs.bzl", "rust_library_tests_and_docs")
load("//bazel/rust/docs:defs.bzl", "rust_docs")

exports_files(["Cargo.toml"])

value_from_stable_status(
    name = "version",
    default = module_name(),
    key = "STABLE_SYNCRONIA_VERSION",
    visibility = [":__subpackages__"],
)

rust_library_tests_and_docs(
    name = "syncronia_lib",
    srcs = glob(["src/**/*.rs"]),
    all_features = {
        "cli": ["cli"],
        "test_utils": ["test_utils"],
    },
    crate_name = "syncronia",
    deps = [
        "//bazel/third_party/crates:anyhow",
        "//bazel/third_party/crates:camino",
        "//bazel/third_party/crates:chrono",
        "//bazel/third_party/crates:chrono-tz",
        "//bazel/third_party/crates:clap",
        "//bazel/third_party/crates:diesel",
        "//bazel/third_party/crates:fs4",
        "//bazel/third_party/crates:ignore-files",
        "//bazel/third_party/crates:serde",
        "//bazel/third_party/crates:serde_yml",
        "//bazel/third_party/crates:thiserror",
        "//bazel/third_party/crates:tokio",
        "//bazel/third_party/crates:tracing",
        "//bazel/third_party/crates:tempfile",
        "//libraries/cron",
        "//libraries/filesystem",
        "//libraries/pcloud_sdk",
    ],
)

rust_binary(
    name = "syncronia",
    srcs = glob(["src/cli/**/*.rs"]),
    crate_features = [
        "cli",
    ],
    deps = [
        ":syncronia_lib",
        "//bazel/third_party/crates:anyhow",
        "//bazel/third_party/crates:camino",
        "//bazel/third_party/crates:chrono-tz",
        "//bazel/third_party/crates:clap",
        "//bazel/third_party/crates:clap-verbosity-flag",
        "//bazel/third_party/crates:home",
        "//bazel/third_party/crates:log",
        "//bazel/third_party/crates:thiserror",
        "//bazel/third_party/crates:tokio",
        "//bazel/third_party/crates:tracing",
        "//bazel/third_party/crates:tracing-subscriber",
        "//libraries/pcloud_sdk",
    ],
)

rust_docs(
    name = "docs",
    crates = [
        ":syncronia",
        ":syncronia_lib",
    ],
    visibility = ["//docs:__subpackages__"],
)
