[package]
name = "syncronia"
version = "0.1.0"
edition = "2021"

[features]
test_utils = []
cli = []

[dependencies]
pcloud_sdk = { path = "../../libraries/pcloud_sdk" }
filesystem = { path = "../../libraries/filesystem", features = ["diff", "local"] }
filesystem_pcloud = { path = "../../libraries/filesystem_pcloud" }

fs4 = { workspace = true }
confy = { workspace = true, default-features = false, features = ["yaml_conf"] }
camino = { workspace = true, features = ["serde1"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tracing = { workspace = true }
time = {workspace = true, features = [
    "serde",
    "parsing",
    "formatting",
    "macros",
] }
# tokio-cron-scheduler = { version = "0.8" }
cron-parser = {workspace = true }
chrono = { workspace = true, features = ["serde"] }
chrono-tz = { workspace = true }
tokio = { workspace = true, features = ["full"] }
anyhow = {workspace = true }
thiserror = {workspace = true }
ignore = {workspace = true}
async-trait = {workspace = true}
flume = {workspace = true}
sha256 = {workspace = true}
futures = {workspace = true}
async-std = {workspace = true}

# Optional dependencies
httpmock = { workspace = true }
tempfile = { workspace = true}

# Deps for CLI
clap = {workspace = true, features = ["derive"] }
clap-verbosity-flag = { workspace = true }
log = { workspace = true }
tracing-subscriber = { workspace = true}
home = {workspace = true }

[dev-dependencies]
tempfile = {workspace = true}
pcloud_sdk = { path = "../../libraries/pcloud_sdk", features = ["test_utils"] }
syncronia = { path = ".", features = ["test_utils"] }


[[bin]]
name = "scr"
path = "src/cli/main.rs"
# Waiting for https://github.com/rust-lang/rfcs/pull/3374
required-features = ["cli"]
