load("@rules_rust//rust:defs.bzl", "rust_binary")

rust_binary(
    name = "capture_args_and_env",
    srcs = ["capture_args_and_env.rs"],
    edition = "2018",
    visibility = ["//visibility:public"],
)

rust_binary(
    name = "run_scripts",
    srcs = ["run_scripts.rs"],
    edition = "2018",
    visibility = ["//visibility:public"],
)
