"""Provide `rust_docs` rule to build together the documentation for several crates"""

load("@rules_rust//rust/private:common.bzl", "rust_common")
load("@rules_rust//rust/private:rustdoc.bzl", "rustdoc_compile_action")
load("@rules_rust//rust/private:utils.bzl", "dedent", "find_toolchain")

def _zip_action(ctx, input_dir, output_zip, crate_label):
    """Creates an archive of the generated documentation from `rustdoc`

    FIXME: Copied from https://github.com/konkers/rules_rust/blob/bb060134fded62ef5f566fcf5eafaf0b86855db3/rust/private/rustdoc.bzl#L150,
    FIXME: I can't import it because it is a private function (starts with _)

    Args:
        ctx (ctx): The `rust_doc` rule's context object
        input_dir (File): A directory containing the outputs from rustdoc
        output_zip (File): The location of the output archive containing generated documentation
        crate_label (str): The label of the crate docs are being generated for.
    """
    args = ctx.actions.args()
    args.add(ctx.executable._zipper)
    args.add(output_zip)
    args.add(ctx.bin_dir.path)
    args.add_all([input_dir], expand_directories = True)
    ctx.actions.run(
        executable = ctx.executable._dir_zipper,
        inputs = [input_dir],
        outputs = [output_zip],
        arguments = [args],
        mnemonic = "RustdocZip",
        progress_message = "Creating RustdocZip for {}".format(crate_label),
        tools = [ctx.executable._zipper],
    )

def _rust_docs_impl(ctx):
    """The implementation of the `rust_docs` rule

    Args:
        ctx (ctx): The rule's context object
    """

    output_dir = ctx.actions.declare_directory("{}.rustdoc".format(ctx.label.name))

    rustdoc_scripts = []
    rustdoc_inputs = []

    for crate in ctx.attr.crates:
        crate_info = crate[rust_common.crate_info]

        # Add the current crate as an extern for the compile action
        rustdoc_flags = [
            "--extern",
            "{}={}".format(crate_info.name, crate_info.output.path),
        ]

        action = rustdoc_compile_action(
            ctx = ctx,
            toolchain = find_toolchain(ctx),
            crate_info = crate_info,
            output = output_dir,
            rustdoc_flags = rustdoc_flags,
        )

        arg_file = ctx.actions.declare_file("gendocs-{}.sh".format(crate.label.name))

        dump_args = ctx.actions.args()
        dump_args.add(action.executable)

        ctx.actions.run(
            mnemonic = "Args",
            progress_message = "Dumping args for {}".format(crate.label),
            outputs = [arg_file],
            executable = ctx.executable._capture_args_and_env,
            inputs = [],
            env = {"OUTPUT_FILE": arg_file.path} | action.env,
            arguments = [dump_args] + action.arguments,
        )

        rustdoc_scripts.append(arg_file)
        rustdoc_inputs += [action.inputs, depset([action.executable])]

    args = ctx.actions.args()
    for script in rustdoc_scripts:
        args.add(script)

    ctx.actions.run(
        mnemonic = "Rustdoc",
        progress_message = "Generating Rustdocs",
        outputs = [output_dir],
        executable = ctx.executable._run_scripts,
        inputs = depset(rustdoc_scripts, transitive = rustdoc_inputs),
        #env = action.env,
        arguments = [args],
        #tools = action.tools,
    )

    # This rule does nothing without a single-file output, though the directory should've sufficed.
    all_crates = ", ".join([crate.label.name for crate in ctx.attr.crates])
    _zip_action(ctx, output_dir, ctx.outputs.rust_doc_zip, all_crates)

    return [
        DefaultInfo(
            files = depset([output_dir]),
        ),
        OutputGroupInfo(
            rustdoc_dir = depset([output_dir]),
            rustdoc_zip = depset([ctx.outputs.rust_doc_zip]),
        ),
    ]

rust_docs = rule(
    doc = dedent("""\
    Generates code documentation for multiple crates.

    Example:
    Suppose you have the following directory structure for two Rust library crates:
    ```
    [workspace]/
        WORKSPACE
        BUILD
        hello_lib/
            BUILD
            src/
                lib.rs
        world_lib/
            BUILD
            src/
                lib.rs
    ```

    To build [`rustdoc`][rustdoc] documentation for the `hello_lib` and `world_lib` \
    crates, define a `rust_docs` rule that depends on the `hello_lib` and \
    `world_lib` `rust_library` targets:

    [rustdoc]: https://doc.rust-lang.org/book/documentation.html

    ```python
    package(default_visibility = ["//visibility:public"])
    load("@rules_rust//rust:defs.bzl", "rust_docs")
    rust_docs(
        name = "workspace_docs",
        crates = ["//hello_lib", "//world_lib"],
    )
    ```

    Running `bazel build //:workspace_docs` will build a zip file containing \
    the documentation for the `hello_lib` and `world_lib` library crates \
    generated by `rustdoc`.
    """),
    implementation = _rust_docs_impl,
    attrs = {
        "crates": attr.label_list(
            doc = (
                "A list of lablesThe label of the target to generate code documentation for.\n" +
                "\n" +
                "`rust_doc` can generate HTML code documentation for the source files of " +
                "`rust_library` or `rust_binary` targets."
            ),
            providers = [rust_common.crate_info],
            mandatory = True,
        ),
        "html_after_content": attr.label(
            doc = "File to add in `<body>`, after content.",
            allow_single_file = [".html", ".md"],
        ),
        "html_before_content": attr.label(
            doc = "File to add in `<body>`, before content.",
            allow_single_file = [".html", ".md"],
        ),
        "html_in_header": attr.label(
            doc = "File to add to `<head>`.",
            allow_single_file = [".html", ".md"],
        ),
        "markdown_css": attr.label_list(
            doc = "CSS files to include via `<link>` in a rendered Markdown file.",
            allow_files = [".css"],
        ),
        "rustc_flags": attr.string_list(
            doc = dedent("""\
                List of compiler flags passed to `rustc`.
                These strings are subject to Make variable expansion for predefined
                source/output path variables like `$location`, `$execpath`, and
                `$rootpath`. This expansion is useful if you wish to pass a generated
                file of arguments to rustc: `@$(location //package:target)`.
            """),
        ),
        "_cc_toolchain": attr.label(
            doc = "In order to use find_cpp_toolchain, you must define the '_cc_toolchain' attribute on your rule or aspect.",
            default = Label("@bazel_tools//tools/cpp:current_cc_toolchain"),
        ),
        "_dir_zipper": attr.label(
            doc = "A tool that orchestrates the creation of zip archives for rustdoc outputs.",
            default = Label("@rules_rust//util/dir_zipper"),
            cfg = "exec",
            executable = True,
        ),
        "_capture_args_and_env": attr.label(
            doc = "A tool for dumping arguments and env vars to a file",
            default = Label("//bazel/rust/docs:capture_args_and_env"),
            cfg = "exec",
            executable = True,
        ),
        "_process_wrapper": attr.label(
            doc = "A process wrapper for running rustdoc on all platforms",
            default = Label("@rules_rust//util/process_wrapper"),
            executable = True,
            allow_single_file = True,
            cfg = "exec",
        ),
        "_run_scripts": attr.label(
            doc = "A tool for running multiple scripts in the same action",
            default = Label("//bazel/rust/docs:run_scripts"),
            cfg = "exec",
            executable = True,
        ),
        "_zipper": attr.label(
            doc = "A Bazel provided tool for creating archives",
            default = Label("@bazel_tools//tools/zip:zipper"),
            cfg = "exec",
            executable = True,
        ),
    },
    fragments = ["cpp"],
    host_fragments = ["cpp"],
    outputs = {
        "rust_doc_zip": "%{name}.zip",
    },
    toolchains = [
        str(Label("@rules_rust//rust:toolchain_type")),
        "@bazel_tools//tools/cpp:toolchain_type",
    ],
    incompatible_use_toolchain_transition = True,
)
