use std::collections::HashMap;
use std::env;
use std::fs::File;
use std::io::{BufRead, BufReader};
use std::process::Command;

const ENVVAR_PREFIX: &str = "env: ";
const ENVVAR_SEPARATOR: &str = "=";

/// Parses the content of a file generated by [`capture_args_and_env`] script. This
/// function receives the lines and returns a tuple with the command (first argument
/// line), a map with the environment variables and a vector with the CLI arguments
fn parse_lines(lines: impl Iterator<Item = String>) -> (String, HashMap<String, String>, Vec<String>) {
    let (env, args_lines): (Vec<_>, Vec<_>) = lines.partition(|l| l.starts_with(ENVVAR_PREFIX));

    // Collect environment variables
    let env_vars: HashMap<String, String> = env
        .into_iter()
        .map(|e| {
            let (k, v) = e
                .strip_prefix(ENVVAR_PREFIX)
                .expect("doesn't start with prefix")
                .split_once(ENVVAR_SEPARATOR)
                .unwrap();
            (k.to_string(), v.to_string())
        })
        .collect();

    // First line of the file is the command to run.
    let mut args_lines_it = args_lines.iter();
    let command = args_lines_it
        .next()
        .ok_or_else(|| format!("no command in file"))
        .unwrap();

    // Subsequent lines are arguments.
    let args: Vec<String> = args_lines_it.into_iter().map(|l| l.to_string()).collect();

    (command.to_string(), env_vars, args)
}

// Simple utility to run commands from files.  Each command/command line
// argument in the file is on a separate line.
pub fn main() {
    // Skip the first arg (our executable path).
    let scripts = env::args().skip(1);

    for script in scripts {
        let script_file = BufReader::new(File::open(&script).expect("unable to open file"));
        let lines = script_file
            .lines()
            .map(|l| l.map_err(|e| format!("{script}: error reading line: {e}")).unwrap());

        let (command, env_vars, args) = parse_lines(lines.into_iter());

        // Run the command and wait for it to finish.
        let mut child = Command::new(&command)
            .args(args)
            .envs(&env_vars)
            .spawn()
            .map_err(|e| format!("{script}: failed to spawn child process {command}: {e}"))
            .unwrap();
        let status = child.wait().expect("");

        if !status.success() {
            panic!("{}: error running script: {}", script, status);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_file() {
        let (command, envvars, args) = parse_lines(
            vec![
                "env: k1=v1".to_string(),
                "env: k2=v2".to_string(),
                "mycommand".to_string(),
                "--args1=value1".to_string(),
                "--args2".to_string(),
            ]
            .into_iter(),
        );

        assert_eq!(command, "mycommand");
        assert_eq!(envvars.len(), 2);
        assert_eq!(envvars["k1"], "v1");
        assert_eq!(envvars["k2"], "v2");
        assert_eq!(args, vec!["--args1=value1", "--args2"]);
    }
}
