load("@rules_rust//rust:defs.bzl", "rust_proc_macro")

exports_files(["Cargo.toml"])

rust_proc_macro(
    name = "proto_wrapper_derive",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    visibility = ["//visibility:public"],
    deps = [
        "//bazel/third_party/crates:quote",
        "//bazel/third_party/crates:syn",
    ],
)
