load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "models",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob([
        "**/*.h",
        "**/*.hpp",
    ]),
    visibility = ["//apps/finances/qt:__subpackages__"],
    deps = [
        "//libraries/utils/cpp:integral_type",
        "//libraries/utils/cpp:string_type",
        "//libraries/utils/cpp/db",
        "//libraries/utils/cpp/libpqxx:date",
        "//libraries/utils/cpp/libpqxx:numeric",
        "@spdlog",
        "@tl-expected",
    ],
)
