load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "models",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob([
        "**/*.h",
        "**/*.hpp",
    ]),
    visibility = [
        "//apps/finances/qt:__subpackages__",
        "//libraries/finances/investments/cpp:__subpackages__",
    ],
    deps = [
        "//bazel/logging:spdlog",
        "//libraries/utils/cpp:integral_type",
        "//libraries/utils/cpp:string_type",
        "//libraries/utils/cpp/libpqxx:connection_pool",
        "//libraries/utils/cpp/libpqxx/datatypes:date",
        "//libraries/utils/cpp/libpqxx/datatypes:numeric",
        "@magic_enum",
        "@tl-expected",
    ],
)
