# Generated by Django 5.2 on 2025-11-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_repo_stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commit",
            name="reviewers",
            field=models.ManyToManyField(
                related_name="commit_reviewed_set", to="github_repo_stats.contributor"
            ),
        ),
    ]
