# Generated by Django 5.2 on 2025-11-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_repo_stats", "0002_alter_commit_reviewers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="commit",
            unique_together={("repo", "sha")},
        ),
        migrations.AlterUniqueTogether(
            name="repository",
            unique_together={("org", "name")},
        ),
    ]
