# Generated by Django 5.2 on 2025-11-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_repo_stats", "0003_alter_contributor_email_alter_commit_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commit",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
