# Generated by Django 5.2 on 2025-11-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github_repo_stats", "0004_alter_commit_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commit",
            name="reviewers",
        ),
        migrations.AddField(
            model_name="commit",
            name="changes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="commit",
            name="contributors",
            field=models.ManyToManyField(to="github_repo_stats.user"),
        ),
    ]
