load("@rules_rust//rust:defs.bzl", "rust_doc", "rust_doc_test", "rust_proc_macro", "rust_test")

exports_files(["Cargo.toml"])

rust_proc_macro(
    name = "constants",
    srcs = glob(["src/**/*.rs"]),
    visibility = ["//visibility:public"],
)

rust_test(
    name = "tests",
    crate = ":constants",
)

rust_doc(
    name = "doc",
    crate = ":constants",
    visibility = ["//libraries:__pkg__"],
)

rust_doc_test(
    name = "doc/test",
    crate = ":constants",
    visibility = ["//visibility:private"],
)
