load("@rules_rust//rust:defs.bzl", "rust_library")

exports_files(["Cargo.toml"])

rust_library(
    name = "proto_wrapper",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    crate_features = ["derive_macro"],
    proc_macro_deps = [
        "//libraries/utils/rust/proto_wrapper_derive",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//bazel/third_party/crates:prost",
    ],
)
