load("@aspect_bazel_lib//lib:expand_template.bzl", "expand_template")
load("//bazel:sh_with_runfiles_binary.bzl", "sh_with_runfiles_binary")
load("//bazel:value_from_stable_status.bzl", "value_from_stable_status")
load("//bazel/python/django/docker_compose:with_docker_compose_run.bzl", "with_docker_compose_run")
load("//bazel/run:defs.bzl", "run_together")

value_from_stable_status(
    name = "version",
    default = module_name(),
    key = "STABLE_FINANCES_VERSION",
    visibility = [":__subpackages__"],
)

# Development environment
# FIXME: This should probably be part of the actual docker-compose if we create Postgres inside docker
expand_template(
    name = "expose_postgresql",
    out = "expose_postgresql.yaml",
    tags = [
        "manual",
    ],
    template = [
        "services:",
        "  db:",
        "    ports:",
        "      - 5432",
        "",
    ],
)

# The backend requires a database (and the Django application to access the admin interface)
with_docker_compose_run(
    name = "backend",
    binaries = [
        "//apps/finances/tauri/src-tauri:app",
    ],
    docker_compose = [
        "//apps/finances/django:app-docker_compose",
        ":expose_postgresql",
    ],
    env = {
        "SECRET_KEY": "development-environment",
        # Create superuser
        "DJANGO_SUPERUSER_PASSWORD": "django",
        "DJANGO_SUPERUSER_USERNAME": "django",
        "DJANGO_SUPERUSER_EMAIL": "django@django.com",
        # Copy DB into the dev server ('host.docker.internal' is the host for the _external localhost_)
        "PRODUCTION_DATABASE_URL": "postgres://finances_ro:finances_ro@host.docker.internal:5433/finances",
        # Rust debugging
        "RUST_BACKTRACE": "1",
        "RUST_LOG": "debug",
        "OPENEXCHANGERATES_APIKEY": "empty",
    },
    remove_volumes = True,
)

# The frontend is just a regular Svelte application with SSR enabled
alias(
    name = "frontend",
    actual = "//apps/finances/tauri:devserver",
)

# To develop, we need to run the backend and the frontend
run_together(
    name = "dev",
    after = ":backend",
    before = ":frontend",
    delay_seconds = 1,
)

sh_with_runfiles_binary(
    name = "finances-app",
    tags = ["no-remote-cache"],
    tool = "//apps/finances/tauri/src-tauri:app",
    visibility = ["//apps/finances/installable:__subpackages__"],
)
