load("@aspect_bazel_lib//lib:expand_template.bzl", "expand_template")
load("//bazel:value_from_stable_status.bzl", "value_from_stable_status")
load("//bazel/containers/with_docker:with_docker_compose_run.bzl", "with_docker_compose_run")

value_from_stable_status(
    name = "version",
    default = module_name(),
    key = "STABLE_FINANCES_VERSION",
    visibility = [":__subpackages__"],
)

# Development environment
# FIXME: This should probably be part of the actual docker-compose if we create Postgres inside docker
expand_template(
    name = "expose_postgresql",
    out = "expose_postgresql.yaml",
    tags = [
        "manual",
    ],
    template = [
        "services:",
        "  db:",
        "    ports:",
        "      - 5431:5432",
        "",
    ],
)

with_docker_compose_run(
    name = "dev",
    binaries = [
        "//apps/finances/tauri:dev_sh",
    ],
    docker_compose = [
        "//apps/finances/django:app-docker_compose",
        ":expose_postgresql",
    ],
    env = {
        "SQL_DATABASE": "finances-dev",
        "SECRET_KEY": "development-environment",
        # Create superuser
        "DJANGO_SUPERUSER_PASSWORD": "django",
        "DJANGO_SUPERUSER_USERNAME": "django",
        "DJANGO_SUPERUSER_EMAIL": "django@django.com",
        # Migrate data from legacy DB ('host.docker.internal' is the host for the _external localhost_)
        "LEGACY_DATABASE_URL": "postgres://finances_ro:finances_ro@host.docker.internal:5432/finances",
    },
)
