
mod utils '../../just/utils.justfile'

cgreen := "\\033[1;32m"
creset := "\\033[0m"

tmpdir  := `mktemp -d`
prefix := "finances"
latest_tag := tmpdir / "latest-tag"
next_tag := tmpdir / "next-tag"

latest-tag: (utils::_latest-tag prefix latest_tag )

next-tag: (utils::_next-tag prefix next_tag )

# Runs finances app (Rust frontend) connecting (read-only) to production database
run:
    RUST_LOG=debug bazel run //apps/finances:finances-app


release: latest-tag next-tag utils::_gh_check_local_changes
    # GH: Create a tag (using "<date>[-<num>]"), use the tag to stamp the binaries
    bazel run --config=release --config=stamp //tools/gh -- release create $(cat {{ next_tag }}) --generate-notes --notes-start-tag $(cat {{ latest_tag }})
    git fetch --tags

    # Build the installable binary (after I have the right tag)
    bazel build --config=release --config=stamp //apps/finances/installable

    # GH: Release the installable (to Github)
    bazel run --config=release --config=stamp //apps/finances/installable:release

    @echo ""
    @echo "🎉 Execute the following to install the package:"
    @echo ""
    @echo "{{ cgreen }}sudo installer -pkg bazel-bin/apps/finances/installable/installable.pkg -target / -verboseR{{ creset }}"
    @echo ""
