load("@py_deps//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary")


py_binary(
    name = "admin",
    srcs = ["django_admin_wrapper.py"],
    main = "django_admin_wrapper.py",
    visibility = ["//visibility:public"],
    deps = [
        requirement("django"),
    ],
)
