"""A very opinionated Bazel macro to create the targets for a Django application"""

load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_library")
load("@py_deps//:requirements.bzl", "requirement")
load("//bazel/python/django:makemigrations.bzl", "django_makemigrations")
load("//bazel/python/django:test.bzl", "django_test")

def django_app(name, deps = None, visibility = None, app_label = None):
    """
    A very opinionated macro to create a Django application.

    This macro should be called from the root of the Django application and it
    will collect the following files:
    *

    Targets generated by this macro:
    *

    Args:
        name(str): The name of the application
        deps(list): A list of dependencies
        visibility: The visibility for the py_library
        app_label: Short name for the application
    """

    app_label = app_label or name

    native.filegroup(
        name = "{}/fixtures".format(name),
        srcs = native.glob(["fixtures/**/*.json"]),
    )

    native.filegroup(
        name = "{}/static".format(name),
        srcs = native.glob(["static/**/*.py"]),
    )

    native.filegroup(
        name = "{}/templates".format(name),
        srcs = native.glob(["templates/**/*.html"]),
    )

    deps = depset([requirement("django")] + (deps or [])).to_list()

    py_library(
        name = name,
        # Includes only the actual application files. Tests and management commands are not part of the library
        srcs = native.glob(
            ["**/*.py"],
            exclude = [
                "tests/**/*.*",
                "run_local.py",
            ],
        ),
        data = [
            ":{}/fixtures".format(name),
            ":{}/static".format(name),
            ":{}/templates".format(name),
        ],
        imports = ["../"],
        deps = deps,
        visibility = visibility,
    )

    # The "local" django-admin executable
    py_binary(
        name = "django-admin",
        srcs = ["run_local.py"],
        imports = ["."],
        main = "run_local.py",
        deps = [
            ":{}".format(name),
        ],
    )

    # The test target for this application
    django_test(
        name = "unittests",
        srcs = native.glob(["tests/**/*.py"]),  # Include the test files here
        test_label = "tests",
        django_admin_tool = ":django-admin",
    )

    # Add makemigrations
    django_makemigrations(
        name = "makemigrations",
        app_label = app_label,
        django_admin_tool = ":django-admin",
    )
