load("@py_deps//:requirements.bzl", "requirement")
load("//bazel/tools/pytest:defs.bzl", "pytest_test")

pytest_test(
    name = "tests",
    srcs = glob(["**/*.py"]),
    data = [
        "//apps/finances/django:app-docker_compose",
        "//apps/finances/django:app-tarball",
        "//bazel/python/django/containers/nginx:nginx-tarball",
    ],
    tags = [
        "requires-docker",
        "requires-network",
    ],
    deps = [
        requirement("testcontainers"),
    ],
)
