load("@aspect_rules_swc//swc:defs.bzl", "swc")
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@bazel_skylib//lib:partial.bzl", "partial")
load("@npm//:defs.bzl", "npm_link_all_packages")

npm_link_all_packages(name = "node_modules")

# load("@npm//apps/lego-db:@tauri-apps/cli_bzl_library")

ts_project(
    name = "ts",
    srcs = glob(["src/**/*.ts"]),
    # See the /ts_project_transpiler example for more detail
    transpiler = partial.make(
        swc,
        swcrc = {
            "module": {
                "type": "commonjs",
            },
        },
    ),
    tsconfig = {
        "compilerOptions": {
            "declaration": True,
        },
    },
    deps = [
        ":node_modules",
    ],
)
