# Generated by Django 5.1.2 on 2024-10-29 18:08

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        help_text="Official account identifier",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "ccy",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "Euro"), ("USD", "US Dollar")], default="EUR", max_length=3
                    ),
                ),
                (
                    "open",
                    models.DateField(
                        help_text="Date when this account was opened. All movements related to this account should happen after this data (and before close date)"
                    ),
                ),
                (
                    "close",
                    models.DateField(
                        blank=True,
                        help_text="Date when this account was closed. No more movements are allowed for this account",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountHolder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "is_company",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the holder is a company or a physical person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Custodian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        help_text="Country where this custodian runs its business", max_length=2
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fx",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "foreign",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "Euro"), ("USD", "US Dollar")],
                        default=None,
                        help_text="Foreign (quoted) currency",
                        max_length=3,
                    ),
                ),
                (
                    "local",
                    djmoney.models.fields.CurrencyField(
                        choices=[("EUR", "Euro"), ("USD", "US Dollar")],
                        default="EUR",
                        help_text="Local currency (FX is quoted as local/foreign)",
                        max_length=3,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="How many 'foreign' you need to take a 'local'",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Rate should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
                ("date_value", models.DateField(help_text="Date when this FX was observed")),
            ],
            options={
                "ordering": ["-date_value"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransactionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("once", "Once in a lifetime"),
                            ("year", "Every year"),
                            ("month", "Every month"),
                            ("quarter", "Every quarter"),
                        ],
                        default="once",
                        help_text="How often this same transaction group is rescheduled",
                        max_length=10,
                    ),
                ),
                (
                    "start",
                    models.DateField(
                        help_text="For recurring groups, this will be the base date to compute the cadence. For non recurring events, this is just the date of the single occurrence"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountHolderRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "owns_money",
                    models.BooleanField(
                        default=True,
                        help_text="This person will also be the owner of the money it contains. Furthermore, if there are any debt due to having taken out a loan, this person will be liable for the tax obligations",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finances_accounts.account"
                    ),
                ),
                (
                    "holder",
                    models.ForeignKey(
                        help_text="Person designated and authorized to transact business on behalf of an account",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances_accounts.accountholder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="holders",
            field=models.ManyToManyField(
                through="finances_accounts.AccountHolderRole", to="finances_accounts.accountholder"
            ),
        ),
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tn_ancestors_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Ancestors pks"
                    ),
                ),
                (
                    "tn_ancestors_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Ancestors count"
                    ),
                ),
                (
                    "tn_children_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Children pks"
                    ),
                ),
                (
                    "tn_children_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Children count"
                    ),
                ),
                (
                    "tn_depth",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Depth",
                    ),
                ),
                (
                    "tn_descendants_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Descendants pks"
                    ),
                ),
                (
                    "tn_descendants_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Descendants count"
                    ),
                ),
                (
                    "tn_index",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Index"),
                ),
                (
                    "tn_level",
                    models.PositiveIntegerField(
                        default=1,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Level",
                    ),
                ),
                (
                    "tn_priority",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999999999),
                        ],
                        verbose_name="Priority",
                    ),
                ),
                (
                    "tn_order",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Order"),
                ),
                (
                    "tn_siblings_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Siblings pks"
                    ),
                ),
                (
                    "tn_siblings_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Siblings count"
                    ),
                ),
                ("name", models.CharField(help_text="Name of the element", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A description of the element", null=True
                    ),
                ),
                (
                    "is_abstract",
                    models.BooleanField(
                        default=False, help_text="If the category can be instantiated or not"
                    ),
                ),
                (
                    "tn_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tn_children",
                        to="finances_accounts.accounttype",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "ordering": ["tn_order"],
                "abstract": False,
                "unique_together": {("tn_parent", "name")},
            },
        ),
        migrations.AddField(
            model_name="account",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="finances_accounts.accounttype"
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="custodian",
            field=models.ForeignKey(
                help_text="The entity that has physical possession of its clients' financial assets",
                on_delete=django.db.models.deletion.PROTECT,
                to="finances_accounts.custodian",
            ),
        ),
        migrations.CreateModel(
            name="MovementType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tn_ancestors_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Ancestors pks"
                    ),
                ),
                (
                    "tn_ancestors_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Ancestors count"
                    ),
                ),
                (
                    "tn_children_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Children pks"
                    ),
                ),
                (
                    "tn_children_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Children count"
                    ),
                ),
                (
                    "tn_depth",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Depth",
                    ),
                ),
                (
                    "tn_descendants_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Descendants pks"
                    ),
                ),
                (
                    "tn_descendants_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Descendants count"
                    ),
                ),
                (
                    "tn_index",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Index"),
                ),
                (
                    "tn_level",
                    models.PositiveIntegerField(
                        default=1,
                        editable=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Level",
                    ),
                ),
                (
                    "tn_priority",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(9999999999),
                        ],
                        verbose_name="Priority",
                    ),
                ),
                (
                    "tn_order",
                    models.PositiveIntegerField(default=0, editable=False, verbose_name="Order"),
                ),
                (
                    "tn_siblings_pks",
                    models.TextField(
                        blank=True, default="", editable=False, verbose_name="Siblings pks"
                    ),
                ),
                (
                    "tn_siblings_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="Siblings count"
                    ),
                ),
                ("name", models.CharField(help_text="Name of the element", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A description of the element", null=True
                    ),
                ),
                (
                    "is_abstract",
                    models.BooleanField(
                        default=False, help_text="If the category can be instantiated or not"
                    ),
                ),
                (
                    "tn_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tn_children",
                        to="finances_accounts.movementtype",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "ordering": ["tn_order"],
                "abstract": False,
                "unique_together": {("tn_parent", "name")},
            },
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount in object's currency",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Amount should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
                (
                    "direction",
                    models.IntegerField(
                        choices=[(0, "IN"), (1, "OUT")],
                        help_text="Whether the movement substracts an amount from the related account (OUT) or increases it (IN)",
                    ),
                ),
                (
                    "date_value",
                    models.DateField(
                        help_text="Date when the movement is annotated in the associated account"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finances_accounts.account"
                    ),
                ),
                (
                    "fx",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is the FX used for this movement (it doesn't need to be exactly the same as the official one for this 'date_value', as FX varies along the day)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finances_accounts.fx",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finances_accounts.movementtype",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="Every movement is associated to a transaction, the transaction contains its counterparts",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances_accounts.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_value"],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="group",
            field=models.ForeignKey(
                blank=True,
                help_text="Which group (if any) this transaction belongs to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finances_accounts.transactiongroup",
            ),
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount in object's currency",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Amount should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
                (
                    "date_value",
                    models.DateField(
                        help_text="Date corresponding to this snapshot. It should be a working day, so the FX can be retrieved from official sources"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account this snapshot refers to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finances_accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_value"],
                "abstract": False,
                "unique_together": {("account", "date_value")},
            },
        ),
    ]
