# Generated by Django 5.1.2 on 2024-10-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttype",
            name="unique_name",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="A unique name for this element. Machine readable.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="movementtype",
            name="unique_name",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="A unique name for this element. Machine readable.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
