# Generated by Django 5.1.2 on 2024-10-25 16:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movementdividend",
            options={},
        ),
        migrations.AlterModelOptions(
            name="movementnonnumerable",
            options={},
        ),
        migrations.AlterModelOptions(
            name="movementnumerable",
            options={},
        ),
        migrations.RemoveField(
            model_name="movementdividend",
            name="account",
        ),
        migrations.RemoveField(
            model_name="movementdividend",
            name="date_value",
        ),
        migrations.RemoveField(
            model_name="movementdividend",
            name="direction",
        ),
        migrations.RemoveField(
            model_name="movementdividend",
            name="fx",
        ),
        migrations.RemoveField(
            model_name="movementdividend",
            name="id",
        ),
        migrations.RemoveField(
            model_name="movementdividend",
            name="transaction",
        ),
        migrations.RemoveField(
            model_name="movementdividend",
            name="type",
        ),
        migrations.RemoveField(
            model_name="movementnonnumerable",
            name="account",
        ),
        migrations.RemoveField(
            model_name="movementnonnumerable",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="movementnonnumerable",
            name="date_value",
        ),
        migrations.RemoveField(
            model_name="movementnonnumerable",
            name="direction",
        ),
        migrations.RemoveField(
            model_name="movementnonnumerable",
            name="fx",
        ),
        migrations.RemoveField(
            model_name="movementnonnumerable",
            name="id",
        ),
        migrations.RemoveField(
            model_name="movementnonnumerable",
            name="transaction",
        ),
        migrations.RemoveField(
            model_name="movementnonnumerable",
            name="type",
        ),
        migrations.RemoveField(
            model_name="movementnumerable",
            name="account",
        ),
        migrations.RemoveField(
            model_name="movementnumerable",
            name="date_value",
        ),
        migrations.RemoveField(
            model_name="movementnumerable",
            name="direction",
        ),
        migrations.RemoveField(
            model_name="movementnumerable",
            name="fx",
        ),
        migrations.RemoveField(
            model_name="movementnumerable",
            name="id",
        ),
        migrations.RemoveField(
            model_name="movementnumerable",
            name="transaction",
        ),
        migrations.RemoveField(
            model_name="movementnumerable",
            name="type",
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "direction",
                    models.IntegerField(
                        choices=[(0, "IN"), (1, "OUT")],
                        help_text="Whether the movement substracts an amount from the related account (OUT) or increases it (IN)",
                    ),
                ),
                (
                    "date_value",
                    models.DateField(
                        help_text="Date when the movement is annotated in the associated account"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount in object's currency",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Amount should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="finances_accounts.account"
                    ),
                ),
                (
                    "fx",
                    models.ForeignKey(
                        blank=True,
                        help_text="This is the FX used for this movement (it doesn't need to be exactly the same as the official one for this 'date_value', as FX varies along the day)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finances_accounts.fx",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        help_text="Every movement is associated to a transaction, the transaction contains its counterparts",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finances_accounts.transaction",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finances_accounts.movementtype",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_value"],
            },
        ),
        migrations.AddField(
            model_name="movementdividend",
            name="movement_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="finances_accounts.movement",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movementnonnumerable",
            name="movement_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="finances_accounts.movement",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movementnumerable",
            name="movement_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="finances_accounts.movement",
            ),
            preserve_default=False,
        ),
    ]
