# Generated by Django 5.1.2 on 2024-10-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances_accounts", "0002_alter_movementdividend_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movementnumerable",
            name="movement_ptr",
        ),
        migrations.AlterUniqueTogether(
            name="snapshotnumerable",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="snapshotnumerable",
            name="account",
        ),
        migrations.RemoveField(
            model_name="accounttype",
            name="is_numerable",
        ),
        migrations.DeleteModel(
            name="MovementDividend",
        ),
        migrations.DeleteModel(
            name="MovementNumerable",
        ),
        migrations.DeleteModel(
            name="SnapshotNumerable",
        ),
    ]
