# Generated by Django 5.1.2 on 2024-10-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances_accounts", "0003_remove_movementnumerable_movement_ptr_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="snapshotnonnumerable",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="snapshotnonnumerable",
            name="account",
        ),
        migrations.DeleteModel(
            name="MovementNonNumerable",
        ),
        migrations.DeleteModel(
            name="SnapshotNonNumerable",
        ),
    ]
