# Generated by Django 5.1.2 on 2024-10-28 15:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances_accounts", "0004_alter_snapshotnonnumerable_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount in object's currency",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Amount should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
                (
                    "date_value",
                    models.DateField(
                        help_text="Date corresponding to this snapshot. It should be a working day, so the FX can be retrieved from official sources"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account this snapshot refers to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finances_accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_value"],
                "unique_together": {("account", "date_value")},
            },
        ),
    ]
