# Generated by Django 5.1.2 on 2024-11-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances_accounts", "0006_data_movementtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_numerable",
            field=models.BooleanField(
                default=False,
                help_text="We can only know at an account level if it is numerable or not. Of course there are some AccountType that will always be numerable (Real State, Stocks,...) but sometimes even some investments that could be numerable are not (i.e: an investment fund or pension plan that invest in many different assets)",
            ),
        ),
    ]
