# Generated by Django 5.1.2 on 2024-10-29 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances_accounts", "0006_alter_movement_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount in object's currency",
                max_digits=14,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "Amount should be equal or greater than 0"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="snapshot",
            name="amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount in object's currency",
                max_digits=14,
                validators=[
                    django.core.validators.MinValueValidator(
                        0, "Amount should be equal or greater than 0"
                    )
                ],
            ),
        ),
    ]
