# Generated by Django 5.1.2 on 2024-11-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances_accounts", "0008_alter_movement_amount_alter_snapshot_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountholder",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="custodian",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="transactiongroup",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="accountholder",
            name="photo",
            field=models.FileField(blank=True, null=True, upload_to="holders"),
        ),
        migrations.AddField(
            model_name="custodian",
            name="photo",
            field=models.FileField(blank=True, null=True, upload_to="custodians"),
        ),
    ]
