# Generated by Django 5.1.2 on 2024-12-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances_accounts", "0009_alter_accountholder_options_alter_custodian_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactiongroup",
            name="end",
            field=models.DateField(
                blank=True,
                help_text="Recurring and non recurring groups can have a finish data. After it they won't be listed when creating other transactions",
                null=True,
            ),
        ),
    ]
