# Generated by Django 5.2 on 2025-05-10 16:12

from django.conf import settings
from django.db import migrations
from django.utils.translation import gettext_lazy as _
from django_finances_accounts.constants import MovementTypeConstants


def populate_movementtypes(apps, schema_editor):
    MovementType = apps.get_model("finances_accounts", "MovementType")

    impuestos_indirectos = MovementType.objects.get(
        unique_name=MovementTypeConstants.INDIRECT_TAXES
    )
    impuestos_indirectos_spain = MovementType.objects.get(
        tn_parent=impuestos_indirectos, name=_("España")
    )
    iva = MovementType.objects.get(tn_parent=impuestos_indirectos_spain, name=_("IVA"))

    MovementType.objects.bulk_create(
        [
            MovementType(
                tn_parent=iva,
                name=_("2% (RDL 4/2024)"),
                description=_(
                    "Desde 01/10/2024 los que tributaban al 0% pasan a tributar (temporalmente) al 2%"
                ),
            ),
            MovementType(
                tn_parent=iva,
                name=_("7.50% (RDL 4/2024)"),
                description=_("Desde 01/10/2024 para pastas alimenticias y aceites de semilla"),
            ),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("finances_accounts", "0010_transactiongroup_end"),
    ]

    operations = [
        migrations.RunPython(populate_movementtypes),
    ]
