# Generated by Django 5.2 on 2025-09-10 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances_accounts", "0011_data_movementtype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["custodian", "name"]},
        ),
    ]
