# TODO: Collect all documentation targets from libraries here, make it possible to spawn a static webserver for them. See https://github.com/bazelbuild/rules_rust/issues/472

load("@totum//bazel/rust/docs:defs.bzl", "rust_docs")

ALL_LIBRARIES = [
    "constants",
    "cron",
    "diesel_utils",
    "filesystem",
    "http_utils",
    "pcloud_sdk",
    "rebrickable",
    "utils",
]

rust_docs(
    name = "docs",
    crates = ["//libraries/{}".format(it) for it in ALL_LIBRARIES],
    visibility = ["//docs:__subpackages__"],
)
