# TODO: Collect all documentation targets from libraries here, make it possible to spawn a static webserver for them. See https://github.com/bazelbuild/rules_rust/issues/472

load("//bazel/rust/docs:defs.bzl", "rust_docs")

ALL_LIBRARIES = [
    "conductus",
    "constants",
    "cron",
    "diesel_utils",
    "filesystem",
    # "finances/accounts/rust:finances_accounts",
    # "finances/investments/rust:finances_investments",
    # "googleapis:googleapis/rust",
    "openexchangerates",
    "pcloud_sdk",
    "rebrickable",
    "utils/rust/proto_wrapper",
    "utils/rust/proto_wrapper_derive",
    "utils/rust/utils",
]

rust_docs(
    name = "docs",
    crates = ["//libraries/{}".format(it) for it in ALL_LIBRARIES],
    visibility = ["//docs:__subpackages__"],
)
