load("@rules_qt//qt:qt_cc_library.bzl", "qt_cc_library")

qt_cc_library(
    name = "interface",
    srcs = ["account_detail.cpp"],
    hdrs = ["account_detail.h"],
    visibility = ["//apps/finances/qt/widgets/accounts:__subpackages__"],
    deps = [
        "//apps/finances/qt/metatypes",
        "//apps/finances/qt/models",
        "@rules_qt//:qt_widgets",
    ],
)

qt_cc_library(
    name = "widgets",
    srcs = [
        "accounts_table.cpp",
        "accounts_table_filter.cpp",
        "main_tab.cpp",
    ],
    hdrs = [
        "accounts_table.h",
        "accounts_table_filter.h",
        "main_tab.h",
    ],
    visibility = ["//apps/finances/qt:__subpackages__"],
    deps = [
        "//apps/finances/qt/table_models",
        "//apps/finances/qt/tables",
        "//apps/finances/qt/widgets/accounts/non_numerable:widgets",
        "//apps/finances/qt/widgets/accounts/numerable:widgets",
        "//bazel/logging:spdlog",
        "@rules_qt//:qt_widgets",
    ],
)
