
load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "accounts",
    srcs = [
        "model.cpp",
    ],
    hdrs = [
        "model.h",
    ],
    visibility = ["//apps/finances/qt:__subpackages__"],
    deps = [
        "//libraries/finances/accounts/cpp/models",
        "//libraries/utils/cpp/qt/models",
        "@magic_enum",
        "@rules_qt//:qt_core",
        "@rules_qt//:qt_gui",
    ],
)
