load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_proto_grpc_cpp//:defs.bzl", "cpp_grpc_library")

# exports_files(
#     [
#         "common.proto",
#         "management_service.proto",
#         "semantic_graph_access_service.proto",
#     ],
#     visibility = ["//visibility:public"],
# )

proto_library(
    name = "cli_service_proto",
    srcs = ["cli_service.proto"],
    # strip_import_prefix = "/sysconfig/server/protocol/schemas",
    visibility = ["//visibility:public"],
    deps = [
        # ":common_proto",
        "@protobuf//:empty_proto",
    ],
)

cpp_grpc_library(
    name = "cli_service_proto_cpp",
    # include_prefix = "system_config/server/protocol",
    protos = [
        ":cli_service_proto",
    ],
    # strip_include_prefix = "management_service_proto_cpp_pb",
    # deps = [":common_proto_cpp"],
)

cc_library(
    name = "protocol_lib",
    # visibility = ["//visibility:public"],
    deps = [
        ":cli_service_proto_cpp",
    ],
)
