
# Runs board_games/database app (Django backend) using a temporary PostgreSQL with some test data
database-devserver:
    (sleep 10 ; open http://127.0.0.1:8000/admin) &
    bazel run //apps/board_games/database:devserver
