[package]
name = "pcloud-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcloud-sdk = { path = "../sdk" }
# indicatif = { version = "0.17"}
home = "0.5.4"
tokio = { version = "1.21", features = ["full"] }
clap = { version = "4.0", features = ["derive"] }
#clap-verbosity-flag = { version = "1.0" }
