load("@py_deps//:requirements.bzl", "requirement")
load("//bazel/containers/with_docker:with_postgres_run.bzl", "with_postgres_run")
load("//bazel/python/django/app:django_app.bzl", "django_app")
load("//bazel/rust/diesel:print_schema.bzl", "diesel_print_schema")

django_app(
    name = "finances_accounts",
    visibility = ["//visibility:public"],
    deps = [
        requirement("django-treenode"),
        requirement("django-money"),
        requirement("django-countries"),
        requirement("django-appconf"),
    ],
)

# genrule(
#     name = "migrate_postgres",
#     outs = ["migrate.sh"],
#     cmd_bash = """
#         echo 'export \"SQL_ENGINE=django.db.backends.postgresql\"' > $@
#         echo 'export \"SQL_DATABASE=$$POSTGRES_DB\"' >> $@
#         echo 'export \"SQL_USER=$$POSTGRES_USER\"' >> $@
#         echo 'export \"SQL_PASSWORD=$$POSTGRES_PASSWORD\"' >> $@
#         echo 'export \"SQL_HOST=$$POSTGRES_HOST\"' >> $@
#         echo 'export \"SQL_PORT=$$POSTGRES_PORT\"' >> $@
#         echo '$(rootpath :django-admin) migrate' >> $@
#     """,
#     executable = True,
#     tools = [
#         ":django-admin",
#     ],
# )

diesel_print_schema(
    name = "diesel_print_schema",
    schema = "src/schema.postgres.rs",
)

with_postgres_run(
    name = "diesel_schema_postgres",
    # First migrate,then print the schema
    binaries = [
        ":migrate",
        ":diesel_print_schema",
    ],
    env = {
        "SQL_ENGINE": "django.db.backends.postgresql",
    },
    env_transpose = {
        "SQL_DATABASE": "POSTGRES_DB",
        "SQL_USER": "POSTGRES_USER",
        "SQL_PASSWORD": "POSTGRES_PASSWORD",
        "SQL_HOST": "POSTGRES_HOST",
        "SQL_PORT": "POSTGRES_PORT",
    },
    postgres_image_tag = "17",
)

#   - SQL_ENGINE=django.db.backends.postgresql
#   - SQL_DATABASE=${SQL_DATABASE:-hello_django_dev}
#   - SQL_USER=${SQL_USER:-hello_django}
#   - SQL_PASSWORD=${SQL_PASSWORD:-hello_django}
#   - SQL_HOST=db
#   - SQL_PORT=5432

# "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
# "NAME": os.environ.get("SQL_DATABASE", BASE_DIR / "db.sqlite3"),
# "USER": os.environ.get("SQL_USER", "user"),
# "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
# "HOST": os.environ.get("SQL_HOST", "localhost"),
# "PORT": os.environ.get("SQL_PORT", "5432"),

# genrule(
#     name = "diesel_print_schema",
#     outs = ["diesel_print_schema.sh"],
#     cmd_bash = """
#         echo 'export \"SQL_ENGINE=django.db.backends.postgresql\"' > $@
#         echo 'export \"SQL_DATABASE=$$POSTGRES_DB\"' >> $@
#         echo 'export \"SQL_USER=$$POSTGRES_USER\"' >> $@
#         echo 'export \"SQL_PASSWORD=$$POSTGRES_PASSWORD\"' >> $@
#         echo 'export \"SQL_HOST=$$POSTGRES_HOST\"' >> $@
#         echo 'export \"SQL_PORT=$$POSTGRES_PORT\"' >> $@
#         echo '$(location @diesel_cli) print-schema --help' >> $@
#     """,
#     executable = True,
#     tools = [
#         "@diesel_cli",
#     ],
# )

# sh_binary(
#     name = "diesel_print_schema",
#     outs = ["schema.rs"],
#     cmd = "ls -la"
# )

# filegroup(
#     name = "diesel_config",
#     srcs = ["diesel.toml"],
#     tags = [
#         "manual",
#     ],
# )

# with_docker_compose_run(
#     name = "schema_gen",
#     cmd = "./$(rootpath @diesel_cli//:diesel_cli) print-schema --database-url postgres://diesel-schema:diesel-schema@127.0.0.1:5431/diesel-schema > $BUILD_WORKSPACE_DIRECTORY/apps/finances/desktop/src/schema.postgres.rs",
#     docker_compose = [
#         "//apps/finances/django:app-docker_compose",
#         ":expose_postgresql",
#     ],
#     docker_services = [
#         "web",
#         "db",
#     ],
#     env = {
#         "SECRET_KEY": "not-for-production",
#         "SQL_USER": "diesel-schema",
#         "SQL_DATABASE": "diesel-schema",
#         "SQL_PASSWORD": "diesel-schema",
#     },
#     tags = [
#         "update",
#     ],
#     tools = ["@diesel_cli"],
# )
