load("@crates_libraries//:defs.bzl", "aliases", "all_crate_deps")
load("@totum//bazel/rust:defs.bzl", "rust_library_tests_and_docs")

rust_library_tests_and_docs(
    name = "filesystem",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    all_features = {
        "diff": ["diff"],
        "local": ["local"],
        "local_temp": [
            "local_temp",
            "local",
        ],
        "pcloud": ["pcloud"],
        "test_utils": ["test_utils"],
    },
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    test_deps = [
        "@crates_libraries//:anyhow",
        "@crates_libraries//:headers",
    ],
    test_suite_deps = [
        "@crates_libraries//:anyhow",
    ],
    deps = all_crate_deps(
        normal = True,
    ) + [
        "@totum//libraries/pcloud_sdk",
        "@totum//libraries/utils",
    ],
)
