load("@crates_libraries//:defs.bzl", "aliases", "all_crate_deps")
load("//bazel/rust:defs.bzl", "rust_library_tests_and_docs")
load("//bazel/rust/diesel:diesel_print_schema.bzl", "diesel_print_schema")
load("//bazel/rust/diesel:diesel_setup.bzl", "diesel_setup")

rust_library_tests_and_docs(
    name = "filesystem",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    all_features = {
        "local": ["local"],
        "diesel_indexed_impl": ["diesel_indexed_impl"],
        "local_temp": [
            "local_temp",
            "local",
        ],
        "pcloud": ["pcloud"],
        "test_utils": ["test_utils"],
    },
    compile_data = [":migrations"],
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    test_data = [
        "//libraries/pcloud_sdk:test_data",
    ],
    test_deps = [
        "@crates_libraries//:anyhow",
        "@crates_libraries//:headers",
    ],
    test_suite_deps = [
        "@crates_libraries//:anyhow",
    ],
    deps = all_crate_deps(
        normal = True,
    ) + [
        "//libraries/diesel_utils",
        "//libraries/pcloud_sdk",
        "//libraries/utils",
        "@crates_libraries//:diesel",
        "@crates_libraries//:diesel_migrations",
    ],
)

# For the diesel FilesystemIndexedDB implementation
filegroup(
    name = "diesel_config",
    srcs = ["diesel.toml"],
)

filegroup(
    name = "migrations",
    srcs = glob(["src/impls/composites/indexed/diesel_indexed/migrations/**/*.sql"]),
    visibility = ["//visibility:public"],
)

diesel_setup(
    name = "setup",
    config_file = ":diesel_config",
    database_url = "db.sqlite3",
    migrations = [":migrations"],
)

diesel_print_schema(
    name = "schema",
    config_file = ":diesel_config",
    database_url = ":setup",
    target = "src/impls/composites/indexed/diesel_indexed/schema.rs",
)
