[package]
name = "filesystem"
version = "0.1.0"
edition = "2021"

[features]
diff = []
local = ["dep:async-std", "dep:ignore", "dep:futures", "dep:sha256"]
test_utils = ["local", "dep:tempfile"]

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
camino = { workspace = true }
flume = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

# Optional dependencies
async-std = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
ignore = { workspace = true, optional = true }
sha256 = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }

[dev-dependencies]
filesystem = { path = ".", features = ["test_utils", "diff"] }
