[package]
name = "filesystem"
version = "0.1.0"
edition = "2021"

[features]
diff = []
local = ["dep:async-std", "dep:ignore", "dep:futures", "dep:sha256"]
local_temp = ["dep:uuid", "dep:tempfile", "local"]

[dependencies]
async-trait = { workspace = true }
camino = { workspace = true }
flume = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

# Optional dependencies
async-std = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
ignore = { workspace = true, optional = true }
sha256 = { workspace = true, optional = true }
tempfile = { workspace = true, optional = true }
uuid = { workspace = true, optional = true, features = ["v4"] }

[dev-dependencies]
filesystem = { path = ".", features = ["local_temp", "diff"] }
