# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
# file = "src/impls/composites/diesel_indexed/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId"]

[migrations_directory]
dir = "src/impls/composites/indexed/diesel_indexed/migrations"
