FROM ubuntu:26.04

# Install dependencies (for Bazel)
RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    git \
    jq \
    bash \
    sudo \
    unzip \
    wget \
    default-jdk

# Install Docker and Docker compose plugin (using Docker's official GPG key):
RUN install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc \
    && chmod a+r /etc/apt/keyrings/docker.asc \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null \
    && apt-get update \
    && apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin


# Install GH CLI
RUN mkdir -p -m 755 /etc/apt/keyrings \
    && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    && cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
    && chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && apt update \
    && apt install -y gh

# Install dependencies:
# * Tauri v2: https://v2.tauri.app/start/prerequisites/#linux
# * Postgresql: library + client
RUN apt-get install -y \
    libwebkit2gtk-4.1-dev \
    build-essential \
    curl \
    wget \
    file \
    libxdo-dev \
    libssl-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev \
    libpq-dev \
    postgresql-client

RUN rm -rf /var/lib/apt/lists/*

# Install bazelisk
RUN wget https://github.com/bazelbuild/bazelisk/releases/download/v1.25.0/bazelisk-linux-amd64 && \
    chmod +x bazelisk-linux-amd64 && \
    mv bazelisk-linux-amd64 /usr/local/bin/bazel

# # Create a non-root user and add to docker group
ARG RUNNER_USER=myuser
ARG USER_UID=1000
ARG USER_GID=1000

RUN groupadd -g $USER_GID $RUNNER_USER && \
    useradd -m -u $USER_UID -g $USER_GID -s /bin/bash $RUNNER_USER && \
    echo "$RUNNER_USER ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers


ENV RUNNER_WORKDIR=/home/runner/actions-runner
RUN mkdir -p $RUNNER_WORKDIR && chown -R $RUNNER_USER:$RUNNER_USER $RUNNER_WORKDIR
WORKDIR $RUNNER_WORKDIR
USER $RUNNER_USER

# Download and extract the GitHub Actions Runner
RUN curl -o actions-runner-linux-x64-2.322.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.322.0/actions-runner-linux-x64-2.322.0.tar.gz && \
    echo "b13b784808359f31bc79b08a191f5f83757852957dd8fe3dbfcc38202ccf5768  actions-runner-linux-x64-2.322.0.tar.gz" | shasum -a 256 -c && \
    tar xzf ./actions-runner-linux-x64-2.322.0.tar.gz && \
    rm actions-runner-linux-x64-2.322.0.tar.gz

# Copy entrypoint script
COPY entrypoint.sh /entrypoint.sh
COPY runner.sh /runner.sh
# RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
