load("//apps/finances/installable:defs.bzl", "ALL_FOLDERS", "DJANGO_ADMIN_APP", "NAME")
load("//bazel/scripts/django:django_command.bzl", "django_command")
load("//bazel/scripts/envfile:combine_envfiles.bzl", "combine_envfiles")
load("//bazel/scripts/envfile:envfile_load.bzl", "envfile_load")
load("//bazel/scripts/envsubst:apply_envsubst.bzl", "apply_envsubst")
load("//bazel/scripts/filesystem:untar_files.bzl", "untar_files")
load("//bazel/scripts/hosts:append_hosts.bzl", "append_hosts")
load("//bazel/tools/pkgbuild:scripts.bzl", "postinstall")

apply_envsubst(
    name = "envsubst-supervisor",
    files = [
        "/usr/local/{}/data/supervisord.ini".format(NAME),
        "/usr/local/{}/data/nginx.conf".format(NAME),
        "/usr/local/{}/data/envfile".format(NAME),
        # DATA_FOLDER + "/supervisord.ini",
    ],
)

untar_files(
    name = "untar-files",
    files = [
        "/usr/local/{}/bin/app-admin-tar.tar".format(NAME),
        "/usr/local/{}/bin/app-gunicorn-tar.tar".format(NAME),
        # BIN_FOLDER + "/app-admin-tar.tar",  # "location :app-admin-tar"
        # BIN_FOLDER + "/app-gunicorn-tar.tar",  # "location :app-gunicorn-tar"
    ],
)

combine_envfiles(
    name = "combine-env",
    source = "/usr/local/{}/data/envfile".format(NAME),
    target = "/usr/local/{}/bin/.env".format(NAME),
)

envfile_load(
    name = "envfile-load",
    envfile = "/usr/local/{}/bin/.env".format(NAME),
)

django_command(
    name = "django-migrate",
    command = [
        "migrate",
    ],
    django_admin_app = DJANGO_ADMIN_APP,
)

django_command(
    name = "django-collectstatic",
    command = [
        "collectstatic",
        "--no-input",
        "--clear",
    ],
    django_admin_app = DJANGO_ADMIN_APP,
)

append_hosts(
    name = "nginx-append-app",
    host = "localhost.{}".format(NAME),  # This should match the gunicorn configuration
)

postinstall(
    name = "postinstall",
    chunks = [
        ":envsubst-supervisor",
        ":untar-files",
        ":combine-env",
        ":envfile-load",
        "//bazel/scripts/postgres:pg_create_database.sh",
        ":django-migrate",
        ":django-collectstatic",

        # TODO: Add django-createsuperuser (use GUI app to collect data)

        # Once we are done installing and creating all the files, we chown them
        "//bazel/scripts/bash:chown_root_folder.sh",

        # Supervisorctl
        "//bazel/scripts/supervisor:update_and_start.sh",

        # Nginx
        "//bazel/scripts/nginx:reload.sh",
        ":nginx-append-app",
    ],
    folders = ALL_FOLDERS,
    pkgbuild_name = NAME,
    tags = ["manual"],
    visibility = ["//apps/finances/installable/scripts:__subpackages__"],
)
