load("@rules_qt//qt:qt_cc_library.bzl", "qt_cc_library")

qt_cc_library(
    name = "models",
    srcs = [
        "generic_table_model.cpp",
    ],
    hdrs = [
        "generic_table_model.h",
    ],
    normal_hdrs = [
        "errors.h",
        "data_dispatcher.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//bazel/logging:spdlog",
        "//libraries/utils/cpp:type_name",
        "//libraries/utils/cpp/expected_type",
        "//libraries/utils/cpp/libpqxx:connection_pool",
        "//libraries/utils/cpp/libpqxx/orm",
        "@magic_enum",
        "@rules_qt//:qt_core",
        "@tl-expected",
    ],
)
