# Envvars for the Rust application
FINANCES_QT_SQL_USER=${DJANGO_SQL_USER}
FINANCES_QT_SQL_PASSWORD=${DJANGO_SQL_PASSWORD}
FINANCES_QT_SQL_HOST=${DJANGO_SQL_HOST}
FINANCES_QT_SQL_PORT=${DJANGO_SQL_PORT}
FINANCES_QT_SQL_DATABASE=${DJANGO_SQL_DATABASE}

# This is the AccountHolder ME
FINANCES_QT_INITIAL_HOLDER_PK=48
