load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "combobox_with_search",
    hdrs = [
        "combobox_with_search.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//bazel/logging:spdlog",
        "//libraries/utils/cpp:expected_type",
        "//libraries/utils/cpp/qt/models",
        "@magic_enum",
        "@rules_qt//:qt_widgets",
    ],
)
