load("@rules_qt//qt:qt_cc_library.bzl", "qt_cc_library")

qt_cc_library(
    name = "combobox_with_search",
    srcs = [
        "combobox_with_search.cpp",
    ],
    hdrs = [
        "combobox_with_search.h",
    ],
    # normal_hdrs = [
    #     "errors.h",
    #     "data_dispatcher.h",
    # ],
    visibility = ["//visibility:public"],
    deps = [
        "//bazel/logging:spdlog",
        # "//libraries/utils/cpp:expected_type",
        # "//libraries/utils/cpp:type_name",
        # "//libraries/utils/cpp/libpqxx:connection_pool",
        # "//libraries/utils/cpp/libpqxx/orm",
        # "@magic_enum",
        "@rules_qt//:qt_widgets",
        # "@tl-expected",
    ],
)
