[package]
name = "filesystem-pcloud"
version = "0.1.0"
edition = "2021"

[features]


[dependencies]
filesystem = { path = "../filesystem" }
pcloud-sdk = { path = "../pcloud_sdk" }

anyhow = { version = "1.0" }
async-trait = "0.1"
camino = "1.1"
flume = "0.10.14"
tokio = { version = "1.26", features = ["full"] }
tracing = { version = "0.1" }

[dev-dependencies]
#filesystem = { path = ".", features = ["test_utils"] }
pcloud-sdk = { path = "../pcloud_sdk", features = ["test_utils"] }


[[example]]
name = "copy_file"

