// @generated by protoc-gen-es v2.11.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/ticket_to_ride/models/board.proto (package board_games.ticket_to_ride, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { DestinationDeck, TrainDeck } from "./decks_pb.js";

/**
 * Describes the file apps/board_games/games/ticket_to_ride/models/board.proto.
 */
export declare const file_apps_board_games_games_ticket_to_ride_models_board: GenFile;

/**
 * @generated from message board_games.ticket_to_ride.BoardState
 */
export declare type BoardState = Message<"board_games.ticket_to_ride.BoardState"> & {
  /**
   * Train & destination decks
   *
   * @generated from field: board_games.ticket_to_ride.TrainDeck train_deck = 1;
   */
  trainDeck?: TrainDeck;

  /**
   * @generated from field: board_games.ticket_to_ride.DestinationDeck destination_deck = 2;
   */
  destinationDeck?: DestinationDeck;

  /**
   * Which routes have been claimed by which player.
   * Index = route_id from MapDefinition.
   *
   * route_id → player_id
   *
   * @generated from field: map<uint32, uint32> route_owner = 3;
   */
  routeOwner: { [key: number]: number };
};

/**
 * Describes the message board_games.ticket_to_ride.BoardState.
 * Use `create(BoardStateSchema)` to create a new message.
 */
export declare const BoardStateSchema: GenMessage<BoardState>;

