// @generated by protoc-gen-es v2.10.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/ticket_to_ride/models/cards.proto (package board_games.ticket_to_ride, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Color } from "../maps/map_pb.js";

/**
 * Describes the file apps/board_games/games/ticket_to_ride/models/cards.proto.
 */
export declare const file_apps_board_games_games_ticket_to_ride_models_cards: GenFile;

/**
 * This is a single train card (color or loco).
 *
 * @generated from message board_games.ticket_to_ride.TrainCard
 */
export declare type TrainCard = Message<"board_games.ticket_to_ride.TrainCard"> & {
  /**
   * @generated from oneof board_games.ticket_to_ride.TrainCard.card_color
   */
  cardColor: {
    /**
     * @generated from field: board_games.ticket_to_ride.Color color = 1;
     */
    value: Color;
    case: "color";
  } | {
    /**
     * @generated from field: bool locomotive = 2;
     */
    value: boolean;
    case: "locomotive";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message board_games.ticket_to_ride.TrainCard.
 * Use `create(TrainCardSchema)` to create a new message.
 */
export declare const TrainCardSchema: GenMessage<TrainCard>;

/**
 * @generated from message board_games.ticket_to_ride.DestinationTicket
 */
export declare type DestinationTicket = Message<"board_games.ticket_to_ride.DestinationTicket"> & {
  /**
   * unique per ticket deck
   *
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * city indices referring to MapDefinition.cities
   *
   * @generated from field: uint32 city_a = 2;
   */
  cityA: number;

  /**
   * @generated from field: uint32 city_b = 3;
   */
  cityB: number;

  /**
   * positive or negative at end
   *
   * @generated from field: uint32 points = 4;
   */
  points: number;
};

/**
 * Describes the message board_games.ticket_to_ride.DestinationTicket.
 * Use `create(DestinationTicketSchema)` to create a new message.
 */
export declare const DestinationTicketSchema: GenMessage<DestinationTicket>;

