// @generated by protoc-gen-es v2.10.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/ticket_to_ride/models/colors.proto (package board_games.ticket_to_ride, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file apps/board_games/games/ticket_to_ride/models/colors.proto.
 */
export declare const file_apps_board_games_games_ticket_to_ride_models_colors: GenFile;

/**
 * @generated from enum board_games.ticket_to_ride.Color
 */
export enum Color {
  /**
   * @generated from enum value: UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: BLUE = 1;
   */
  BLUE = 1,

  /**
   * @generated from enum value: RED = 2;
   */
  RED = 2,

  /**
   * @generated from enum value: GREEN = 3;
   */
  GREEN = 3,

  /**
   * @generated from enum value: YELLOW = 4;
   */
  YELLOW = 4,

  /**
   * @generated from enum value: BLACK = 5;
   */
  BLACK = 5,

  /**
   * @generated from enum value: WHITE = 6;
   */
  WHITE = 6,

  /**
   * @generated from enum value: ORANGE = 7;
   */
  ORANGE = 7,

  /**
   * @generated from enum value: PURPLE = 8;
   */
  PURPLE = 8,
}

/**
 * Describes the enum board_games.ticket_to_ride.Color.
 */
export declare const ColorSchema: GenEnum<Color>;

