// @generated by protoc-gen-es v2.10.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/ticket_to_ride/models/decks.proto (package board_games.ticket_to_ride, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { DestinationTicket, TrainCard } from "./cards_pb.js";

/**
 * Describes the file apps/board_games/games/ticket_to_ride/models/decks.proto.
 */
export declare const file_apps_board_games_games_ticket_to_ride_models_decks: GenFile;

/**
 * @generated from message board_games.ticket_to_ride.TrainDeck
 */
export declare type TrainDeck = Message<"board_games.ticket_to_ride.TrainDeck"> & {
  /**
   * Cards remaining in draw deck (top is last).
   *
   * @generated from field: repeated board_games.ticket_to_ride.TrainCard draw_pile = 1;
   */
  drawPile: TrainCard[];

  /**
   * exactly 5 in standard rules
   *
   * @generated from field: repeated board_games.ticket_to_ride.TrainCard face_up = 2;
   */
  faceUp: TrainCard[];

  /**
   * For reshuffling or late-game empty-deck situations.
   *
   * @generated from field: repeated board_games.ticket_to_ride.TrainCard discard_pile = 3;
   */
  discardPile: TrainCard[];
};

/**
 * Describes the message board_games.ticket_to_ride.TrainDeck.
 * Use `create(TrainDeckSchema)` to create a new message.
 */
export declare const TrainDeckSchema: GenMessage<TrainDeck>;

/**
 * @generated from message board_games.ticket_to_ride.DestinationDeck
 */
export declare type DestinationDeck = Message<"board_games.ticket_to_ride.DestinationDeck"> & {
  /**
   * @generated from field: repeated board_games.ticket_to_ride.DestinationTicket draw_pile = 1;
   */
  drawPile: DestinationTicket[];

  /**
   * @generated from field: repeated board_games.ticket_to_ride.DestinationTicket discard_pile = 2;
   */
  discardPile: DestinationTicket[];
};

/**
 * Describes the message board_games.ticket_to_ride.DestinationDeck.
 * Use `create(DestinationDeckSchema)` to create a new message.
 */
export declare const DestinationDeckSchema: GenMessage<DestinationDeck>;

