// @generated by protoc-gen-es v2.10.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/ticket_to_ride/models/event_log.proto (package board_games.ticket_to_ride, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apps/board_games/games/ticket_to_ride/models/event_log.proto.
 */
export declare const file_apps_board_games_games_ticket_to_ride_models_event_log: GenFile;

/**
 * @generated from message board_games.ticket_to_ride.event
 */
export declare type event = Message<"board_games.ticket_to_ride.event"> & {
};

/**
 * Describes the message board_games.ticket_to_ride.event.
 * Use `create(eventSchema)` to create a new message.
 */
export declare const eventSchema: GenMessage<event>;

