syntax = "proto3";
package board_games.ticket_to_ride;

import "apps/board_games/games/ticket_to_ride/models/board.proto";
import "apps/board_games/games/ticket_to_ride/models/player.proto";
import "apps/board_games/games/ticket_to_ride/models/map.proto";


message GameState {
  MapDefinition map = 1;

  // Indexed or mapped by Participant.id
  map<uint32, PlayerState> players = 2;

  BoardState board = 3;

  // Turn manager
  uint32 current_player_id = 4;
  uint32 turn_number = 5;

  bool final_turn_triggered = 6; // last turn begins
  bool game_over = 7;
}
