// @generated by protoc-gen-es v2.10.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/ticket_to_ride/models/game.proto (package board_games.ticket_to_ride, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { MapDefinition } from "./map_pb.js";
import type { PlayerState } from "./player_pb.js";
import type { BoardState } from "./board_pb.js";

/**
 * Describes the file apps/board_games/games/ticket_to_ride/models/game.proto.
 */
export declare const file_apps_board_games_games_ticket_to_ride_models_game: GenFile;

/**
 * @generated from message board_games.ticket_to_ride.GameState
 */
export declare type GameState = Message<"board_games.ticket_to_ride.GameState"> & {
  /**
   * @generated from field: board_games.ticket_to_ride.MapDefinition map = 1;
   */
  map?: MapDefinition;

  /**
   * Indexed or mapped by Participant.id
   *
   * @generated from field: map<uint32, board_games.ticket_to_ride.PlayerState> players = 2;
   */
  players: { [key: number]: PlayerState };

  /**
   * @generated from field: board_games.ticket_to_ride.BoardState board = 3;
   */
  board?: BoardState;

  /**
   * Turn manager
   *
   * @generated from field: uint32 current_player_id = 4;
   */
  currentPlayerId: number;

  /**
   * @generated from field: uint32 turn_number = 5;
   */
  turnNumber: number;

  /**
   * last turn begins
   *
   * @generated from field: bool final_turn_triggered = 6;
   */
  finalTurnTriggered: boolean;

  /**
   * @generated from field: bool game_over = 7;
   */
  gameOver: boolean;
};

/**
 * Describes the message board_games.ticket_to_ride.GameState.
 * Use `create(GameStateSchema)` to create a new message.
 */
export declare const GameStateSchema: GenMessage<GameState>;

