// @generated by protoc-gen-es v2.10.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/ticket_to_ride/models/map.proto (package board_games.ticket_to_ride, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Color } from "./colors_pb.js";

/**
 * Describes the file apps/board_games/games/ticket_to_ride/models/map.proto.
 */
export declare const file_apps_board_games_games_ticket_to_ride_models_map: GenFile;

/**
 * @generated from message board_games.ticket_to_ride.RouteDefinition
 */
export declare type RouteDefinition = Message<"board_games.ticket_to_ride.RouteDefinition"> & {
  /**
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * @generated from field: uint32 city_a = 2;
   */
  cityA: number;

  /**
   * @generated from field: uint32 city_b = 3;
   */
  cityB: number;

  /**
   * @generated from oneof board_games.ticket_to_ride.RouteDefinition.route_color
   */
  routeColor: {
    /**
     * @generated from field: board_games.ticket_to_ride.Color color = 4;
     */
    value: Color;
    case: "color";
  } | {
    /**
     * GREY = any color
     *
     * @generated from field: bool any = 5;
     */
    value: boolean;
    case: "any";
  } | { case: undefined; value?: undefined };

  /**
   * 1..6
   *
   * @generated from field: uint32 length = 6;
   */
  length: number;

  /**
   * for Europe, false in USA
   *
   * @generated from field: bool is_tunnel = 7;
   */
  isTunnel: boolean;

  /**
   * true for the second parallel edge
   *
   * @generated from field: bool is_second_route = 8;
   */
  isSecondRoute: boolean;
};

/**
 * Describes the message board_games.ticket_to_ride.RouteDefinition.
 * Use `create(RouteDefinitionSchema)` to create a new message.
 */
export declare const RouteDefinitionSchema: GenMessage<RouteDefinition>;

/**
 * @generated from message board_games.ticket_to_ride.MapDefinition
 */
export declare type MapDefinition = Message<"board_games.ticket_to_ride.MapDefinition"> & {
  /**
   * e.g. "USA", "Europe"
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * names indexed by city id
   *
   * @generated from field: repeated string cities = 2;
   */
  cities: string[];

  /**
   * static, referenced by route_id
   *
   * @generated from field: repeated board_games.ticket_to_ride.RouteDefinition routes = 3;
   */
  routes: RouteDefinition[];
};

/**
 * Describes the message board_games.ticket_to_ride.MapDefinition.
 * Use `create(MapDefinitionSchema)` to create a new message.
 */
export declare const MapDefinitionSchema: GenMessage<MapDefinition>;

