// @generated by protoc-gen-es v2.10.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/ticket_to_ride/models/player.proto (package board_games.ticket_to_ride, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { DestinationTicket, TrainCard } from "./cards_pb.js";

/**
 * Describes the file apps/board_games/games/ticket_to_ride/models/player.proto.
 */
export declare const file_apps_board_games_games_ticket_to_ride_models_player: GenFile;

/**
 * @generated from message board_games.ticket_to_ride.PlayerState
 */
export declare type PlayerState = Message<"board_games.ticket_to_ride.PlayerState"> & {
  /**
   * maps to Participant.pk
   *
   * @generated from field: uint32 player_id = 1;
   */
  playerId: number;

  /**
   * starts at 45 (USA)
   *
   * @generated from field: uint32 trains_remaining = 2;
   */
  trainsRemaining: number;

  /**
   * hidden from others
   *
   * @generated from field: repeated board_games.ticket_to_ride.TrainCard hand = 3;
   */
  hand: TrainCard[];

  /**
   * hidden, includes uncompleted ones
   *
   * @generated from field: repeated board_games.ticket_to_ride.DestinationTicket tickets = 4;
   */
  tickets: DestinationTicket[];

  /**
   * references RouteDef.id
   *
   * @generated from field: repeated uint32 claimed_route_ids = 5;
   */
  claimedRouteIds: number[];

  /**
   * optional; can be computed by engine
   *
   * @generated from field: uint32 score = 6;
   */
  score: number;
};

/**
 * Describes the message board_games.ticket_to_ride.PlayerState.
 * Use `create(PlayerStateSchema)` to create a new message.
 */
export declare const PlayerStateSchema: GenMessage<PlayerState>;

