load("//bazel/rust:defs.bzl", "rust_library_tests_and_docs")

exports_files(["Cargo.toml"])

rust_library_tests_and_docs(
    name = "cron",
    srcs = glob(["src/**/*.rs"]),
    all_features = {
        "diff": ["diff"],
        "local": ["local"],
        "test_utils": [
            "test_utils",
            "local",
        ],
    },
    deps = [
        "//bazel/third_party/crates:chrono",
        "//bazel/third_party/crates:chrono-tz",
        "//bazel/third_party/crates:cron-parser",
        "//bazel/third_party/crates:serde",
        "//bazel/third_party/crates:thiserror",
    ],
)
