load("@crates_libraries//:defs.bzl", "aliases", "all_crate_deps")
load("//bazel/rust:defs.bzl", "rust_library_tests_and_docs")

rust_library_tests_and_docs(
    name = "cron",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    all_features = {
        "diff": ["diff"],
        "local": ["local"],
        "test_utils": [
            "test_utils",
            "local",
        ],
    },
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    deps = all_crate_deps(
        normal = True,
    ),
)
