load("@aspect_rules_ts//ts:proto.bzl", "ts_proto_library")
load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("//apps/board_games/games/ticket_to_ride/maps:defs.bzl", "generate_map_targets")

proto_library(
    name = "map_proto",
    srcs = [
        "map.proto",
    ],
)

cc_proto_library(
    name = "map_cc_proto",
    visibility = ["//apps/board_games/games/ticket_to_ride:__subpackages__"],
    deps = [":map_proto"],
)

ts_proto_library(
    name = "map_ts_proto",
    copy_files = True,
    node_modules = "//:node_modules",
    proto = ":map_proto",
    proto_srcs = [
        "map.proto",
    ],
    protoc_gen_options = {
        "import_extension": "js",
    },
    visibility = [
        "//apps/board_games/games/ticket_to_ride/webapp:__pkg__",
    ],
)

# MAPS

generate_map_targets(name = "usa")
# filegroup(
#     name = "usa",
#     srcs = ["usa.textproto"],
#     visibility = ["//apps/board_games/games/ticket_to_ride:__subpackages__"],
# )

# genrule(
#     name = "usa-svg",
#     srcs = [":usa"],
#     outs = ["usa.svg"],
#     cmd = "$(location //apps/board_games/games/ticket_to_ride/maps/gen) --textproto=$(location :usa) --output=$@",
#     tools = [
#         "//apps/board_games/games/ticket_to_ride/maps/gen",
#     ],
# )
