// @generated by protoc-gen-es v2.10.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/games/ticket_to_ride/maps/map.proto (package board_games.ticket_to_ride, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file apps/board_games/games/ticket_to_ride/maps/map.proto.
 */
export declare const file_apps_board_games_games_ticket_to_ride_maps_map: GenFile;

/**
 * @generated from message board_games.ticket_to_ride.MapData
 */
export declare type MapData = Message<"board_games.ticket_to_ride.MapData"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: repeated board_games.ticket_to_ride.City cities = 2;
   */
  cities: City[];

  /**
   * @generated from field: repeated board_games.ticket_to_ride.Route routes = 3;
   */
  routes: Route[];

  /**
   * @generated from field: int32 size_x = 4;
   */
  sizeX: number;

  /**
   * @generated from field: int32 size_y = 5;
   */
  sizeY: number;
};

/**
 * Describes the message board_games.ticket_to_ride.MapData.
 * Use `create(MapDataSchema)` to create a new message.
 */
export declare const MapDataSchema: GenMessage<MapData>;

/**
 * @generated from message board_games.ticket_to_ride.City
 */
export declare type City = Message<"board_games.ticket_to_ride.City"> & {
  /**
   * @generated from field: int32 id = 1;
   */
  id: number;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: int32 pos_x = 3;
   */
  posX: number;

  /**
   * @generated from field: int32 pos_y = 4;
   */
  posY: number;
};

/**
 * Describes the message board_games.ticket_to_ride.City.
 * Use `create(CitySchema)` to create a new message.
 */
export declare const CitySchema: GenMessage<City>;

/**
 * @generated from message board_games.ticket_to_ride.Route
 */
export declare type Route = Message<"board_games.ticket_to_ride.Route"> & {
  /**
   * @generated from field: int32 city1 = 1;
   */
  city1: number;

  /**
   * @generated from field: int32 city2 = 2;
   */
  city2: number;

  /**
   * @generated from field: board_games.ticket_to_ride.Color color = 3;
   */
  color: Color;

  /**
   * @generated from field: int32 length = 4;
   */
  length: number;

  /**
   * @generated from field: bool double_route = 5;
   */
  doubleRoute: boolean;

  /**
   * @generated from field: bool draw_ccw = 6;
   */
  drawCcw: boolean;
};

/**
 * Describes the message board_games.ticket_to_ride.Route.
 * Use `create(RouteSchema)` to create a new message.
 */
export declare const RouteSchema: GenMessage<Route>;

/**
 * @generated from enum board_games.ticket_to_ride.Color
 */
export enum Color {
  /**
   * @generated from enum value: COLOR_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: COLOR_BLUE = 1;
   */
  BLUE = 1,

  /**
   * @generated from enum value: COLOR_RED = 2;
   */
  RED = 2,

  /**
   * @generated from enum value: COLOR_GREEN = 3;
   */
  GREEN = 3,

  /**
   * @generated from enum value: COLOR_YELLOW = 4;
   */
  YELLOW = 4,

  /**
   * @generated from enum value: COLOR_BLACK = 5;
   */
  BLACK = 5,

  /**
   * @generated from enum value: COLOR_WHITE = 6;
   */
  WHITE = 6,

  /**
   * @generated from enum value: COLOR_ORANGE = 7;
   */
  ORANGE = 7,

  /**
   * @generated from enum value: COLOR_PURPLE = 8;
   */
  PURPLE = 8,

  /**
   * @generated from enum value: COLOR_PINK = 8;
   */
  PINK = 8,
}

/**
 * Describes the enum board_games.ticket_to_ride.Color.
 */
export declare const ColorSchema: GenEnum<Color>;

