# --- Map dimensions --
size_x: 1200
size_y: 773

# --- Cities ---
cities: { id: 0  name: "Vancouver" pos_x: 97 pos_y: 90 }
cities: { id: 1  name: "Seattle" pos_x: 95 pos_y: 158 }
cities: { id: 2  name: "Portland" pos_x: 68 pos_y: 223 }
cities: { id: 3  name: "San Francisco" pos_x: 51 pos_y: 468 }
cities: { id: 4  name: "Los Angeles" pos_x: 142 pos_y: 600 }
cities: { id: 5  name: "Calgary" pos_x: 262 pos_y: 70 }
cities: { id: 6  name: "Helena" pos_x: 385 pos_y: 233 }
cities: { id: 7  name: "Salt Lake City" pos_x: 298 pos_y: 388 }
cities: { id: 8  name: "Las Vegas" pos_x: 228 pos_y: 526 }
cities: { id: 9  name: "Phoenix" pos_x: 296 pos_y: 608 }
cities: { id: 10 name: "Winnipeg" pos_x: 540 pos_y: 80 }
cities: { id: 11 name: "Denver" pos_x: 460 pos_y: 430 }
cities: { id: 12 name: "Santa Fe" pos_x: 450 pos_y: 540 }
cities: { id: 13 name: "El Paso" pos_x: 443 pos_y: 653 }
cities: { id: 14 name: "Duluth" pos_x: 682 pos_y: 227 }
cities: { id: 15 name: "Omaha" pos_x: 646 pos_y: 342 }
cities: { id: 16 name: "Kansas City" pos_x: 669 pos_y: 405 }
cities: { id: 17 name: "Oklahoma City" pos_x: 644 pos_y: 514 }
cities: { id: 18 name: "Dallas" pos_x: 669 pos_y: 624 }
cities: { id: 19 name: "Houston" pos_x: 721 pos_y: 674 }
cities: { id: 20 name: "Sault Ste Marie" pos_x: 840 pos_y: 142 }
cities: { id: 21 name: "Chicago" pos_x: 835 pos_y: 304 }
cities: { id: 22 name: "Saint Louis" pos_x: 780 pos_y: 408 }
cities: { id: 23 name: "Little Rock" pos_x: 757 pos_y: 518 }
cities: { id: 24 name: "New Orleans" pos_x: 840 pos_y: 665 }
cities: { id: 25 name: "Nashville" pos_x: 897 pos_y: 457 }
cities: { id: 26 name: "Atlanta" pos_x: 958 pos_y: 499 }
cities: { id: 27 name: "Toronto" pos_x: 980 pos_y: 170 }
cities: { id: 28 name: "Pittsburgh" pos_x: 998 pos_y: 285 }
cities: { id: 29 name: "Montreal" pos_x: 1080 pos_y: 60 }
cities: { id: 30 name: "Boston" pos_x: 1168 pos_y: 136 }
cities: { id: 31 name: "New York" pos_x: 1103 pos_y: 229 }
cities: { id: 32 name: "Washington" pos_x: 1114 pos_y: 342 }
cities: { id: 33 name: "Raleigh" pos_x: 1040 pos_y: 425 }
cities: { id: 34 name: "Charleston" pos_x: 1077 pos_y: 508 }
cities: { id: 35 name: "Miami" pos_x: 1115 pos_y: 705 }


# --- Routes ---
# (city1, city2, color, length, double_route)
#
# - city1: origin
# - city2: target
# - color: route color, use COLOR_UNKNOWN for "grey" ones
# - lenght: number of carriages for the route
# - double_route: true for double routes.

# Vancouver - Seattle
routes: { city1: 0  city2: 1  color: COLOR_UNKNOWN length: 1 double_route: true }
routes: { city1: 0  city2: 1  color: COLOR_UNKNOWN length: 1 double_route: true }

# Seattle - Portland
routes: { city1: 1  city2: 2  color: COLOR_UNKNOWN length: 1 double_route: true }
routes: { city1: 1  city2: 2  color: COLOR_UNKNOWN length: 1 double_route: true }

# Portland - San Francisco
routes: { city1: 2  city2: 3  color: COLOR_GREEN length: 5 double_route: true }
routes: { city1: 2  city2: 3  color: COLOR_PINK length: 5 double_route: true }

# San Francisco - Los Angeles
routes: { city1: 3  city2: 4  color: COLOR_YELLOW length: 3 double_route: true }
routes: { city1: 3  city2: 4  color: COLOR_PINK length: 3 double_route: true }

# Calgary - Vancouver
routes: { city1: 5  city2: 0  color: COLOR_UNKNOWN length: 3 double_route: false }

# Calgary - Seattle
routes: { city1: 5  city2: 1  color: COLOR_UNKNOWN length: 4 double_route: false }

# Calgary - Helena
routes: { city1: 5  city2: 6  color: COLOR_UNKNOWN length: 4 double_route: false }

# Helena - Seattle
routes: { city1: 6  city2: 1  color: COLOR_YELLOW length: 6 double_route: false }

# Helena - Salt Lake City
routes: { city1: 6  city2: 7  color: COLOR_PINK length: 3 double_route: false }

# Salt Lake City - Portland
routes: { city1: 7  city2: 2  color: COLOR_BLUE length: 6 double_route: false }

# Salt Lake City - San Francisco
routes: { city1: 7  city2: 3  color: COLOR_ORANGE length: 5 double_route: true }
routes: { city1: 7  city2: 3  color: COLOR_WHITE length: 5 double_route: true }

# Salt Lake City - Las Vegas
routes: { city1: 7  city2: 8  color: COLOR_ORANGE length: 3 double_route: false }

# Las Vegas - Los Angeles
routes: { city1: 8  city2: 4  color: COLOR_UNKNOWN length: 2 double_route: false }

# Phoenix - Los Angeles
routes: { city1: 9  city2: 4  color: COLOR_UNKNOWN length: 3 double_route: false }

# Winnipeg - Calgary
routes: { city1: 10  city2: 5  color: COLOR_WHITE length: 6 double_route: false }

# Winnipeg - Helena
routes: { city1: 10  city2: 6  color: COLOR_BLUE length: 4 double_route: false }

# Denver - Helena
routes: { city1: 11  city2: 6  color: COLOR_GREEN length: 4 double_route: false }

# Denver - Salt Lake City
routes: { city1: 11  city2: 7  color: COLOR_RED length: 3 double_route: true }
routes: { city1: 11  city2: 7  color: COLOR_YELLOW length: 3 double_route: true }

# Denver - Phoenix
routes: { city1: 11  city2: 9  color: COLOR_WHITE length: 5 double_route: false }

# Denver - Santa Fe
routes: { city1: 11  city2: 12  color: COLOR_UNKNOWN length: 2 double_route: false }

# Santa Fe - Phoenix
routes: { city1: 12  city2: 9  color: COLOR_UNKNOWN length: 3 double_route: false }

# Santa Fe - El Paso
routes: { city1: 12  city2: 13  color: COLOR_UNKNOWN length: 2 double_route: false }

# El Paso - Los Angeles
routes: { city1: 13  city2: 4  color: COLOR_BLACK length: 6 double_route: false }

# Duluth - Winnipeg
routes: { city1: 14  city2: 10  color: COLOR_BLACK length: 4 double_route: false }

# Duluth - Helena
routes: { city1: 14  city2: 6  color: COLOR_ORANGE length: 6 double_route: false }

# Duluth - Omaha
routes: { city1: 14  city2: 15  color: COLOR_UNKNOWN length: 2 double_route: true }
routes: { city1: 14  city2: 15  color: COLOR_UNKNOWN length: 2 double_route: true }

# Omaha - Helena
routes: { city1: 15  city2: 6  color: COLOR_RED length: 5 double_route: false }

# Omaha - Denver
routes: { city1: 15  city2: 11  color: COLOR_PINK length: 4 double_route: false }

# Omaha - Kansas City
routes: { city1: 15  city2: 16  color: COLOR_UNKNOWN length: 1 double_route: true }
routes: { city1: 15  city2: 16  color: COLOR_UNKNOWN length: 1 double_route: true }

# Kansas City - Denver
routes: { city1: 16  city2: 11  color: COLOR_BLACK length: 4 double_route: true }
routes: { city1: 16  city2: 11  color: COLOR_ORANGE length: 4 double_route: true }

# Kansas City - Oklahoma City
routes: { city1: 16  city2: 17  color: COLOR_UNKNOWN length: 2 double_route: true }
routes: { city1: 16  city2: 17  color: COLOR_UNKNOWN length: 2 double_route: true }

# Oklahoma City - Denver
routes: { city1: 17  city2: 11  color: COLOR_RED length: 4 double_route: false }

# Oklahoma City - Santa Fe
routes: { city1: 17  city2: 12  color: COLOR_BLUE length: 3 double_route: false }

# Oklahoma City - El Paso
routes: { city1: 17  city2: 13  color: COLOR_YELLOW length: 5 double_route: false }

# Oklahoma City - Dallas
routes: { city1: 17  city2: 18  color: COLOR_UNKNOWN length: 1 double_route: true }
routes: { city1: 17  city2: 18  color: COLOR_UNKNOWN length: 1 double_route: true }

# Dallas - El Paso
routes: { city1: 18  city2: 13  color: COLOR_RED length: 4 double_route: false }

# Dallas - Houston
routes: { city1: 18  city2: 19  color: COLOR_UNKNOWN length: 1 double_route: true }
routes: { city1: 18  city2: 19  color: COLOR_UNKNOWN length: 1 double_route: true }

# Houston - El Paso
routes: { city1: 19  city2: 13  color: COLOR_GREEN length: 6 double_route: false }

# Sault Ste Marie - Winnipeg
routes: { city1: 20  city2: 10  color: COLOR_UNKNOWN length: 6 double_route: false }

# Sault Ste Marie - Duluth
routes: { city1: 20  city2: 14  color: COLOR_UNKNOWN length: 3 double_route: false }

# Chicago - Duluth
routes: { city1: 21  city2: 14  color: COLOR_RED length: 3 double_route: false }

# Chicago - Omaha
routes: { city1: 21  city2: 15  color: COLOR_BLUE length: 4 double_route: false }

# Chicago - Saint Louis
routes: { city1: 21  city2: 22  color: COLOR_GREEN length: 2 double_route: true }
routes: { city1: 21  city2: 22  color: COLOR_WHITE length: 2 double_route: true }

# Saint Louis - Kansas
routes: { city1: 22  city2: 16  color: COLOR_BLUE length: 2 double_route: true }
routes: { city1: 22  city2: 16  color: COLOR_PINK length: 2 double_route: true }

# Saint Louis - Little Rock
routes: { city1: 22  city2: 23  color: COLOR_UNKNOWN length: 2 double_route: false }

# Little Rock - Oklahoma City
routes: { city1: 23  city2: 17  color: COLOR_UNKNOWN length: 2 double_route: false }

# Little Rock - Dallas
routes: { city1: 23  city2: 18  color: COLOR_UNKNOWN length: 2 double_route: false }

# Little Rock - New Orleans
routes: { city1: 23  city2: 24  color: COLOR_GREEN length: 3 double_route: false }

# New Orleans - Houston
routes: { city1: 24  city2: 19  color: COLOR_UNKNOWN length: 2 double_route: false }

# Nashville - Saint Louis
routes: { city1: 25  city2: 22  color: COLOR_UNKNOWN length: 2 double_route: false }

# Nashville - Little Rock
routes: { city1: 25  city2: 23  color: COLOR_WHITE length: 3 double_route: false }

# Nashville - Atlanta
routes: { city1: 25  city2: 26  color: COLOR_UNKNOWN length: 1 double_route: false }

# Atlanta - New Orleans
routes: { city1: 26  city2: 24  color: COLOR_YELLOW length: 4 double_route: true }
routes: { city1: 26  city2: 24  color: COLOR_ORANGE length: 4 double_route: true }

# Toronto - Sault Ste Marie
routes: { city1: 27  city2: 20  color: COLOR_UNKNOWN length: 2 double_route: false }

# Toronto - Duluth
routes: { city1: 27  city2: 14  color: COLOR_PINK length: 6 double_route: false }

# Toronto - Chicago
routes: { city1: 27  city2: 21  color: COLOR_WHITE length: 4 double_route: false }

# Toronto - Pittsburgh
routes: { city1: 27  city2: 28  color: COLOR_UNKNOWN length: 2 double_route: false }

# Pittsburgh - Chicago
routes: { city1: 28  city2: 21  color: COLOR_ORANGE length: 3 double_route: true }
routes: { city1: 28  city2: 21  color: COLOR_BLACK length: 3 double_route: true }

# Pittsburgh - Saint Louis
routes: { city1: 28  city2: 22  color: COLOR_GREEN length: 5 double_route: false }

# Pittsburgh - Nashville
routes: { city1: 28  city2: 25  color: COLOR_YELLOW length: 4 double_route: false }

# Montreal - Sault Ste Marie
routes: { city1: 29  city2: 20  color: COLOR_BLACK length: 5 double_route: false }

# Montreal - Toronto
routes: { city1: 29  city2: 27  color: COLOR_UNKNOWN length: 3 double_route: false }

# Montreal - New York
routes: { city1: 29  city2: 31  color: COLOR_BLUE length: 3 double_route: false }

# Montreal - Boston
routes: { city1: 29  city2: 30  color: COLOR_UNKNOWN length: 2 double_route: true }
routes: { city1: 29  city2: 30  color: COLOR_UNKNOWN length: 2 double_route: true }

# Boston - New York
routes: { city1: 30  city2: 31  color: COLOR_YELLOW length: 2 double_route: true }
routes: { city1: 30  city2: 31  color: COLOR_RED length: 2 double_route: true }

# New York - Pittsburgh
routes: { city1: 31  city2: 28  color: COLOR_WHITE length: 2 double_route: true }
routes: { city1: 31  city2: 28  color: COLOR_GREEN length: 2 double_route: true }

# New York - Washington
routes: { city1: 31  city2: 32  color: COLOR_ORANGE length: 2 double_route: true }
routes: { city1: 31  city2: 32  color: COLOR_BLACK length: 2 double_route: true }

# Washington - Pittsburgh
routes: { city1: 32  city2: 28  color: COLOR_UNKNOWN length: 2 double_route: false }

# Washington - Raleigh
routes: { city1: 32  city2: 33  color: COLOR_UNKNOWN length: 2 double_route: true }
routes: { city1: 32  city2: 33  color: COLOR_UNKNOWN length: 2 double_route: true }

# Raleigh - Pittsburgh
routes: { city1: 33  city2: 28  color: COLOR_UNKNOWN length: 2 double_route: false }

# Raleigh - Nashville
routes: { city1: 33  city2: 25  color: COLOR_BLACK length: 3 double_route: false }

# Raleigh - Atlanta
routes: { city1: 33  city2: 26  color: COLOR_UNKNOWN length: 2 double_route: true }
routes: { city1: 33  city2: 26  color: COLOR_UNKNOWN length: 2 double_route: true }

# Raleigh - Charleston
routes: { city1: 33  city2: 34  color: COLOR_UNKNOWN length: 2 double_route: false }

# Charleston - Atlanta
routes: { city1: 34  city2: 26  color: COLOR_UNKNOWN length: 2 double_route: false }

# Charleston - Miami
routes: { city1: 34  city2: 35  color: COLOR_PINK length: 4 double_route: false }

# Miami - Atlanta
routes: { city1: 35  city2: 26  color: COLOR_BLUE length: 5 double_route: false }

# Miami - New Orleans
routes: { city1: 35  city2: 24  color: COLOR_RED length: 6 double_route: false }
