load("@rules_rust//rust:defs.bzl", "rust_binary")
load("//bazel/rust:defs.bzl", "rust_library_tests_and_docs")

exports_files(["Cargo.toml"])

rust_library_tests_and_docs(
    name = "rebrickable",
    srcs = glob(["src/**/*.rs"]),
    all_features = {
        "cli": [
            "cli",
            "use_indicatif",
        ],
        "use_indicatif": ["use_indicatif"],
        "test_utils": ["test_utils"],
    },
    proc_macro_deps = [
        "//bazel/third_party/crates:async-trait",
    ],
    deps = [
        "//bazel/third_party/crates:anyhow",
        "//bazel/third_party/crates:http",
        "//bazel/third_party/crates:reqwest",
        "//bazel/third_party/crates:serde",
        "//bazel/third_party/crates:serde_json",
        "//bazel/third_party/crates:thiserror",
        "//bazel/third_party/crates:time",
        "//libraries/utils/rust/utils",
    ],
)

rust_binary(
    name = "cli",
    srcs = glob(["src/cli/**/*.rs"]),
    deps = [
        ":rebrickable",
        "//bazel/third_party/crates:anyhow",
        "//bazel/third_party/crates:clap",
        "//bazel/third_party/crates:clap-verbosity-flag",
        "//bazel/third_party/crates:log",
        "//bazel/third_party/crates:serde_json",
        "//bazel/third_party/crates:tokio",
        "//bazel/third_party/crates:tracing",
        "//bazel/third_party/crates:tracing-subscriber",
    ],
)
