[package]
name = "rebrickable"
version = "0.1.0"
edition = "2021"

[features]
### The `cli` feature is required for the CLI binary. It also provides structs and methods to handle and
### store app authentication. We need to add it ot the "default" features as they are the ones enabled
### while building the CLI "binary"
default = ["cli"]
cli = ["dep:clap-verbosity-flag", "dep:tracing-subscriber", "dep:log", "dep:clap", "dep:anyhow", "use_indicatif"]
use_indicatif = ["dep:indicatif"]
test_utils = ["dep:mockall", "dep:httpmock"]


[dependencies]
utils = { path = "../utils/rust/utils" }

async-trait = { workspace = true }
camino = { workspace = true, features = ["serde1"] }
headers = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
itertools = { workspace = true }
mime = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_repr = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = [
    "serde",
    "parsing",
    "formatting",
    "macros",
] }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

# Optional dependencies
httpmock = { workspace = true, optional = true }
indicatif = { workspace = true, optional = true }
mockall = { workspace = true, optional = true }

# Deps for CLI
clap = { workspace = true, features = ["derive"], optional = true }
clap-verbosity-flag = { workspace = true, optional = true }
log = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }

[dev-dependencies]
env_logger = { workspace = true }
rebrickable = { path = ".", features = ["test_utils"] }
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }

[[bin]]
name = "bricklink"
path = "src/cli/main.rs"
# Waiting for https://github.com/rust-lang/cargo/issues/4663 (and related: https://github.com/rust-lang/rfcs/pull/3374)
required-features = ["cli"]
