load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "geometry_2d",
    hdrs = [
        "angle.hpp",
        "circle_for_arc.hpp",
        "circunference.hpp",
        "point.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/utils/cpp/math:newton_method",
    ],
)
