# Envvars for the Rust application
POSTGRES_USER=${DJANGO_SQL_USER}
POSTGRES_PASSWORD=${DJANGO_SQL_PASSWORD}
POSTGRES_HOST=${DJANGO_SQL_HOST}
POSTGRES_PORT=${DJANGO_SQL_PORT}
POSTGRES_DB=${DJANGO_SQL_DATABASE}

DJANGO_BASE_URL=http://localhost.%NAME%

MEDIA_URL=media
STATIC_URL=static

# Openexchangerates API
OPENEXCHANGERATES_APIKEY=
