load("@rules_rust//cargo:defs.bzl", "cargo_build_script")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test", "rust_test_suite")
load("//bazel/containers/with_docker:with_postgres_run.bzl", "with_postgres_test")

exports_files(["Cargo.toml"])

filegroup(
    name = "capabilities",
    srcs = glob(["capabilities/**/*"]),
)

filegroup(
    name = "icons",
    srcs = glob(["icons/**/*"]),
)

filegroup(
    name = "srcs_lib",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/main.rs"],
    ),
    visibility = ["//visibility:public"],
)

cargo_build_script(
    name = "build",
    srcs = ["build.rs"],
    build_script_env = {
        "DEP_TAURI_DEV": "false",
        # Tauri core
        "UNTAR-DEP_TAURI_CORE__CORE_PLUGIN___PERMISSION_FILES_PATH": "$(location //bazel/third_party/crates:tauri-core-permission-files)",
        "UNTAR-DEP_TAURI_CORE:APP__CORE_PLUGIN___PERMISSION_FILES_PATH": "$(location //bazel/third_party/crates:tauri-core-app-permission-files)",
        "UNTAR-DEP_TAURI_CORE:EVENT__CORE_PLUGIN___PERMISSION_FILES_PATH": "$(location //bazel/third_party/crates:tauri-core-event-permission-files)",
        "UNTAR-DEP_TAURI_CORE:IMAGE__CORE_PLUGIN___PERMISSION_FILES_PATH": "$(location //bazel/third_party/crates:tauri-core-image-permission-files)",
        "UNTAR-DEP_TAURI_CORE:MENU__CORE_PLUGIN___PERMISSION_FILES_PATH": "$(location //bazel/third_party/crates:tauri-core-menu-permission-files)",
        "UNTAR-DEP_TAURI_CORE:PATH__CORE_PLUGIN___PERMISSION_FILES_PATH": "$(location //bazel/third_party/crates:tauri-core-path-permission-files)",
        "UNTAR-DEP_TAURI_CORE:RESOURCES__CORE_PLUGIN___PERMISSION_FILES_PATH": "$(location //bazel/third_party/crates:tauri-core-resources-permission-files)",
        "UNTAR-DEP_TAURI_CORE:TRAY__CORE_PLUGIN___PERMISSION_FILES_PATH": "$(location //bazel/third_party/crates:tauri-core-tray-permission-files)",
        "UNTAR-DEP_TAURI_CORE:WEBVIEW__CORE_PLUGIN___PERMISSION_FILES_PATH": "$(location //bazel/third_party/crates:tauri-core-webview-permission-files)",
        "UNTAR-DEP_TAURI_CORE:WINDOW__CORE_PLUGIN___PERMISSION_FILES_PATH": "$(location //bazel/third_party/crates:tauri-core-window-permission-files)",
        "DEP_TAURI_GLOBAL_API_SCRIPT_PATH": "$(location //bazel/third_party/crates:tauri-global-api-script)",
        # Tauri plugins
        "DEP_TAURI_PLUGIN_LOG_PERMISSION_FILES_PATH": "$(location //bazel/third_party/crates:tauri-plugin-log-permission-files-index)",
        "DEP_TAURI_PLUGIN_LOG_GLOBAL_API_SCRIPT_PATH": "$(location //bazel/third_party/crates:tauri-plugin-log-global-api-script)",
        "DEP_TAURI_PLUGIN_SHELL_PERMISSION_FILES_PATH": "$(location //bazel/third_party/crates:tauri-plugin-shell-permission-files-index)",
        "DEP_TAURI_PLUGIN_SHELL_GLOBAL_SCOPE_SCHEMA_PATH": "$(location //bazel/third_party/crates:tauri-plugin-shell-global-scope)",
        "DEP_TAURI_PLUGIN_SHELL_GLOBAL_API_SCRIPT_PATH": "$(location //bazel/third_party/crates:tauri-plugin-shell-global-api-script)",
    },
    data = [
        "Cargo.toml",
        "tauri.conf.json",
        ":capabilities",
        ":icons",
        # Tauri core
        "//bazel/third_party/crates:tauri-global-api-script",
        "//bazel/third_party/crates:tauri-core-permission-files",
        "//bazel/third_party/crates:tauri-core-app-permission-files",
        "//bazel/third_party/crates:tauri-core-event-permission-files",
        "//bazel/third_party/crates:tauri-core-image-permission-files",
        "//bazel/third_party/crates:tauri-core-menu-permission-files",
        "//bazel/third_party/crates:tauri-core-path-permission-files",
        "//bazel/third_party/crates:tauri-core-resources-permission-files",
        "//bazel/third_party/crates:tauri-core-tray-permission-files",
        "//bazel/third_party/crates:tauri-core-webview-permission-files",
        "//bazel/third_party/crates:tauri-core-window-permission-files",
        # Tauri plugins
        # "//bazel/third_party/crates:tauri-plugin-log-permission-files",
        "//bazel/third_party/crates:tauri-plugin-log-permission-files-index",
        "//bazel/third_party/crates:tauri-plugin-log-global-api-script",
        # "//bazel/third_party/crates:tauri-plugin-shell-permission-files",
        "//bazel/third_party/crates:tauri-plugin-shell-permission-files-index",
        "//bazel/third_party/crates:tauri-plugin-shell-global-scope",
        "//bazel/third_party/crates:tauri-plugin-shell-global-api-script",
    ],
    deps = [
        "//bazel/third_party/crates:anyhow",
        "//bazel/third_party/crates:flate2",
        "//bazel/third_party/crates:serde_json",
        "//bazel/third_party/crates:tar",
        "//bazel/third_party/crates:tauri-build",
    ],
)

rust_library(
    name = "applib",
    srcs = [":srcs_lib"],
    # compile_data = [
    #     # "tauri.conf.json",
    #     # ":icons",
    #     # ":capabilities",
    #     # ":gen",
    #     # "//apps/finances/tauri:frontend",
    # ],
    crate_features = ["postgres"],
    crate_name = "finances_app_lib",
    deps = [
        ":build",
        "//apps/finances/tauri/models:models/rust",
        "//bazel/third_party/crates:bigdecimal",
        "//bazel/third_party/crates:chrono",
        "//bazel/third_party/crates:diesel",
        "//bazel/third_party/crates:log",
        "//bazel/third_party/crates:serde",
        "//bazel/third_party/crates:tauri",
        "//bazel/third_party/crates:tauri-plugin-log",
        "//bazel/third_party/crates:tauri-plugin-shell",
        "//bazel/third_party/crates:thiserror",
        "//libraries/finances/accounts/rust:finances_accounts",
        "//libraries/finances/investments/rust:finances_investments",
    ],
)

# Unittests
rust_test(
    name = "tests",
    crate = ":applib",
    crate_features = [
        "postgres",
    ],
    data = [
        "tauri.conf.json",
        ":capabilities",
        ":icons",
    ],
)

# Integration tests
integration_tests_files = glob(["tests/**/test_*.rs"])

rust_test_suite(
    name = "_integration_tests",
    srcs = integration_tests_files,
    crate_features = ["postgres"],
    shared_srcs = glob(["tests/common/**/*.rs"]),
    tags = [
        "manual",
    ],
    deps = [
        ":applib",
        "//apps/finances/tauri/models:models/rust",
        "//bazel/third_party/crates:bigdecimal",
        "//bazel/third_party/crates:camino",
        "//bazel/third_party/crates:chrono",
        "//bazel/third_party/crates:prost",
        "//bazel/third_party/crates:serde",
        "//bazel/third_party/crates:serde_json",
        "//bazel/third_party/crates:tauri",
        "//libraries/finances/accounts/rust:finances_accounts/test_utils",
    ],
)

with_postgres_test(
    name = "integration_tests",
    # First migrate,then run the tests
    binaries = [
        "//libraries/finances/investments/django_finances_investments:migrate",
        "//libraries/finances/accounts/django_finances_accounts:populate_test_database",
        "//libraries/finances/investments/django_finances_investments:populate_test_database",
    ] + ["_integration_tests_{}".format(it.replace(".rs", "")) for it in integration_tests_files],  # NOTE: The rust_test_suite is just a group of tests! # TODO: Bazel multicommand!!!
    env = {
        "DJANGO_SQL_ENGINE": "django.db.backends.postgresql",
    },
    env_transpose = {
        "DJANGO_SQL_DATABASE": "POSTGRES_DB",
        "DJANGO_SQL_USER": "POSTGRES_USER",
        "DJANGO_SQL_PASSWORD": "POSTGRES_PASSWORD",
        "DJANGO_SQL_HOST": "POSTGRES_HOST",
        "DJANGO_SQL_PORT": "POSTGRES_PORT",
    },
    tags = [
        "no-sandbox",  # The tauri-plugin-log generates some output files.
    ],
)

# TODO: Add targets to generate docs and to doc-testing

rust_binary(
    name = "app",
    srcs = ["src/main.rs"],
    visibility = ["//apps/finances:__pkg__"],
    deps = [
        ":applib",
        "//apps/finances/tauri/models:models/rust",
        "//bazel/third_party/crates:camino",
        "//bazel/third_party/crates:tauri",
    ],
)
