load("@crates_libraries//:defs.bzl", "all_crate_deps")
load("@rules_rust//cargo:defs.bzl", "cargo_build_script")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test", "rust_test_suite")
load("//bazel/containers/with_docker:with_postgres_run.bzl", "with_postgres_test")

filegroup(
    name = "tauri_conf_json",
    srcs = ["tauri.conf.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "cargo_toml",
    srcs = ["Cargo.toml"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "build_rs",
    srcs = ["build.rs"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "capabilities",
    srcs = glob(["capabilities/**/*"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "icons",
    srcs = glob(["icons/**/*"]),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "srcs_lib",
    srcs = glob(
        ["src/**/*.rs"],
        exclude = ["src/main.rs"],
    ),
    visibility = ["//visibility:public"],
)

filegroup(
    name = "srcs_bin",
    srcs = ["src/main.rs"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "all",
    srcs = [
        ":build_rs",
        ":capabilities",
        ":cargo_toml",
        ":icons",
        ":srcs_bin",
        ":srcs_lib",
        ":tauri_conf_json",
    ],
    visibility = ["//visibility:public"],
)

cargo_build_script(
    name = "build",
    srcs = [":build_rs"],
    build_script_env = {
        "DEP_TAURI_DEV": "false",
    },
    data = [
        ":cargo_toml",
        ":srcs_lib",
        ":tauri_conf_json",
    ],
    deps = [
        "@crates_libraries//:tauri-build",
    ],
)

rust_library(
    name = "applib",
    srcs = [":srcs_lib"],
    compile_data = [
        ":tauri_conf_json",
        ":icons",
        ":capabilities",
    ],
    crate_features = ["postgres"],
    crate_name = "finances_app_lib",
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    deps = all_crate_deps(
        normal = True,
    ) + [
        ":build",
        "//libraries/finances/accounts/rust:finances_accounts",
        "//libraries/finances/investments/rust:finances_investments",
    ],
)

# Unittests
rust_test(
    name = "tests",
    crate = ":applib",
    crate_features = [
        "postgres",
    ],
    data = [
        ":capabilities",
        ":icons",
        ":tauri_conf_json",
    ],
)

# Integration tests
integration_tests_files = glob(["tests/**/test_*.rs"])

rust_test_suite(
    name = "_integration_tests",
    srcs = integration_tests_files,
    crate_features = ["postgres"],
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    shared_srcs = glob(["tests/common/**/*.rs"]),
    tags = [
        "manual",
    ],
    deps = [
        ":applib",
        "//libraries/finances/accounts/rust:finances_accounts/test_utils",
        "@crates_libraries//:serde",
        "@crates_libraries//:serde_json",
        "@crates_libraries//:tauri",
    ],
)

with_postgres_test(
    name = "integration_tests",
    # First migrate,then run the tests
    binaries = [
        "//libraries/finances/investments/django_finances_investments:migrate",
        "//libraries/finances/accounts/django_finances_accounts:populate_test_database",
        "//libraries/finances/investments/django_finances_investments:populate_test_database",
    ] + ["_integration_tests_{}".format(it.replace(".rs", "")) for it in integration_tests_files],  # NOTE: The rust_test_suite is just a group of tests! # TODO: Bazel multicommand!!!
    env = {
        "SQL_ENGINE": "django.db.backends.postgresql",
    },
    env_transpose = {
        "SQL_DATABASE": "POSTGRES_DB",
        "SQL_USER": "POSTGRES_USER",
        "SQL_PASSWORD": "POSTGRES_PASSWORD",
        "SQL_HOST": "POSTGRES_HOST",
        "SQL_PORT": "POSTGRES_PORT",
    },
)

# TODO: Add targets to generate docs and to doc-testing

rust_binary(
    name = "app",
    srcs = [":srcs_bin"],
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    visibility = [
        "//apps/finances:__subpackages__",
    ],
    deps = all_crate_deps(
        normal = True,
    ) + [
        ":applib",
    ],
)
