[package]
name = "finances-app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

[features]
default = ["postgres"]
# sqlite = ["finances_db/sqlite", "diesel/sqlite", "diesel/returning_clauses_for_sqlite_3_35"]
postgres = ["finances_accounts/postgres", "finances_investments/postgres", "diesel/postgres", "diesel/numeric"]

[lib]
name = "finances_app_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.0.3", features = [] }

[dependencies]
finances_accounts = { path = "../../../../libraries/finances/accounts/rust"}
finances_investments = { path = "../../../../libraries/finances/investments/rust" }
openexchangerates = { path = "../../../../libraries/openexchangerates" }

bigdecimal = "0.4.7"
chrono = { version = "0.4.38" }
chrono-tz = { version = "0.10.0" }
diesel = { version = "2.2.6", features = ["r2d2", "chrono"] }

tauri-build = { version = "2.0.3", features = [] } # FIXME: If I don't list it here, Bazel doesn't include it in crate_libraries
tauri = { version = "2.1.1", features = [] }
tauri-plugin-shell = "2.0.2"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.134"
thiserror = "1.0.69"
log = "0.4.22"
tauri-plugin-log = "2.0.3"
itertools = "0.13.0"

[dev-dependencies]
finances_accounts = { path = "../../../../libraries/finances/accounts/rust", features = ["postgres", "test_utils"] }
finances_investments = { path = "../../../../libraries/finances/investments/rust", features = ["postgres"] }
finances-app = { path = ".", default-features = false, features = ["postgres"] }
tauri = { version = "2.1.1", features = ["test"] }
