load("@rules_rust//rust:defs.bzl", "rust_binary")
load("//bazel:value_from_stable_status.bzl", "value_from_stable_status")
load("//bazel/rust:defs.bzl", "rust_library_tests_and_docs")
load("//bazel/rust/diesel:diesel_print_schema.bzl", "diesel_print_schema")
load("//bazel/rust/diesel:diesel_setup.bzl", "diesel_setup")

exports_files(["Cargo.toml"])

value_from_stable_status(
    name = "version",
    default = module_name(),
    key = "STABLE_PHOTODB_VERSION",
    visibility = [":__subpackages__"],
)

# // Working with Diesel requires several targets to create and update the schemas (and an associated database
# // because these schemas are created from the database)

filegroup(
    name = "diesel_config",
    srcs = ["diesel.toml"],
)

filegroup(
    name = "migrations",
    srcs = glob(["migrations/**/*.sql"]),
)

diesel_setup(
    name = "setup",
    config_file = ":diesel_config",
    database_url = "db.sqlite3",
    migrations = [
        "//libraries/filesystem:migrations",
        ":migrations",
    ],
)

diesel_print_schema(
    name = "schema",
    config_file = ":diesel_config",
    database_url = ":setup",
    target = "src/database/schema.rs",
)

rust_library_tests_and_docs(
    name = "photodb_lib",
    srcs = glob(
        ["src/**/*.rs"],
    ),
    compile_data = [":migrations"],
    crate_name = "photodb",
    proc_macro_deps = [
        "//bazel/third_party/crates:async-trait",
        "//bazel/third_party/crates:strum_macros",
    ],
    deps = [
        "//bazel/third_party/crates:anyhow",
        "//bazel/third_party/crates:camino",
        "//bazel/third_party/crates:camino-tempfile",
        "//bazel/third_party/crates:chrono",
        "//bazel/third_party/crates:clap",
        "//bazel/third_party/crates:data-encoding",
        "//bazel/third_party/crates:diesel",
        "//bazel/third_party/crates:diesel_migrations",
        "//bazel/third_party/crates:flume",
        "//bazel/third_party/crates:ignore-files",
        "//bazel/third_party/crates:image",
        "//bazel/third_party/crates:kamadak-exif",
        "//bazel/third_party/crates:lazy_static",
        "//bazel/third_party/crates:log",
        "//bazel/third_party/crates:oxipng",
        "//bazel/third_party/crates:ring",
        "//bazel/third_party/crates:serde",
        "//bazel/third_party/crates:serde_json",
        "//bazel/third_party/crates:strum",
        "//bazel/third_party/crates:tempfile",
        "//bazel/third_party/crates:tokio",
        "//bazel/third_party/crates:tracing",
        "//libraries/diesel_utils",
        "//libraries/filesystem",
        "//libraries/pcloud_sdk",
        "//libraries/utils",
    ],
)

rust_binary(
    name = "photodb",
    srcs = ["src/bin/photodb.rs"],
    deps = [
        ":photodb_lib",
        "//bazel/third_party/crates:anyhow",
        "//bazel/third_party/crates:camino",
        "//bazel/third_party/crates:chrono",
        "//bazel/third_party/crates:clap",
        "//bazel/third_party/crates:clap-verbosity-flag",
        "//bazel/third_party/crates:dirs",
        "//bazel/third_party/crates:log",
        "//bazel/third_party/crates:tokio",
        "//bazel/third_party/crates:tracing",
        "//bazel/third_party/crates:tracing-subscriber",
        "//libraries/filesystem",
        "//libraries/pcloud_sdk",
        "//libraries/utils",
    ],
)
