[package]
name = "photodb"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
filesystem = { path = "../../libraries/filesystem" }

anyhow = { workspace = true }
async-trait = { workspace = true }
camino = { workspace = true }
clap = { workspace = true, features = ["derive"] }
clap-verbosity-flag = { workspace = true }
diesel = { workspace = true, features = ["sqlite"] }
diesel_migrations = { workspace = true }
dotenvy = { workspace = true }
home = { workspace = true }
log = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
filesystem = { path = "../../libraries/filesystem", features = ["local", "test_utils"] }

#[[bin]]
#name = "list_photos"

[[bin]]
name = "photodb"
