load("@bazel_skylib//rules:native_binary.bzl", "native_binary")

native_binary(
    name = "buildx",
    src = select({
        "@bazel_tools//src/conditions:linux_x86_64": "@buildx_linux_amd64//file",
        "@bazel_tools//src/conditions:darwin_arm64": "@buildx_darwin_arm64//file",
        "@bazel_tools//src/conditions:darwin_x86_64": "@buildx_darwin_amd64//file",
    }),
    out = "buildx",
    tags = [
        "manual",
    ],
    visibility = [
        "//containers:__subpackages__",
    ],
)
