load("@aspect_bazel_lib//lib:expand_template.bzl", "expand_template")
load("//bazel/containers/buildx:image_from_dockerfile.bzl", "image_from_dockerfile")
load("//bazel/python/django/containers:defs.bzl", "GROUP", "USER", "USER_UID")

image_name = "deploy_django"

repository = "ghcr.io/jgsogo/{}".format(image_name)  # FIXME: Make it global for all the repo

expand_template(
    name = "dockerfile",
    out = "Dockerfile",
    substitutions = {
        "%USER%": USER,
        "%USER_UID%": USER_UID,
        "%GROUP%": GROUP,
    },
    template = ":Dockerfile.tpl",
)

image_from_dockerfile(
    name = "deploy",
    srcs = [
        ":dockerfile",
    ],
    repository = repository,
    tags = [
        "manual",
    ],
    visibility = [
        "//visibility:public",
    ],
)
