[package]
name = "pcloud_sdk"
version = "0.1.0"
edition = "2021"

[features]
### The `cli` feature is required for the CLI binary. It also provides structs and methods to handle and
### store app authentication. We need to add it ot the "default" features as they are the ones enabled
### while building the CLI "binary"
default = ["cli"]
cli = ["dep:clap-verbosity-flag", "dep:tracing-subscriber", "dep:log", "dep:clap", "use_indicatif"]
use_indicatif = ["dep:indicatif"]
test_utils = ["dep:mockall", "dep:httpmock"]


[dependencies]
http_utils = { path = "../http_utils" }
filesystem = { path = "../filesystem" }

bytes = { workspace = true }
tokio = { workspace = true, features = ["full"] }
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["server"] }
dirs = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true, default-features = false, features = ["alloc"] }
url = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_repr = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
thiserror = { workspace = true }
time = { workspace = true, features = [
    "serde",
    "parsing",
    "formatting",
    "macros",
] }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
chrono-tz = { workspace = true }
cron-parser = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
bitflags = { workspace = true }
itertools = { workspace = true }
camino = { workspace = true, features = ["serde1"] }
headers = { workspace = true }
mime = { workspace = true }
http-body-util = { workspace = true }

# Optional dependencies
indicatif = { workspace = true, optional = true }
mockall = { workspace = true, optional = true }
httpmock = { workspace = true, optional = true }

# Deps for CLI
clap-verbosity-flag = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }
log = { workspace = true, optional = true }
clap = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
tempfile = { workspace = true }
env_logger = { workspace = true }
tracing-subscriber = { workspace = true }
pcloud_sdk = { path = ".", features = ["test_utils"] }

[[bin]]
name = "pcloud_sdk"
path = "src/cli/main.rs"
# Waiting for https://github.com/rust-lang/cargo/issues/4663 (and related: https://github.com/rust-lang/rfcs/pull/3374)
required-features = ["cli"]
