[package]
name = "pcloud_sdk"
version = "0.1.0"
edition = "2021"

[features]
### The `cli` feature is required for the CLI binary. It also provides structs and methods to handle and
### store app authentication. We need to add it ot the "default" features as they are the ones enabled
### while building the CLI "binary"
default = ["bin"]
cli = ["dep:clap-verbosity-flag", "dep:tracing-subscriber", "dep:log", "dep:clap", "use_indicatif"]
use_indicatif = ["dep:indicatif"]
test_utils = ["dep:mockall", "dep:httpmock"]
bin = ["dep:anyhow", "cli"]


[dependencies]
http_utils = { path = "../http_utils" }
utils = { path = "../utils", features = ["filesystem"]}
async_utils = { path = "../async_utils" }

async-trait = { workspace = true }
bitflags = { workspace = true }
bytes = { workspace = true }
camino = { workspace = true, features = ["serde1"] }
dirs = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true, default-features = false, features = ["alloc"] }
headers = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["full"] }
hyper-util = { workspace = true, features = ["server"] }
itertools = { workspace = true }
mime = { workspace = true }
reqwest = { workspace = true, features = ["stream"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_repr = { workspace = true }
strum = { workspace = true, features = ["derive"] }
strum_macros = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, features = [
    "serde",
    "parsing",
    "formatting",
    "macros",
] }
tracing = { workspace = true }
tokio = { workspace = true, features = ["full"] }
url = { workspace = true }

# Optional dependencies
httpmock = { workspace = true, optional = true }
indicatif = { workspace = true, optional = true }
mockall = { workspace = true, optional = true }

# Deps for CLI
clap = { workspace = true, features = ["derive"], optional = true }
clap-verbosity-flag = { workspace = true, optional = true }
log = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

# Deps for binary
anyhow = { workspace = true, optional = true }

[dev-dependencies]
env_logger = { workspace = true }
pcloud_sdk = { path = ".", features = ["test_utils"] }
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }

[[bin]]
name = "pcloud_sdk"
path = "src/bin/pcloud_sdk/main.rs"
# Waiting for https://github.com/rust-lang/cargo/issues/4663 (and related: https://github.com/rust-lang/rfcs/pull/3374)
required-features = ["bin"]
