load("@aspect_rules_ts//ts:defs.bzl", "ts_config", "ts_project")
load("@aspect_rules_ts//ts:proto.bzl", "ts_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")
load("@rules_proto_grpc_cpp//:defs.bzl", "cpp_grpc_library")

proto_library(
    name = "cli_service_proto",
    srcs = ["cli_service.proto"],
    # visibility = ["//visibility:public"],
    deps = [
        "@protobuf//:empty_proto",
    ],
)

cpp_grpc_library(
    name = "cli_service_cpp_grpc",
    protos = [":cli_service_proto"],
    visibility = ["//visibility:public"],
)

proto_library(
    name = "engine_proto",
    srcs = ["engine.proto"],
    # visibility = ["//visibility:public"],
    deps = [
        "@protobuf//:empty_proto",
    ],
)

cpp_grpc_library(
    name = "engine_cpp_grpc",
    protos = [":engine_proto"],
    visibility = ["//visibility:public"],
)

ts_proto_library(
    name = "engine_ts_proto",
    copy_files = True,
    node_modules = "//:node_modules",
    proto = ":engine_proto",
    proto_srcs = ["engine.proto"],
    protoc_gen_options = {
        "import_extension": "js",
    },
    # visibility = ["//visibility:public"],
)

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
)

ts_project(
    name = "engine_proto/ts",
    srcs = [
        "engine_client.ts",
        "package.json",
    ],
    declaration = True,
    source_map = True,
    tsconfig = ":tsconfig",
    visibility = ["//visibility:public"],
    deps = [
        ":engine_ts_proto",
        "//:node_modules",  # TODO: Consume only the required deps
    ],
)
