syntax = "proto3";
package board_game;

import "google/protobuf/empty.proto";


service EngineService {
  rpc CreateNewRoom (NewRoomRequest) returns (google.protobuf.Empty);
  rpc StartGame (StartGameRequest) returns (google.protobuf.Empty);
  rpc GetOrCreateParticipant (GetOrCreateParticipantRequest) returns (Participant);

  rpc SendGameAction(SendGameActionRequest) returns (google.protobuf.Empty);
}

message NewRoomRequest {
  string uuid = 1;
  string name = 2;
}

message StartGameRequest {
  string room_uuid = 1;
  string game_type = 2;
}

message GetOrCreateParticipantRequest {
  string room_uuid = 1;
  string participant_uuid = 2;
  string participant_role = 3;
  optional uint32 player_number = 4;
}

message Participant {
  string room_uuid = 1;
  string uuid = 2;
  string role = 3;
  uint32 player_number = 4;
}

message SendGameActionRequest {
  string room_uuid = 1;
  string participant_uuid = 2;
  bytes payload = 3;
}

message CommandRequest {
  string game_id = 1;
  string player_id = 2;
  bytes payload = 3; // Serialized game-specific command
}

message CommandResponse {
  bool success = 1;
  string message = 2;
}
