syntax = "proto3";
package board_games;

import "google/protobuf/empty.proto";


service EngineService {
  rpc CreateNewRoom (NewRoomRequest) returns (google.protobuf.Empty);
  rpc StartGame (StartGameRequest) returns (google.protobuf.Empty);
  rpc JoinGame(SendActionRequest) returns (google.protobuf.Empty);
  rpc SendAction(SendActionRequest) returns (google.protobuf.Empty);
}

message NewRoomRequest {
  string uuid = 1;
  string name = 2;
}

message StartGameRequest {
  string room_uuid = 1;
  string game_type = 2;
}

message SendActionRequest {
  string room_uuid = 1;
  string participant_uuid = 2;
  bytes payload = 3;
}
