// @generated by protoc-gen-es v2.10.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/engine/protocol/engine.proto (package board_game, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file apps/board_games/engine/protocol/engine.proto.
 */
export declare const file_apps_board_games_engine_protocol_engine: GenFile;

/**
 * @generated from message board_game.NewRoomRequest
 */
export declare type NewRoomRequest = Message<"board_game.NewRoomRequest"> & {
  /**
   * @generated from field: string uuid = 1;
   */
  uuid: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message board_game.NewRoomRequest.
 * Use `create(NewRoomRequestSchema)` to create a new message.
 */
export declare const NewRoomRequestSchema: GenMessage<NewRoomRequest>;

/**
 * @generated from message board_game.StartGameRequest
 */
export declare type StartGameRequest = Message<"board_game.StartGameRequest"> & {
  /**
   * @generated from field: string room_uuid = 1;
   */
  roomUuid: string;

  /**
   * @generated from field: string game_type = 2;
   */
  gameType: string;
};

/**
 * Describes the message board_game.StartGameRequest.
 * Use `create(StartGameRequestSchema)` to create a new message.
 */
export declare const StartGameRequestSchema: GenMessage<StartGameRequest>;

/**
 * @generated from message board_game.GetOrCreateParticipantRequest
 */
export declare type GetOrCreateParticipantRequest = Message<"board_game.GetOrCreateParticipantRequest"> & {
  /**
   * @generated from field: string room_uuid = 1;
   */
  roomUuid: string;

  /**
   * @generated from field: string participant_uuid = 2;
   */
  participantUuid: string;

  /**
   * @generated from field: string participant_role = 3;
   */
  participantRole: string;

  /**
   * @generated from field: optional uint32 player_number = 4;
   */
  playerNumber?: number;
};

/**
 * Describes the message board_game.GetOrCreateParticipantRequest.
 * Use `create(GetOrCreateParticipantRequestSchema)` to create a new message.
 */
export declare const GetOrCreateParticipantRequestSchema: GenMessage<GetOrCreateParticipantRequest>;

/**
 * @generated from message board_game.Participant
 */
export declare type Participant = Message<"board_game.Participant"> & {
  /**
   * @generated from field: string room_uuid = 1;
   */
  roomUuid: string;

  /**
   * @generated from field: string uuid = 2;
   */
  uuid: string;

  /**
   * @generated from field: string role = 3;
   */
  role: string;

  /**
   * @generated from field: uint32 player_number = 4;
   */
  playerNumber: number;
};

/**
 * Describes the message board_game.Participant.
 * Use `create(ParticipantSchema)` to create a new message.
 */
export declare const ParticipantSchema: GenMessage<Participant>;

/**
 * @generated from message board_game.SendActionRequest
 */
export declare type SendActionRequest = Message<"board_game.SendActionRequest"> & {
  /**
   * @generated from field: string room_uuid = 1;
   */
  roomUuid: string;

  /**
   * @generated from field: string participant_uuid = 2;
   */
  participantUuid: string;

  /**
   * @generated from field: bytes payload = 3;
   */
  payload: Uint8Array;
};

/**
 * Describes the message board_game.SendActionRequest.
 * Use `create(SendActionRequestSchema)` to create a new message.
 */
export declare const SendActionRequestSchema: GenMessage<SendActionRequest>;

/**
 * @generated from service board_game.EngineService
 */
export declare const EngineService: GenService<{
  /**
   * @generated from rpc board_game.EngineService.CreateNewRoom
   */
  createNewRoom: {
    methodKind: "unary";
    input: typeof NewRoomRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc board_game.EngineService.StartGame
   */
  startGame: {
    methodKind: "unary";
    input: typeof StartGameRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc board_game.EngineService.GetOrCreateParticipant
   */
  getOrCreateParticipant: {
    methodKind: "unary";
    input: typeof GetOrCreateParticipantRequestSchema;
    output: typeof ParticipantSchema;
  },
  /**
   * @generated from rpc board_game.EngineService.SendAction
   */
  sendAction: {
    methodKind: "unary";
    input: typeof SendActionRequestSchema;
    output: typeof EmptySchema;
  },
}>;

