// @generated by protoc-gen-es v2.10.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file apps/board_games/engine/protocol/engine.proto (package board_games, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { EmptySchema } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file apps/board_games/engine/protocol/engine.proto.
 */
export declare const file_apps_board_games_engine_protocol_engine: GenFile;

/**
 * @generated from message board_games.NewRoomRequest
 */
export declare type NewRoomRequest = Message<"board_games.NewRoomRequest"> & {
  /**
   * @generated from field: string uuid = 1;
   */
  uuid: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message board_games.NewRoomRequest.
 * Use `create(NewRoomRequestSchema)` to create a new message.
 */
export declare const NewRoomRequestSchema: GenMessage<NewRoomRequest>;

/**
 * @generated from message board_games.StartGameRequest
 */
export declare type StartGameRequest = Message<"board_games.StartGameRequest"> & {
  /**
   * @generated from field: string room_uuid = 1;
   */
  roomUuid: string;

  /**
   * @generated from field: string game_type = 2;
   */
  gameType: string;
};

/**
 * Describes the message board_games.StartGameRequest.
 * Use `create(StartGameRequestSchema)` to create a new message.
 */
export declare const StartGameRequestSchema: GenMessage<StartGameRequest>;

/**
 * @generated from message board_games.SendActionRequest
 */
export declare type SendActionRequest = Message<"board_games.SendActionRequest"> & {
  /**
   * @generated from field: string room_uuid = 1;
   */
  roomUuid: string;

  /**
   * @generated from field: string participant_uuid = 2;
   */
  participantUuid: string;

  /**
   * @generated from field: bytes payload = 3;
   */
  payload: Uint8Array;
};

/**
 * Describes the message board_games.SendActionRequest.
 * Use `create(SendActionRequestSchema)` to create a new message.
 */
export declare const SendActionRequestSchema: GenMessage<SendActionRequest>;

/**
 * @generated from service board_games.EngineService
 */
export declare const EngineService: GenService<{
  /**
   * @generated from rpc board_games.EngineService.CreateNewRoom
   */
  createNewRoom: {
    methodKind: "unary";
    input: typeof NewRoomRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc board_games.EngineService.StartGame
   */
  startGame: {
    methodKind: "unary";
    input: typeof StartGameRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc board_games.EngineService.JoinGame
   */
  joinGame: {
    methodKind: "unary";
    input: typeof SendActionRequestSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc board_games.EngineService.SendAction
   */
  sendAction: {
    methodKind: "unary";
    input: typeof SendActionRequestSchema;
    output: typeof EmptySchema;
  },
}>;

