// @generated by protoc-gen-es v2.4.0 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file libraries/googleapis/protos/google/type/date.proto (package google.type, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file libraries/googleapis/protos/google/type/date.proto.
 */
export declare const file_libraries_googleapis_protos_google_type_date: GenFile;

/**
 * @generated from message google.type.Date
 */
export declare type Date = Message<"google.type.Date"> & {
  /**
   * @generated from field: int32 year = 1;
   */
  year: number;

  /**
   * @generated from field: int32 month = 2;
   */
  month: number;

  /**
   * @generated from field: int32 day = 3;
   */
  day: number;
};

/**
 * Describes the message google.type.Date.
 * Use `create(DateSchema)` to create a new message.
 */
export declare const DateSchema: GenMessage<Date>;

