// @generated by protoc-gen-connect-es v1.6.1 with parameter "keep_empty_files=true,target=js+dts,import_extension=js"
// @generated from file libraries/googleapis/protos/google/type/date.proto (package google.type, syntax proto3)
/* eslint-disable */
// @ts-nocheck

