load("//bazel/rust:defs.bzl", "rust_library_tests_and_docs")
load("//bazel/rust/diesel:diesel_print_schema.bzl", "diesel_print_schema")
load("//bazel/rust/diesel:diesel_setup.bzl", "diesel_setup")

exports_files(["Cargo.toml"])

rust_library_tests_and_docs(
    name = "diesel_utils",
    srcs = glob(["src/**/*.rs"]),
    all_features = {
        "sqlite": [
            "sqlite",
        ],
    },
    test_compile_data = glob([
        "tests/common/migrations/**",
    ]),
    test_shared_srcs = glob(
        ["tests/common/**/*.rs"],
    ),
    test_suite_deps = [
        "//bazel/third_party/crates:diesel_migrations",
        "//bazel/third_party/crates:testing_logger",
    ],
    deps = [
        "//bazel/third_party/crates:diesel",
        "//bazel/third_party/crates:log",
        "//bazel/third_party/crates:thiserror",
        "@libpqxx//:libpq",
    ],
)

# Create the schema.rs file for integration tests
filegroup(
    name = "diesel_config",
    srcs = ["tests/common/diesel.toml"],
)

filegroup(
    name = "migrations",
    srcs = glob(["tests/common/migrations/**/*.sql"]),
)

diesel_setup(
    name = "setup",
    config_file = ":diesel_config",
    database_url = "db.sqlite3",
    migrations = [":migrations"],
)

diesel_print_schema(
    name = "schema",
    config_file = ":diesel_config",
    database_url = ":setup",
    target = "tests/common/schema.rs",
)
