load("@crates_libraries//:defs.bzl", "aliases", "all_crate_deps")
load("//bazel/rust:defs.bzl", "rust_library_tests_and_docs")
load("//bazel/rust/diesel:diesel_print_schema.bzl", "diesel_print_schema")
load("//bazel/rust/diesel:diesel_setup.bzl", "diesel_setup")

rust_library_tests_and_docs(
    name = "diesel_utils",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    all_features = {
        "sqlite": [
            "sqlite",
        ],
    },
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    test_compile_data = glob([
        "tests/common/migrations/**",
    ]),
    test_shared_srcs = glob(
        ["tests/common/**/*.rs"],
    ),
    test_suite_deps = [
        "@crates_libraries//:diesel_migrations",
        "@crates_libraries//:testing_logger",
    ],
    deps = all_crate_deps(
        normal = True,
    ),
)

# Create the schema.rs file for integration tests
filegroup(
    name = "diesel_config",
    srcs = ["tests/common/diesel.toml"],
)

filegroup(
    name = "migrations",
    srcs = glob(["tests/common/migrations/**/*.sql"]),
)

diesel_setup(
    name = "setup",
    config_file = ":diesel_config",
    database_url = "db.sqlite3",
    migrations = [":migrations"],
)

diesel_print_schema(
    name = "schema",
    config_file = ":diesel_config",
    database_url = ":setup",
    target = "tests/common/schema.rs",
)
