load("@py_deps//:requirements.bzl", "requirement")
load("//bazel/python/django/app:django_app.bzl", "django_app")

django_app(
    name = "migrate_legacy",
    visibility = ["//apps/finances/django:__subpackages__"],
    deps = [
        requirement("psycopg"),
        requirement("SQLAlchemy"),
        requirement("tqdm"),
        #     requirement("django-money"),
        #     requirement("django-countries"),
        #     requirement("django-appconf"),
    ],
)
