[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[features]
filesystem = ["dep:camino"]
async = ["dep:tokio"]

[dependencies]
log = { workspace = true }
thiserror = { workspace = true }

# filesystem
camino = { workspace = true, optional = true }

# async
tokio = { workspace = true, features = ["full"], optional = true }

[dev-dependencies]
anyhow = { workspace = true }
testing_logger = { workspace = true }
