load("@aspect_rules_ts//ts:defs.bzl", "ts_config", "ts_project")
load("@npm//:vitest/package_json.bzl", vitest_bin = "bin")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

exports_files(["Cargo.toml"])

###########
# Rust library
###########

rust_library(
    name = "models/rust",
    srcs = glob(
        ["src-rust/**/*.rs"],
    ),
    crate_features = ["bazel"],
    crate_name = "finances_app_models",
    visibility = ["//apps/finances/tauri/src-tauri:__subpackages__"],
    deps = [
        "//bazel/third_party/crates:num-bigint",
        "//bazel/third_party/crates:prost",
        "//apps/finances/tauri/models/protos:protos_rs",
        "//libraries/utils/rust/proto_wrapper",
        "//libraries/finances/accounts/rust:finances_accounts",
        # "//libraries/googleapis:googleapis/rust", # FIXME: Rust regenerates the googleapis/protos so we can't reuse here
        "//bazel/third_party/crates:bigdecimal",
        "//bazel/third_party/crates:thiserror",
        "//bazel/third_party/crates:chrono",
        "//bazel/third_party/crates:camino",
    ],
)

# Unittests
rust_test(
    name = "tests",
    crate = ":models/rust",
    crate_features = ["bazel"],
)

###########
# Javascript library
###########

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
)

ts_project(
    name = "models/ts",
    srcs = glob(
        ["src-js/**/*.ts"],
        exclude = [
            "**/*.spec.ts",
            "**/*.test.ts",
        ],
    ) + ["package.json"],
    declaration = True,
    source_map = True,
    tsconfig = ":tsconfig",
    visibility = ["//visibility:public"],
    deps = [
        "//:node_modules/@types/node",
        "//:node_modules/buffer",
        "//:node_modules/decimal.js",
        "//apps/finances/tauri/models/protos:protos_ts",
        "//libraries/googleapis:googleapis/ts",
    ],
)

ts_project(
    name = "src_test_ts",
    srcs = glob([
        "src-js/**/*.spec.ts",
        # "src-js/**/*.test.ts",
    ]) + ["package.json"],
    declaration = True,
    source_map = True,
    tsconfig = ":tsconfig",
    deps = [
        ":models/ts",
        "//:node_modules/vitest",
    ],
)

vitest_bin.vitest_test(
    name = "test.vitest",
    args = ["run"],
    chdir = package_name(),
    data = [
        "package.json",
        ":src_test_ts",
        "//:node_modules",  # TODO: Consume only the required deps
    ],
)
