load("@aspect_rules_jest//jest:defs.bzl", "jest_test")
load("@aspect_rules_js//js:defs.bzl", "js_library")
load("@aspect_rules_ts//ts:defs.bzl", "ts_config", "ts_project")

# load("@aspect_rules_js//js:defs.bzl", "js_library")
# load("@aspect_rules_ts//ts:defs.bzl", "ts_config")
load("@crates_libraries//:defs.bzl", "all_crate_deps")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

# Testing with jest, example: https://github.com/aspect-build/bazel-examples/tree/main/jest
# Maybe: https://stackoverflow.com/questions/59433880/jest-testing-with-bazel-throws-module-ts-jest-in-the-transform-option-was-not-f

npm_link_all_packages(name = "node_modules")

###########
# Rust library
###########

rust_library(
    name = "models/rust",
    srcs = glob(
        ["src-rust/**/*.rs"],
    ),
    crate_features = ["bazel"],
    crate_name = "finances_app_models",
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    visibility = ["//visibility:public"],
    deps = all_crate_deps(
        normal = True,
    ) + [
        "//apps/finances/tauri/models/protos:protos_rs",
    ],
)

# Unittests
rust_test(
    name = "tests",
    crate = ":models/rust",
    crate_features = ["bazel"],
)

###########
# Javascript library
###########

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
)

js_library(
    name = "jest_config",
    srcs = ["jest.config.js"],
)

ts_project(
    name = "lib",
    srcs = glob(
        ["src-js/**/*.ts"],
        exclude = ["**/*.spec.ts"],
    ),
    # out_dir = "dist",
    data = ["package.json"],
    declaration = True,
    source_map = True,
    tsconfig = ":tsconfig",
    # visibility = ["//visibility:public"],
    deps = [
        ":node_modules/@types/node",
        "//apps/finances/tauri/models/protos:protos_ts",
    ],
)

ts_project(
    name = "test_lib",
    srcs = ["src-js/index.spec.ts"],
    declaration = True,
    source_map = True,
    # out_dir = "dist",
    tsconfig = ":tsconfig",
    deps = [
        ":lib",
        ":node_modules/@testing-library/jest-dom",
        ":node_modules/@types/jest",
    ],
)

jest_test(
    name = "test",
    config = ":jest_config",
    data = [
        ":test_lib",
        ":node_modules/jest-environment-jsdom",
        # ":lib",
    ],
    node_modules = ":node_modules",
)

# Exposed via js_library()
js_library(
    name = "pkg",
    srcs = [
        "package.json",
        ":lib",
    ],
    visibility = ["//visibility:public"],
)
