load("@aspect_rules_ts//ts:defs.bzl", "ts_config", "ts_project")
load("@crates_libraries//:defs.bzl", "all_crate_deps")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//sandbox/svelte-hello-world:vitest/package_json.bzl", vitest_bin = "bin")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

npm_link_all_packages(name = "node_modules")

###########
# Rust library
###########

rust_library(
    name = "models/rust",
    srcs = glob(
        ["src-rust/**/*.rs"],
    ),
    crate_features = ["bazel"],
    crate_name = "finances_app_models",
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    visibility = ["//visibility:public"],
    deps = all_crate_deps(
        normal = True,
    ) + [
        "//apps/finances/tauri/models/protos:protos_rs",
        "//libraries/finances/accounts/rust:finances_accounts",
        "//libraries/finances/investments/rust:finances_investments",
        "//libraries/googleapis:googleapis/rust",
    ],
)

# Unittests
rust_test(
    name = "tests",
    crate = ":models/rust",
    crate_features = ["bazel"],
)

###########
# Javascript library
###########

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
)

ts_project(
    name = "models/ts",
    srcs = glob(
        ["src-js/**/*.ts"],
        exclude = [
            "**/*.spec.ts",
            "**/*.test.ts",
        ],
    ) + ["package.json"],
    declaration = True,
    source_map = True,
    tsconfig = ":tsconfig",
    visibility = ["//visibility:public"],
    deps = [
        ":node_modules/@types/node",
        ":node_modules/decimal.js",
        "//apps/finances/tauri/models/protos:protos_ts",
        "//libraries/googleapis:googleapis/ts",
    ],
)

ts_project(
    name = "src_test_ts",
    srcs = glob([
        "src-js/**/*.spec.ts",
        # "src-js/**/*.test.ts",
    ]) + ["package.json"],
    declaration = True,
    source_map = True,
    tsconfig = ":tsconfig",
    deps = [
        ":models/ts",
        ":node_modules/vitest",
    ],
)

vitest_bin.vitest_test(
    name = "test.vitest",
    args = ["run"],
    chdir = package_name(),
    data = [
        "package.json",
        ":node_modules",
        ":src_test_ts",
    ],
)
