[package]
name = "finances-app-models"
version = "0.1.0"
authors = ["you"]
edition = "2021"
description = "Provide the adapter between the diesel models coming from the DB and the types that can be sent to the frontend using protobuf as communication protocol"

include = ["**/*.rs", "Cargo.toml", "protos"]

[lib]
name = "finances_app_models"
path = "src-rust/lib.rs"

[features]
bazel = []

[build-dependencies]
prost-build = { workspace = true }

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
bigdecimal = { workspace = true }
num-bigint = { workspace = true }
diesel = { workspace = true }
thiserror = { workspace = true }

proto_wrapper = { path = "../../../../libraries/rust/proto_wrapper" }
proto_wrapper_derive = { path = "../../../../libraries/rust/proto_wrapper_derive" }
googleapis = { path = "../../../../libraries/googleapis" }
finances_accounts = { path = "../../../../libraries/finances/accounts/rust" }
finances_investments = { path = "../../../../libraries/finances/investments/rust" }
