load("@aspect_bazel_lib//lib:expand_template.bzl", "expand_template")
load("@aspect_rules_js//js:defs.bzl", "js_run_devserver")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//sandbox/tauri-hello-world:@tauri-apps/cli/package_json.bzl", tauri_bin = "bin")
load("//bazel:copy_filegroups.bzl", "copy_filegroups")
load("//bazel/tauri:defs.bzl", "tauri_run")

npm_link_all_packages(name = "node_modules")

filegroup(
    name = "src",
    srcs = glob(["src/**/*.*"]),
)

filegroup(
    name = "static",
    srcs = glob(["static/**/*.*"]),
)

js_run_devserver(
    name = "devserver",
    args = ["dev --config vite.config.js"],
    chdir = package_name(),
    command = "./node_modules/.bin/vite",
    data = [
        # Configs
        "vite.config.js",
        "package.json",
        "tsconfig.json",
        "svelte.config.js",

        # Build deps
        ":node_modules",  # TODO: Use //:node_modules instead

        # Sources
        ":src",
        ":static",
    ],
    grant_sandbox_write_permissions = True,
)

tauri_run(
    name = "dev",
    backend = "//sandbox/tauri-hello-world/src-tauri:app",
    frontend = ":devserver",
)

### Bundling

This PR is broken. Prevent accidental merge

copy_filegroups(
    name = "capabilities",
    strip_prefix = "sandbox/tauri-hello-world",
    targeted_filegroups = [
        "//sandbox/tauri-hello-world/src-tauri:capabilities",
        "//sandbox/tauri-hello-world/src-tauri:icons",
        "//sandbox/tauri-hello-world/src-tauri:srcs",
        "//sandbox/tauri-hello-world/src-tauri:root_files",
    ],
)

expand_template(
    name = "cargo_toml_tpl",
    out = "Cargo.toml",
    template = "//sandbox/tauri-hello-world/src-tauri:Cargo.toml",
)

copy_filegroups(
    name = "cargo_toml",
    folder = "src-tauri",
    strip_prefix = "sandbox/tauri-hello-world",
    targeted_filegroups = [
        ":cargo_toml_tpl",
    ],
)

tauri_bin.tauri_binary(
    name = "tauri_binary",
    args = ["build"],
    data = [
        # Configs
        "vite.config.js",
        "package.json",
        "tsconfig.json",
        "svelte.config.js",

        # Build deps
        ":node_modules",  # TODO: Use //:node_modules instead

        # Sources
        ":src",
        ":static",

        # Rust
        ":capabilities",
        ":cargo_toml",
    ],
)
