load("@rules_pkg//pkg:mappings.bzl", "pkg_attributes", "pkg_filegroup", "pkg_files")
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")
load("//apps/finances/installable:defs.bzl", "BIN_FOLDER", "MACOS_APPLICATION_QT_CONTENTS", "MACOS_APPLICATION_QT_CONTENTS_MACOS", "NAME")

# The application itself
pkg_tar(
    name = "app-finances-qt-tar",
    srcs = [
        "//apps/finances:finances-qt-app",
    ],
    include_runfiles = True,
    mode = "0551",
    tags = [
        "manual",
        "no-remote-cache",
    ],
)

pkg_files(
    name = "bin",
    srcs = [
        ":app-finances-qt-tar",
    ],
    include_runfiles = True,
    prefix = BIN_FOLDER,
)

genrule(
    name = "finances-app-gen",
    outs = ["finances-app-executable"],
    cmd = """
        echo "#!/usr/bin/env bash" > $@
        echo "/usr/local/{}/bin/finances-qt" >> $@
    """.format(NAME),
    executable = True,
)

pkg_files(
    name = "finances-app",
    srcs = [
        ":finances-app-gen",
    ],
    attributes = pkg_attributes(
        # group = "admin",
        mode = "0551",  # Executable
        # owner = "root",
    ),
    prefix = MACOS_APPLICATION_QT_CONTENTS_MACOS,
)

# The Info.plist file
# TODO: Create this Info.plist from a template and pass the values
pkg_files(
    name = "info-plist",
    srcs = [
        ":Info.plist",
    ],
    prefix = MACOS_APPLICATION_QT_CONTENTS,
)

# Group all files together
pkg_filegroup(
    name = "application-qt",
    srcs = [
        ":bin",
        ":finances-app",
        ":info-plist",
    ],
    visibility = ["//apps/finances/installable:__subpackages__"],
)
