load("@rules_qt//qt:qt_cc_library.bzl", "qt_cc_library")

qt_cc_library(
    name = "widgets",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob(["**/*.h"]),
    visibility = ["//apps/finances/qt:__subpackages__"],
    deps = [
        "//apps/finances/qt/models",
        "//apps/finances/qt/widgets/accounts:interface",
        "//bazel/logging:spdlog",
        "//libraries/finances/investments/cpp/models",
        "@rules_qt//:qt_widgets",
    ],
)
