load("@aspect_bazel_lib//lib:expand_template.bzl", "expand_template")
load("//bazel/containers/with_docker:with_docker_binary.bzl", "with_docker_compose")

expand_template(
    name = "expose_postgresql",
    out = "expose_postgresql.yaml",
    tags = [
        "manual",
    ],
    template = [
        "services:",
        "  db:",
        "    ports:",
        "      - 5431:5432",
        "",
    ],
)

filegroup(
    name = "diesel_config",
    srcs = ["diesel.toml"],
    tags = [
        "manual",
    ],
)

with_docker_compose(
    name = "schema_gen",
    cmd = "./$(rootpath @diesel_cli//:diesel_cli) print-schema --database-url postgres://diesel-schema:diesel-schema@127.0.0.1:5431/diesel-schema > $BUILD_WORKSPACE_DIRECTORY/apps/finances/desktop/src/schema.postgres.rs",
    docker_compose = [
        "//apps/finances/django:app-docker_compose",
        ":expose_postgresql",
    ],
    docker_services = [
        "web",
        "db",
    ],
    env = {
        "SECRET_KEY": "not-for-production",
        "SQL_USER": "diesel-schema",
        "SQL_DATABASE": "diesel-schema",
        "SQL_PASSWORD": "diesel-schema",
    },
    tags = [
        "update",
    ],
    tools = ["@diesel_cli"],
)
