load("@rules_qt//qt:qt_cc_library.bzl", "qt_cc_library")

qt_cc_library(
    name = "transactions",
    srcs = [
        "add_transaction.cpp",
        "movements/add_movement.cpp",
    ],
    hdrs = [
        "add_transaction.h",
        "movements/add_movement.h",
    ],
    visibility = ["//apps/finances/qt:__subpackages__"],
    deps = [
        "//apps/finances/qt/models",
        "//apps/finances/qt/widgets/forms/amounts",
        "//bazel/logging:spdlog",
        "@rules_qt//:qt_widgets",
    ],
)
