load("@aspect_rules_js//js:defs.bzl", "js_run_devserver")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("//bazel/containers/with_docker:with_postgres_run.bzl", "with_postgres_run")
load("//bazel/run:defs.bzl", "run_together")

npm_link_all_packages(name = "node_modules")

filegroup(
    name = "src",
    srcs = glob(["src/**/*.*"]),
)

filegroup(
    name = "static",
    srcs = glob(["static/**/*.*"]),
)

filegroup(
    name = "configs",
    srcs = [
        "svelte.config.js",
        "tsconfig.json",
        "vite.config.ts",
    ],
)

js_run_devserver(
    name = "devserver",
    args = ["dev --config vite.config.ts"],
    chdir = package_name(),
    command = "./node_modules/.bin/vite",
    data = [
        # Configs
        "package.json",

        # Build deps
        ":node_modules",

        # Sources
        ":configs",
        ":src",
        ":static",
    ],
    grant_sandbox_write_permissions = True,
)

run_together(
    name = "engine+devserver",
    after = ":devserver",
    before = "//apps/board_games/engine",
)

with_postgres_run(
    name = "dev",
    binaries = [
        "//apps/board_games/database:_migrate",
        "//apps/board_games/database:_populate_test_database",
        ":engine+devserver",
    ],
    env = {
        "BOARD_GAMES_DATABASE_DJANGO_SQL_ENGINE": "django.db.backends.postgresql",
    },
    env_transpose = {
        # Envvars for the 'database' component
        "BOARD_GAMES_DATABASE_DJANGO_SQL_DATABASE": "POSTGRES_DB",
        "BOARD_GAMES_DATABASE_DJANGO_SQL_USER": "POSTGRES_USER",
        "BOARD_GAMES_DATABASE_DJANGO_SQL_PASSWORD": "POSTGRES_PASSWORD",
        "BOARD_GAMES_DATABASE_DJANGO_SQL_HOST": "POSTGRES_HOST",
        "BOARD_GAMES_DATABASE_DJANGO_SQL_PORT": "POSTGRES_PORT",

        # Envvars for the 'engine' component
        "BOARD_GAMES_ENGINE_SQL_DATABASE": "POSTGRES_DB",
        "BOARD_GAMES_ENGINE_SQL_USER": "POSTGRES_USER",
        "BOARD_GAMES_ENGINE_SQL_PASSWORD": "POSTGRES_PASSWORD",
        "BOARD_GAMES_ENGINE_SQL_HOST": "POSTGRES_HOST",
        "BOARD_GAMES_ENGINE_SQL_PORT": "POSTGRES_PORT",
    },
)
