"""
A collection of utilities for libpqxx
"""

load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "connection_pool",
    srcs = ["connection_pool.cpp"],
    hdrs = ["connection_pool.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//bazel/logging:spdlog",
        "@libpqxx",
    ],
)

cc_library(
    name = "notify",
    srcs = ["notify.cpp"],
    hdrs = ["notify.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//bazel/logging:spdlog",
        "@libpqxx",
    ],
)
