load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")
load("//bazel:sh_with_runfiles_binary.bzl", "sh_with_runfiles_binary")
load("//bazel/containers/with_docker:with_postgres_run.bzl", "with_postgres_run", "with_postgres_test")

exports_files(["Cargo.toml"])

rust_library(
    name = "finances_accounts",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["postgres"],
    visibility = [
        "//apps/finances:__subpackages__",
        "//libraries/finances:__subpackages__",
    ],
    deps = [
        "//bazel/third_party/crates:bigdecimal",
        "//bazel/third_party/crates:chrono",
        "//bazel/third_party/crates:diesel",
    ],
)

rust_library(
    name = "finances_accounts/test_utils",
    srcs = glob(["src/**/*.rs"]),
    crate_features = [
        "postgres",
        "test_utils",
    ],
    crate_name = "finances_accounts",
    visibility = [
        "//apps/finances:__subpackages__",
        "//libraries/finances:__subpackages__",
    ],
    deps = [
        "//bazel/third_party/crates:bigdecimal",
        "//bazel/third_party/crates:chrono",
        "//bazel/third_party/crates:diesel",
    ],
)

# FIXME: This binary is a bit convoluted: it depends on the 'finances_accounts' library
# to generate the 'constants.rs' file which is included in the library itself.
# Now that we have the '//libraries/finances/accounts/fixtures/migration' available, we
# can use those files to generate these constants. It can be a pre-build step and it will
# let us remove some of these targets ('update' ones are evil)
rust_binary(
    name = "gen_constants",
    srcs = glob(["src/gen_constants/bin/**/*.rs"]),
    visibility = ["//libraries/finances/investments/rust:__subpackages__"],
    deps = [
        ":finances_accounts",
        "//bazel/third_party/crates:anyhow",
        "//bazel/third_party/crates:camino",
        "//bazel/third_party/crates:clap",
        "//bazel/third_party/crates:clap-verbosity-flag",
        "//bazel/third_party/crates:diesel",
        "//bazel/third_party/crates:log",
        "//bazel/third_party/crates:tracing",
        "//bazel/third_party/crates:tracing-subscriber",
    ],
)

# Unittests... marked as 'manual' because they require Postgres
rust_test(
    name = "_tests",
    crate = ":finances_accounts",
    crate_features = [
        "postgres",
        "test_utils",
    ],
    tags = ["manual"],
    deps = [
        "//bazel/third_party/crates:anyhow",
        "//bazel/third_party/crates:lazy_static",
        "//bazel/third_party/crates:tempfile",
    ],
)

with_postgres_test(
    name = "tests-postgres",
    # First migrate, then populate the database, then run the tests
    binaries = [
        "//libraries/finances/accounts/django_finances_accounts:migrate",
        "//libraries/finances/accounts/django_finances_accounts:populate_test_database",
        ":_tests",
    ],
    env = {
        "DJANGO_SQL_ENGINE": "django.db.backends.postgresql",
    },
    env_transpose = {
        "DJANGO_SQL_DATABASE": "POSTGRES_DB",
        "DJANGO_SQL_USER": "POSTGRES_USER",
        "DJANGO_SQL_PASSWORD": "POSTGRES_PASSWORD",
        "DJANGO_SQL_HOST": "POSTGRES_HOST",
        "DJANGO_SQL_PORT": "POSTGRES_PORT",
    },
)

###
# Scripts executed at build time. These generate source files
###

# Generate schema files
sh_with_runfiles_binary(
    name = "diesel_print_schema",
    args = [
        "print-schema",
        "--only-tables",
        "finances_accounts",
        "--database-url",
        "$$POSTGRES_URL",
        "> $$BUILD_WORKSPACE_DIRECTORY/" + package_name() + "/src/schema/schema_postgres.rs",
    ],
    tool = "@diesel_cli",
)

# Generate constants.rs file
sh_with_runfiles_binary(
    name = "gen_constants_bin",
    args = [
        "--output-file",
        "$$BUILD_WORKSPACE_DIRECTORY/" + package_name() + "/src/constants.rs",
        "--database-url",
        "$$POSTGRES_URL",
    ],
    tool = ":gen_constants",
)

with_postgres_run(
    name = "codegen",
    # First migrate,then print the schema
    binaries = [
        "//libraries/finances/accounts/django_finances_accounts:migrate",
        ":diesel_print_schema",
        ":gen_constants_bin",
    ],
    env = {
        "DJANGO_SQL_ENGINE": "django.db.backends.postgresql",
    },
    env_transpose = {
        "DJANGO_SQL_DATABASE": "POSTGRES_DB",
        "DJANGO_SQL_USER": "POSTGRES_USER",
        "DJANGO_SQL_PASSWORD": "POSTGRES_PASSWORD",
        "DJANGO_SQL_HOST": "POSTGRES_HOST",
        "DJANGO_SQL_PORT": "POSTGRES_PORT",
    },
    tags = [
        "manual",
        "update",
    ],
)
