load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@bazel_skylib//rules:diff_test.bzl", "diff_test")
load("@rules_shell//shell:sh_test.bzl", "sh_test")
load("//bazel:run_copy_to_workspace.bzl", "run_copy_to_workspace")

genrule(
    name = "svg",
    srcs = ["data.textproto"],
    outs = ["routes.svg"],
    cmd = "$(location //apps/board_games/games/ticket_to_ride/maps/gen) --textproto=$(location :data.textproto) --output=$@",
    tools = [
        "//apps/board_games/games/ticket_to_ride/maps/gen",
    ],
)

# Convert textproto file into binary format (JS doesn't know how to read textproto format)
genrule(
    name = "data-bin",
    srcs = [
        "data.textproto",
        "//apps/board_games/games/ticket_to_ride/maps:map_proto_file",
    ],
    outs = ["data.bin"],
    cmd = """
        $(location @protobuf//:protoc) \\
            --encode=board_games.ticket_to_ride.MapData  \\
            -I $$(dirname $(location //apps/board_games/games/ticket_to_ride/maps:map_proto_file))  \\
            $(location //apps/board_games/games/ticket_to_ride/maps:map_proto_file) \\
            < $(location data.textproto) \\
            > $@
        """,
    tools = [
        "@protobuf//:protoc",
    ],
)

filegroup(
    name = "usa",
    srcs = [
        "background.svg",
        ":data-bin",
        ":svg",
    ],
    visibility = [
        "//apps/board_games/games/ticket_to_ride/engine:__subpackages__",
    ],
)

ts_project(
    name = "usa-js",
    srcs = [
        "index.ts",
        "package.json",
    ],
    data = [
        ":usa",
    ],
    declaration = True,
    source_map = True,
    tsconfig = "//apps/board_games/games/ticket_to_ride/maps:tsconfig",
    visibility = [
        "//apps/board_games/games/ticket_to_ride/maps:__pkg__",
        "//apps/board_games/webapp:__subpackages__",
    ],
    deps = [
        "//:node_modules/@types/node",
    ],
)

# Keep repository file updated
run_copy_to_workspace(
    name = "svg.update",
    origin = ":svg",
    tags = [
        "manual",
        "update",
    ],
    target = "usa-routes.svg",
)

diff_test(
    name = "svg.update.test",
    failure_message = "\n\nRun `bazel run {}:svg.update` to update the schema file".format(package_name()),
    file1 = ":svg",
    file2 = "usa-routes.svg",
    tags = ["check"],
)

# Run tests on the input file
genrule(
    name = "test.map.build",
    testonly = True,
    srcs = [
        ":data.textproto",
    ],
    outs = ["test.map.build.sh"],
    cmd = """
        echo '#!/bin/bash' > $@
        echo '$(rootpath //apps/board_games/games/ticket_to_ride/maps/tests:test_map) \\' >> $@
        echo '  --textproto=$(location :data.textproto) \' >> $@
    """,
    executable = True,
    tools = [
        "//apps/board_games/games/ticket_to_ride/maps/tests:test_map",
    ],
    visibility = ["//visibility:private"],
)

sh_test(
    name = "test.map",
    srcs = [":test.map.build"],
    data = [
        ":data.textproto",
        "//apps/board_games/games/ticket_to_ride/maps/tests:test_map",
    ],
)
