load("//bazel/python/django/app:django_app.bzl", "django_app")
load("//bazel:sh_with_runfiles_binary.bzl", "sh_with_runfiles_binary")

django_app(
    name = "finances_investments",
    visibility = ["//visibility:public"],
    deps = [
        "//libraries/finances/accounts/django_finances_accounts:finances_accounts",
    ],
)

sh_with_runfiles_binary(
    name = "populate_test_database",
    args = [
        "finances_investments_test_data",
    ],
    tags = ["manual"],
    tool = ":django-admin",
    visibility = ["//visibility:public"],
)
