load("@crates_libraries//:defs.bzl", "aliases", "all_crate_deps")
load("@totum//bazel/rust:defs.bzl", "rust_library_tests_and_docs")

rust_library_tests_and_docs(
    name = "filesystem_database",
    srcs = glob(["src/**/*.rs"]),
    aliases = aliases(),
    proc_macro_deps = all_crate_deps(
        proc_macro = True,
    ),
    # test_deps = [
    #     "@crates_libraries//:anyhow",
    # ],
    # test_suite_deps = [
    #     "@crates_libraries//:anyhow",
    # ],
    deps = all_crate_deps(
        normal = True,
    ) + [
        "@totum//libraries/diesel_utils",
        "@totum//libraries/filesystem",
    ],
)
