[package]
name = "filesystem_database"
version = "0.1.0"
edition = "2021"

[features]
default = ["diesel"]
diesel = ["dep:diesel", "dep:diesel_utils"]

[dependencies]
filesystem = { path = "../filesystem" }

async-trait = { workspace = true }
camino = { workspace = true }
 flume = { workspace = true }
# headers = { workspace = true }
# tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

# Diesel backend
diesel = { workspace = true, optional = true }
diesel_utils = { path = "../diesel_utils", optional = true }

[dev-dependencies]
