FROM ubuntu:22.04

# Install dependencies (for Bazel)
RUN apt-get update && apt-get install -y \
    curl \
    git \
    jq \
    bash \
    sudo \
    unzip

# Install dependencies (for Tauri v2): https://v2.tauri.app/start/prerequisites/#linux
RUN apt-get install -y \
    libwebkit2gtk-4.1-dev \
    build-essential \
    curl \
    wget \
    file \
    libxdo-dev \
    libssl-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev

RUN rm -rf /var/lib/apt/lists/*

# Set environment variables
ENV RUNNER_USER=runner
ENV RUNNER_WORKDIR=/home/runner/actions-runner

# Create a user and working directory
RUN useradd -m $RUNNER_USER && mkdir -p $RUNNER_WORKDIR && chown -R $RUNNER_USER:$RUNNER_USER $RUNNER_WORKDIR
WORKDIR $RUNNER_WORKDIR
USER $RUNNER_USER

# Download and extract the GitHub Actions Runner
RUN curl -o actions-runner-linux-x64-2.322.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.322.0/actions-runner-linux-x64-2.322.0.tar.gz && \
    echo "b13b784808359f31bc79b08a191f5f83757852957dd8fe3dbfcc38202ccf5768  actions-runner-linux-x64-2.322.0.tar.gz" | shasum -a 256 -c && \
    tar xzf ./actions-runner-linux-x64-2.322.0.tar.gz && \
    rm actions-runner-linux-x64-2.322.0.tar.gz

# Copy entrypoint script
COPY entrypoint.sh /entrypoint.sh
# RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
