FROM ubuntu:22.04

# Install dependencies (for Bazel)
RUN apt-get update && apt-get install -y \
    curl \
    git \
    jq \
    bash \
    sudo \
    unzip \
    wget \
    default-jdk \
    docker.io

# Install GH CLI
RUN mkdir -p -m 755 /etc/apt/keyrings \
    && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    && cat $out | tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& apt update \
	&& apt install gh -y

# Install dependencies (for Tauri v2): https://v2.tauri.app/start/prerequisites/#linux
RUN apt-get install -y \
    libwebkit2gtk-4.1-dev \
    build-essential \
    curl \
    wget \
    file \
    libxdo-dev \
    libssl-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev

RUN rm -rf /var/lib/apt/lists/*

# Install bazelisk
RUN wget https://github.com/bazelbuild/bazelisk/releases/download/v1.25.0/bazelisk-linux-amd64 && \
    chmod +x bazelisk-linux-amd64 && \
    mv bazelisk-linux-amd64 /usr/local/bin/bazel

# Set environment variables
ENV RUNNER_USER=runner
ENV RUNNER_WORKDIR=/home/runner/actions-runner

# Create a user and working directory
RUN useradd -m $RUNNER_USER && mkdir -p $RUNNER_WORKDIR && chown -R $RUNNER_USER:$RUNNER_USER $RUNNER_WORKDIR
WORKDIR $RUNNER_WORKDIR
USER $RUNNER_USER

# Download and extract the GitHub Actions Runner
RUN curl -o actions-runner-linux-x64-2.322.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.322.0/actions-runner-linux-x64-2.322.0.tar.gz && \
    echo "b13b784808359f31bc79b08a191f5f83757852957dd8fe3dbfcc38202ccf5768  actions-runner-linux-x64-2.322.0.tar.gz" | shasum -a 256 -c && \
    tar xzf ./actions-runner-linux-x64-2.322.0.tar.gz && \
    rm actions-runner-linux-x64-2.322.0.tar.gz

# Copy entrypoint script
COPY entrypoint.sh /entrypoint.sh
# RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
