# Generated by Django 5.1.2 on 2024-10-29 18:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finances_accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovementDividend",
            fields=[
                (
                    "movement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="finances_accounts.movement",
                    ),
                ),
                (
                    "ex_dividend_date",
                    models.DateField(
                        help_text="Date when the dividend is assigned. This data is used to retrieve the number of stocks"
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Dividen per stock",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Unit value should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("finances_accounts.movement",),
        ),
        migrations.CreateModel(
            name="MovementNumerable",
            fields=[
                (
                    "movement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="finances_accounts.movement",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Number of units. Typically this will be an integer, but some accounts allow fractional units",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Quantity should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Value per unit in object's currency",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Unit value should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("finances_accounts.movement", models.Model),
        ),
        migrations.CreateModel(
            name="SnapshotNumerable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "date_value",
                    models.DateField(
                        help_text="Date corresponding to this snapshot. It should be a working day, so the FX can be retrieved from official sources"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Number of units. Typically this will be an integer, but some accounts allow fractional units",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Quantity should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Value per unit in object's currency",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Unit value should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Account this snapshot refers to",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finances_accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_value"],
                "abstract": False,
                "unique_together": {("account", "date_value")},
            },
        ),
    ]
