# Generated by Django 5.1.2 on 2024-11-29 09:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finances_accounts", "0009_alter_accountholder_options_alter_custodian_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovementDividend",
            fields=[
                (
                    "movement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="finances_accounts.movement",
                    ),
                ),
                (
                    "ex_dividend_date",
                    models.DateField(
                        help_text="Date when the dividend is assigned. This data is used to retrieve the number of stocks"
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Dividen per stock",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Unit value should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("finances_accounts.movement",),
        ),
        migrations.CreateModel(
            name="MovementNumerable",
            fields=[
                (
                    "movement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="finances_accounts.movement",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Number of units. Typically this will be an integer, but some accounts allow fractional units",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Quantity should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Value per unit in object's currency",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Unit value should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("finances_accounts.movement", models.Model),
        ),
        migrations.CreateModel(
            name="SnapshotNumerable",
            fields=[
                (
                    "snapshot_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="finances_accounts.snapshot",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Number of units. Typically this will be an integer, but some accounts allow fractional units",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Quantity should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Value per unit in object's currency",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, "Unit value should be equal or greater than 0"
                            )
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("finances_accounts.snapshot", models.Model),
        ),
    ]
