# Generated by Django 5.1.2 on 2024-11-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances_investments", "0004_data_movementtype"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movementdividend",
            options={"ordering": ["-date_value"]},
        ),
        migrations.AlterModelOptions(
            name="movementnumerable",
            options={"ordering": ["-date_value"]},
        ),
        migrations.AlterModelOptions(
            name="snapshotnumerable",
            options={"ordering": ["-date_value"]},
        ),
    ]
