# Generated by Django 5.2 on 2025-05-10 16:12

from django.conf import settings
from django.db import migrations
from django.utils.translation import gettext_lazy as _

from ..constants import MovementTypeConstants


def populate_optional_movementtypes(apps, schema_editor):
    if settings.FINANCES_MIGRATE_ONLY_REQUIRED_MOVMENTTYPES:
        return

    MovementType = apps.get_model("finances_accounts", "MovementType")

    inversiones = MovementType.objects.get(unique_name=MovementTypeConstants.INVESTMENTS)

    # / Ingresos / Inversiones
    MovementType.objects.bulk_create(
        [
            MovementType(tn_parent=inversiones, name=_("QIE Distribution Capital Gain")),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("finances_investments", "0005_alter_movementdividend_options_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_optional_movementtypes),
    ]
