load("//bazel/python/django/project:django_project.bzl", "django_project")

name = "app"

django_project(
    name = name,
    srcs = [
        "settings.py",
        "urls.py",
    ],
    visibility = ["//apps/finances:__subpackages__"],
    deps = [
        "//apps/board_games/database/core:board_games_core",
    ],
)
