"""A very opinionated Bazel macro to create the targets for a Django application"""

load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_library")
load("@py_deps//:requirements.bzl", "requirement")
load("//bazel/python/django/app:makemigrations.bzl", "django_makemigrations_check", "django_makemigrations_update")
load("//bazel/python/django/app:migrate.bzl", "django_migrate")
load("//bazel/python/django/app:test.bzl", "django_test")

def django_app(name, deps = None, visibility = None, app_label = None):
    """
    A very opinionated macro to create a Django application.

    This macro should be called from the root of a Django application, and
    it will take care of creating all the relevant targets:

    ```
    load("@py_deps//:requirements.bzl", "requirement")
    load("//bazel/python/django/app:django_app.bzl", "django_app")

    django_app(
        name = "myapp",
        visibility = ["//visibility:public"],
        deps = [
            requirement("django-money"),
            requirement("django-countries"),
            requirement("django-appconf"),
        ],
    )
    ```

    Targets generated by this macro:
    * <package>:<name> - The py_library with the application (it doesn't include test files, but includes templates, static and fixture files)
    * <package>:<name>/fixtures - Only the fixture files
    * <package>:<name>/static - Static files
    * <package>:<name>/templates - Template files
    * <package>:django-admin - A py_binary that can be used to run django-admin in this application
    * <package>:unittests - A test target to execute all the tests
    * <package>:makemigrations.check - A run target that can be used to check if there are some pending migrations (not created yet)
    * <package>:makemigrations - A run target that can be used to create any pending migrations and update the workspace

    Args:
        name(str): The name of the application
        deps(list): A list of dependencies
        visibility: The visibility for the py_library
        app_label: Short name for the application
    """

    app_label = app_label or name

    # Collect all possible fixture files (all formats, all compressions)
    fixture_extensions = ["xml", "json", "jsonl", "yaml"]
    fixture_compression_formats = ["zip", "gz", "bz2", "lzma", "xz"]
    all_extensions = fixture_extensions + ["{}.{}".format(it1, it2) for it1 in fixture_extensions for it2 in fixture_compression_formats]
    native.filegroup(
        name = "{}/fixtures".format(name),
        srcs = native.glob(["fixtures/**/*.{}".format(ext) for ext in all_extensions]),
    )

    native.filegroup(
        name = "{}/static".format(name),
        srcs = native.glob(["static/**/*.*"]),
    )

    native.filegroup(
        name = "{}/templates".format(name),
        srcs = native.glob(["templates/**/*.html"]),
    )

    deps = depset([requirement("django")] + (deps or [])).to_list()

    py_library(
        name = name,
        # Includes only the actual application files. Tests and management commands are not part of the library
        srcs = native.glob(
            ["**/*.py"],
            exclude = [
                "tests/**/*.*",
                "run_local.py",
            ],
        ),
        data = [
            ":{}/fixtures".format(name),
            ":{}/static".format(name),
            ":{}/templates".format(name),
        ],
        imports = ["../"],
        deps = deps,
        visibility = visibility,
    )

    # The "local" django-admin executable
    py_binary(
        name = "django-admin",
        srcs = ["run_local.py"],
        imports = ["."],
        main = "run_local.py",
        deps = [
            ":{}".format(name),
            requirement("psycopg"),  # Required because deployments can use Postgres
        ],
    )

    # The test target for this application
    django_test(
        name = "unittests",
        srcs = native.glob(["tests/**/*.py"]),  # Include the test files here
        django_admin_tool = ":django-admin",
    )

    # makemigrations - Creates pending migrations (it fails if user input is required)
    django_makemigrations_check(
        name = "makemigrations.check",
        app_label = app_label,
        django_admin_tool = ":django-admin",
        deps = ["@bazel_tools//tools/bash/runfiles"],
        tags = ["check"],
        update_rule = ":makemigrations",
    )

    django_makemigrations_update(
        name = "makemigrations",
        app_label = app_label,
        django_admin_tool = ":django-admin",
        deps = ["@bazel_tools//tools/bash/runfiles"],
        tags = ["manual"],
    )

    django_migrate(
        name = "migrate",
        django_admin_tool = ":django-admin",
        tags = ["manual"],
        visibility = ["//:__subpackages__"],
    )
