load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel/containers/postgres:with_postgres_run.bzl", "with_postgres_run")

cc_library(
    name = "plugin",
    srcs = [],
    hdrs = ["game_plugin.hpp"],
    visibility = [
        "//apps/board_games/engine/services:__subpackages__",
        "//apps/board_games/games:__subpackages__",
    ],
    deps = [
        "//apps/board_games/engine/data",
        "//apps/board_games/engine/data/models",
        "@spdlog",
        "@tl-expected",
    ],
)

cc_binary(
    name = "engine",
    srcs = ["main.cpp"],
    defines = [
        "SPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_TRACE",
    ],
    visibility = ["//apps/board_games:__subpackages__"],
    deps = [
        ":plugin",
        "//apps/board_games/engine/services",
        "//apps/board_games/games/tic_tac_toe/engine",
        "//libraries/utils/cpp/db",
        "@spdlog",
    ],
)

with_postgres_run(
    name = "dev",
    testonly = True,
    binaries = [
        "//apps/board_games/database:app-migrate",
        "//apps/board_games/database:_populate_test_database",
        ":engine",
    ],
    env = {
        "BOARD_GAMES_DATABASE_DJANGO_SQL_ENGINE": "django.db.backends.postgresql",
    },
    env_transpose = {
        # Envvars for the 'database' component
        "BOARD_GAMES_DATABASE_DJANGO_SQL_DATABASE": "POSTGRES_DB",
        "BOARD_GAMES_DATABASE_DJANGO_SQL_USER": "POSTGRES_USER",
        "BOARD_GAMES_DATABASE_DJANGO_SQL_PASSWORD": "POSTGRES_PASSWORD",
        "BOARD_GAMES_DATABASE_DJANGO_SQL_HOST": "POSTGRES_HOST",
        "BOARD_GAMES_DATABASE_DJANGO_SQL_PORT": "POSTGRES_PORT",

        # Envvars for the 'engine' component
        "BOARD_GAMES_ENGINE_SQL_DATABASE": "POSTGRES_DB",
        "BOARD_GAMES_ENGINE_SQL_USER": "POSTGRES_USER",
        "BOARD_GAMES_ENGINE_SQL_PASSWORD": "POSTGRES_PASSWORD",
        "BOARD_GAMES_ENGINE_SQL_HOST": "POSTGRES_HOST",
        "BOARD_GAMES_ENGINE_SQL_PORT": "POSTGRES_PORT",
    },
)
