load("@rules_pkg//pkg:mappings.bzl", "pkg_files")

genrule(
    name = "app_wrapper",
    outs = ["app.sh"],
    cmd = """
        echo "#!/usr/bin/env bash" > $@
        echo "set -euo pipefail" >> $@
        echo "export POSTGRES_USER=finances" >> $@
        echo "export POSTGRES_PASSWORD=finances" >> $@
        echo "export POSTGRES_HOST=localhost" >> $@
        echo "export POSTGRES_PORT=5432" >> $@
        echo "export POSTGRES_DB=finances_v2" >> $@
        echo "export DJANGO_BASE_URL=http://localhost.finances2" >> $@
        echo "export MEDIA_URL=media" >> $@
        echo "export STATIC_URL=static" >> $@
        echo 'DIR="$$(dirname "$$0")"' >> $@
        echo 'exec "$$DIR/app"' >> $@
    """,
    executable = True,
)

pkg_files(
    name = "app",
    srcs = [
        ":app_wrapper",
        "//apps/finances/tauri/src-tauri:app",
    ],
    prefix = "MacOS",
    visibility = ["//apps/finances/tauri/installable:__subpackages__"],
)
