load("//bazel/rust:defs.bzl", "rust_library_tests_and_docs")

exports_files(["Cargo.toml"])

rust_library_tests_and_docs(
    name = "conductus",
    srcs = glob(["src/**/*.rs"]),
    all_features = {
        "sync": [
            "sync",
        ],
        "tokio-async": [
            "tokio-async",
        ],
    },
    proc_macro_deps = [
        "//bazel/third_party/crates:async-trait",
    ],
    deps = [
        "//bazel/third_party/crates:flume",
        "//bazel/third_party/crates:futures",
        "//bazel/third_party/crates:log",
        "//bazel/third_party/crates:tokio",
        "//bazel/third_party/crates:tokio-stream",
        "//bazel/third_party/crates:tracing",
    ],
)
