load("@bazel_skylib//rules:native_binary.bzl", "native_binary")

native_binary(
    name = "cli",
    src = "diesel_cli.sh",
)

# FIXME: Something like the following in the main `MODULE.bazel` file should work
# and then we should be able to run a target like `@crates_libraries//diesel_cli__diesel`
# or similar.
#
# ```bazel
# crate.annotation(
#     repositories = ["crates_libraries"],
#     crate = "diesel_cli",
#     # gen_binaries = ["diesel"],
#     gen_all_binaries = True,
# )
# ```
#
