load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "metatypes",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob(["**/*.h"]),
    visibility = ["//apps/finances/qt:__subpackages__"],
    deps = [
        "//libraries/finances/accounts/cpp/models",
        "//libraries/utils/cpp/libpqxx/orm",
        "@rules_qt//:qt_core",
    ],
)
