"""
A collection of utilities for C++
"""

load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "integral_type",
    hdrs = ["integral_type.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//bazel/logging:spdlog",
        "@libpqxx",
    ],
)

cc_library(
    name = "string_type",
    hdrs = ["string_type.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "string_literal",
    hdrs = ["string_literal.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//bazel/logging:spdlog",
    ],
)

cc_library(
    name = "enumerate",
    hdrs = ["enumerate.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "type_name",
    hdrs = ["type_name.hpp"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "expected_type",
    hdrs = ["expected_type.hpp"],
    visibility = ["//visibility:public"],
    deps = [
        "//bazel/logging:spdlog",
        "//libraries/utils/cpp/concepts:alternative_c",
    ],
)
