load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "models",
    srcs = glob(["**/*.cpp"]),
    hdrs = glob(["**/*.h"]),
    visibility = ["//apps/finances/qt:__subpackages__"],
    deps = [
        "//libraries/finances/accounts/cpp/models",
        "//libraries/finances/investments/cpp/models",
        # "//libraries/utils/cpp:enumerate",
        # "//libraries/utils/cpp/qt/models",
        # "@magic_enum",
        # "@rules_qt//:qt_core",
        # "@rules_qt//:qt_gui",
    ],
)
