name: Buildifier

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: buildifier
        run: bazel run --enable_bzlmod //.github/workflows:buildifier.check
