name: Create Release
on:
  workflow_dispatch:
    branches:
      - master
    inputs:
      app:
        type: choice
        description: The application to tag
        options:
        - finances
        - photodb
        - syncronia
        - board_games

env:
  BAZEL_CONFIG: "--config=ci"
  BAZEL_REMOTE_CACHE_URL: "grpc://bazel-remote:9092"
  BAZEL_DISK_CACHE_PATH: "~/.cache/bazel-disk-cache"

jobs:
  release:
    runs-on: "self-hosted"  # Run only locally
    steps:
      - uses: actions/checkout@v7

      - name: Configure bazel-remote
        run: |
          echo "build --remote_cache=$BAZEL_REMOTE_CACHE_URL" >> user.bazelrc
          echo "build --remote_timeout=10" >> user.bazelrc
          echo "build --remote_upload_local_results" >> user.bazelrc
          echo "build $BAZEL_CONFIG" >> user.bazelrc

      - name: Release
        run: just apps ${{ inputs.app }} release
