name: Static checks

# Controls when the action will run.
on:
  pull_request:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: buildifier
        run: bazel run --enable_bzlmod //.github/workflows:buildifier.check
      - name: pre-commit
        run: pre-commit run --all-files
