name: Update deps

on:
  workflow_dispatch:
  schedule:
    - cron: "30 11 * * 2"

env:
  BRANCH_NAME: "update-deps"

jobs:
  # This job will find out if any self-hosted runner is available and return it
  # (otherwise it returns the 'ubuntu-latest'). The purpose is to use self-hosted runners as
  # much as possible to save GitHub quota.
  #
  # Credit: https://github.com/orgs/community/discussions/20019#discussioncomment-7173595
  check-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}
    steps:
      - name: Set runner
        id: set-runner
        run: |
          runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runners")
          echo "runners: $runners"
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" and .busy == false and .labels[] .name == "self-hosted")' || "")
          if [ -n "$available" ]; then
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "Self-host is not available, however, we are only running this job locally"
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
          fi

  just-update:
    needs:
      - check-runner
    runs-on: ${{ needs.check-runner.outputs.runner-label }}
    permissions: # Full list of permissions: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#account-permissions
      contents: write
      actions: write
      # workflows: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Checkout $BRANCH_NAME
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          git checkout $BRANCH_NAME || git checkout -b "$BRANCH_NAME" --track "origin/$BRANCH_NAME" || git checkout -b "$BRANCH_NAME"
          git push --set-upstream origin "$BRANCH_NAME"

      - name: Install requirements
        if: ${{ needs.check-runner.outputs.runner-label != 'self-hosted' }}
        run: |
          # Install just
          mkdir -p ~/bin
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
          export PATH="$PATH:$HOME/bin"
          ~/bin/just --help
          # Install precommit
          pip install pre-commit
          pre-commit install

      - name: Cache Bazel
        if: ${{ needs.check-runner.outputs.runner-label != 'self-hosted' }}
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.cache/bazel-disk-cache
          key: ${{ runner.os }}-bazel-${{ hashFiles('.bazelversion', '.bazelrc', 'MODULE.bazel.lock', 'Cargo.lock', 'pnpm-lock.yaml', 'bazel/third_party/requirements.lock') }}
          restore-keys: |
            ${{ runner.os }}-bazel-

      - name: Configure disk-cache
        if: ${{ needs.check-runner.outputs.runner-label != 'self-hosted' }}
        run: |
          echo "build --disk_cache=~/.cache/bazel-disk-cache" >> user.bazelrc
          echo "test --disk_cache=~/.cache/bazel-disk-cache" >> user.bazelrc

      - name: Configure bazel-remote
        if: ${{ needs.check-runner.outputs.runner-label == 'self-hosted' }}
        run: |
          echo "build --remote_cache=$BAZEL_REMOTE_CACHE_URL" >> user.bazelrc
          echo "build --remote_timeout=10" >> user.bazelrc
          echo "build --remote_upload_local_results" >> user.bazelrc

      - name: Run just update
        run: |
          ~/bin/just update
          pre-commit run

      - name: Create Pull Request
        run: |
          git add -A
          git status
          # Commit (--no-verify), we really want to create the PR
          git -c author.name=jgsogo -c author.email=jgsogo@users.noreply.github.com -c committer.name=github-actions[bot] -c committer.email=github-actions[bot]@users.noreply.github.com commit -m "Update all deps" --no-verify
          git push
          gh pr create -B master -H $BRANCH_NAME --title '🤖 Bump deps (`just update`)' --body 'Dependency updates using `just update`'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
