// @generated by protoc-gen-connect-es v1.4.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file apps/finances/tauri/protocol/protos/account.proto (package finances_app, syntax proto3)
/* eslint-disable */
// @ts-nocheck

