// @generated by protoc-gen-es v2.2.3 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file apps/finances/tauri/protocol/protos/account.proto (package finances_app, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file apps/finances/tauri/protocol/protos/account.proto.
 */
export declare const file_apps_finances_tauri_protocol_protos_account: GenFile;

/**
 * @generated from message finances_app.Account
 */
export declare type Account = Message<"finances_app.Account"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: optional string description = 2;
   */
  description?: string;

  /**
   * @generated from field: optional google.protobuf.Timestamp open = 3;
   */
  open?: Timestamp;
};

/**
 * Describes the message finances_app.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export declare const AccountSchema: GenMessage<Account>;

